from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent;P=Path('/home/jing/m7-lean-default-query-formalization');S='M7.DefaultQuery.';A='∀ (N : ℕ) [NeZero N] (q : '+S+'Query)';C='M7.Action.Recipe N';R='M7.Action.Record N';feas=S+'feasible q base placed';caps='(match q.localityCap with | none => True | some cap => '+S+'locality placed ≤ cap) ∧ (match q.radiusCap with | none => True | some cap => '+S+'radius placed ≤ cap)';win=S+'winners q base';act=lambda g:f'M7.Action.act {g} base';obj=lambda g:S+'objective q ('+act(g)+')';fq=lambda g:S+'feasible q base ('+act(g)+')';rows=[
('sector_modes',[],A+f' (base placed : {C}), (q.sectorMode = {S}SectorMode.classSector → ({S}sectorTest q base placed ↔ ∃ g : {R}, {S}allows q ({S}signature (M7.Action.act g base)))) ∧ (q.sectorMode = {S}SectorMode.placementSector → ({S}sectorTest q base placed ↔ {S}allows q ({S}signature placed)))','Unfold sectorTest and rewrite the explicit mode. Class-sector witness is allowed at a different placement; placement-sector tests the returned literal pair. No signature transport assumption replaces the literal predicate.'),
('noLogical_policy',[],A+f' (base placed : {C}), ({S}needsDistance q → {S}distance placed = none → ¬ {feas}) ∧ (q.distanceFloor = none → {S}Coordinate.negativeDistance ∉ q.objectives → ({feas} ↔ {S}valid N q ∧ {S}dimension placed ∈ q.dimensions ∧ {S}sectorTest q base placed ∧ {caps}))','Unfold feasible and needsDistance. A demanded distance conflicts with Option.isSome none. When floor is none and no negativeDistance coordinate is requested, both distance guards reduce to True; all other query tests remain. This explicitly permits NoLogical when no numerical distance is requested, and assigns no infinite distance.'),
('literal_fiber',[],A+f' (base : {C}) (g h : {R}), {act("g")} = {act("h")} → (({fq("g")} ↔ {fq("h")}) ∧ {obj("g")} = {obj("h")})','Every label is computed from the literal pair: signature is actual M6 polynomial gcd, dimension twice its degree, distance actual M6.Final.quantumDistance, locality/radius from that same pair. Rewrite the image equality; class-sector term uses the common base and is constant. No unconnected label-oracle premise is present.'),
('winners_exact',[],A+f' (base : {C}), (∀ g : {R}, g ∈ {win} ↔ {fq("g")} ∧ ∀ h : {R}, {fq("h")} → ¬ M7.Selection.better q.order ({obj("h")}) ({obj("g")})) ∧ ({win} = ∅ ↔ ¬ ∃ g : {R}, {fq("g")})','Instantiate accepted M7.Selection.selector_exact on actual Action.Record univ with the concrete feasible/objective functions. Simplify only univ membership and feasibleSet emptiness; preserve all ties and modes. This is an actual query application, not an assumed evaluator.'),
('invalid_rejection',['winners_exact'],A+f' (base : {C}), (¬ {S}valid N q → {S}answer q base = Except.error {S}QueryError.invalidSignature ∧ {win} = ∅) ∧ ({S}valid N q → {S}answer q base = Except.ok ({win}))','Unfold answer and split the validity branch. Invalid signatures return an explicit error, distinguished from a valid empty answer. For the no-winners component use winners_exact and the first valid conjunct of feasible. A valid query returns ok with its actual finite winner set.'),
('strict_dominator',[],A+f' (base : {C}) (g : {R}), {fq("g")} → g ∉ {win} → ∃ h ∈ {win}, M7.Selection.better q.order ({obj("h")}) ({obj("g")})','Apply accepted selector_strict_dominator with actual Action.Record univ, concrete literal-support query predicates and objectives. All strict-order premises were already discharged for actual Pareto/lex in Selection12.'),
('empty_objectives',[],A+f' (base : {C}), q.objectives = [] → {win} = M7.Selection.feasibleSet Finset.univ (fun g : {R} => {fq("g")})','Use accepted M7.Selection.empty_objectives. Destructure Query or generalize/rewrite its objectives field so its dependent Fin length becomes Fin0; no objective coordinate can be strictly better. Keep every feasible action tie.'),
('presentation_exact',[],A+f' (base : {C}), (∀ g ∈ {win}, ∃! h : {R}, {S}present q base h ∧ {act("h")} = {act("g")} ) ∧ (∀ g : {R}, {S}present q base g → g ∈ {win} ∧ ∀ h : {R}, {act("h")} = {act("g")} → M7.ActualPresentation.encode g ≤ M7.ActualPresentation.encode h)','Instantiate verified actual_presentation9 presentation_exact and presentation_sound with concrete DefaultQuery.feasible q base and objective q. winners and actual selected are definitionally the same. The dependency gate must be resolved by canonical actual_presentation9 before launching; no placeholder proof or free presentation oracle is allowed.')]
nodes=[{'id':i,'dependencies':ds,'spec':{'name':S+i,'statement':st,'imports':['M7DefaultQuery','M7SelectionAccepted','M7ActualPresentationAccepted'],'context':'','queries':['finite set minimum lexicographic order'],'guidance':gd+' Return tactic proof lines without leading by; retain exact target and default limits.'},'metadata':{'source_section':'M7 original §2/8/9 actual default query and physical ties','fallback_queries':['algebra']}}for i,ds,st,gd in rows];source=Path('/home/jing/quantum_code_discovery_proof/research_checkpoints/m7_compact_selector_final_20260915/PROOF.md');g={'title':'M7 default query using literal signature/locality and actual M6 quantum distance','source':str(source),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'scope':'Actual default query semantics, NoLogical policy, all finite Pareto/lex ties and unique actual physical presentations. Full structural coverage and class-label cached evaluation remain root integration.','nodes':nodes};(H/'graph.json').write_text(json.dumps(g,ensure_ascii=False,indent=2)+'\n');s='import M7DefaultQuery\nimport M7SelectionAccepted\nimport M7ActualPresentationAccepted\n\n'
for i,ds,st,gd in rows:s+='noncomputable def M7.DefaultQueryTarget.'+i+' : Prop :=\n  '+st+'\n\n#check M7.DefaultQueryTarget.'+i+'\n\n'
for d in [H/'lean',P]:(d/'GraphPreflight.lean').write_text(s)
