import M6ActualCountsDependencies
#print axioms M6.Coordinates.block_coeff
#print axioms M6.Coordinates.block_degree
#print axioms M6.Coordinates.block_reconstruct
#print axioms M6.Coordinates.encode_sum
#print axioms M6.Coordinates.modulus_monic_degree
#print axioms M6.Coordinates.root_period
#print axioms M6.Coordinates.encode_injective
#print axioms M6.Coordinates.encode_polynomial
#print axioms M6.Coordinates.encode_surjective
#print axioms M6.Coordinates.rootPow_add
#print axioms M6.Coordinates.encode_conv
#print axioms M6.BoundaryFibers.annihilator_general
#print axioms M6.BoundaryFibers.boundary_add
#print axioms M6.BoundaryFibers.kernel_iff
#print axioms M6.BoundaryFibers.nonzero_monic
#print axioms M6.BoundaryFibers.signature_nonzero
#print axioms M6.BoundaryFibers.kernel_card
#print axioms M6.BoundaryFibers.fiber_card
#print axioms M6.Flatten.flatten_add
#print axioms M6.Flatten.flatten_dot
#print axioms M6.Flatten.flatten_left
#print axioms M6.Flatten.flatten_right
#print axioms M6.Flatten.flatten_smul
#print axioms M6.Flatten.flatten_weight
#print axioms M6.Flatten.J_involution
#print axioms M6.Flatten.J_weight
#print axioms M6.Flatten.cycle_orthogonal
#print axioms M6.Spaces.boundary_eval
#print axioms M6.Spaces.dual_boundary_eval
#print axioms M6.Spaces.input_card
#print axioms M6.Spaces.boundary_words_iff
#print axioms M6.Spaces.cycle_words_iff
#print axioms M6.Spaces.boundaries_are_cycles
#print axioms M6.Spaces.dual_boundary_card
#print axioms M6.Spaces.logical_words_iff
#print axioms M6.Spaces.zero_not_logical
#print axioms M6.Character.sign_add
#print axioms M6.Character.sign_eq_one
#print axioms M6.Character.character_add
#print axioms M6.Character.sign_sum
#print axioms M6.Character.character_product
#print axioms M6.Character.orthogonality
#print axioms M6.Character.weighted_factorization
#print axioms M6.Character.weighted_macwilliams
#print axioms M6.Character.free_character_factor
#print axioms M6.Character.weight_as_sum
#print axioms M6.Character.pinned_product
#print axioms M6.Character.pinned_macwilliams
#print axioms M6.Character.constant_transform
#print axioms M6.FiberSum.sum_by_fibers
#print axioms M6.Character.dual_cardinality
#print axioms M6.FiberSum.uniform_weighted_sum
#print axioms M6.FiberSum.uniform_cardinality
