from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent;S='M6.EuclidStorage.';E='M6.Euclid.';B=E+'BP';R=S+'Slots'
rows=[
('rem_loop_refines',[],f'∀ (fuel : ℕ) (s : {R}) (c t : ℕ), let r := {S}remLoop fuel s c t; r.slots.p = s.p ∧ r.slots.q = s.q ∧ r.slots.saved = s.saved ∧ r.slots.work = ({E}remainderAux fuel s.work s.q).value ∧ r.cancellations = c + ({E}remainderAux fuel s.work s.q).cancellations ∧ r.rounds = 0 ∧ r.passes = t + ({E}remainderAux fuel s.work s.q).passes', 'Induct fuel generalizing s c t. The actual tail call increments its accumulators before overwriting only work. Split the common remainder stopping guard, instantiate induction with updated slot record, and combine its projection equalities by arithmetic. Keep source algorithm intact.'),
('gcd_loop_refines',['rem_loop_refines'],f'∀ (fuel : ℕ) (s : {R}) (c e t : ℕ), s.work = 0 → let r := {S}gcdLoop fuel s c e t; r.slots.saved = s.saved ∧ r.slots.work = 0 ∧ {S}toRun r = {S}offset ({E}euclidAux fuel s.p s.q) c e t', 'Induct fuel generalizing s and accumulators. q0 and fuel0 return directly. In the other branch apply rem_loop_refines at rank s.p to slots(0,q,p,saved), with c0,t1, matching the complete remainder call. Its q and saved slots are preserved. Apply induction to slots(q,remainder,0,saved), then normalize offset counters. Equality of Run records follows their four field equalities (cases/ext), not an oracle assumption.'),
('gcd_start_refines',['gcd_loop_refines'],f'∀ (p q saved : {B}) (c e t : ℕ), let r := {S}gcdStart p q saved c e t; r.slots.saved = saved ∧ r.slots.work = 0 ∧ {S}toRun r = {S}offset ({E}euclid p q) c e t', 'Instantiate gcd_loop_refines at rankq+1 with slots(p,q,0,saved), initial passes t+1. Unfold only gcdStart, euclid and offset as needed. The initial fuel degree scan is included in both counters.'),
('preprocess_refines',['gcd_start_refines'],f'∀ a b M : {B}, {S}toRun ({S}preprocess a b M) = {E}preprocess a b M', 'Use gcd_start_refines twice. First start has zero accumulators and preserves saved=M; extract its p/value and all counters from toRun equality. Second start reuses the same slots with p=first result,q=M,saved0 and initial accumulators from first run. Match the original shared two-call preprocessing record by fields. No recursive array-frame storage is used in this tail-machine algorithm.'),
('rem_loop_safe',['rem_loop_refines'],f'∀ (fuel : ℕ) (s : {R}) (c t width : ℕ), 0 < width → {S}slotsFit width s → fuel ≤ 32*width → c + ({E}remainderAux fuel s.work s.q).cancellations ≤ 32*width → t + ({E}remainderAux fuel s.work s.q).passes ≤ 32*width → {S}remSafe fuel s c t width', 'Induct fuel with s/c/t generalized. The supplied remaining-run budgets bound all current and terminal counters. In a cancellation branch, accepted Euclid.cancel_drop preserves work width; unfold one remainderAux step in the budgets to obtain the recursive c+1,t+2 budgets. The other three polynomial slots remain unchanged. No final-budget assumption remains in the actual preprocess theorem.'),
('gcd_loop_safe',['rem_loop_safe','rem_loop_refines'],f'∀ (fuel : ℕ) (s : {R}) (c e t width : ℕ), 0 < width → {S}slotsFit width s → s.work = 0 → fuel ≤ 32*width → c + ({E}euclidAux fuel s.p s.q).cancellations ≤ 32*width → e + ({E}euclidAux fuel s.p s.q).rounds ≤ 32*width → t + ({E}euclidAux fuel s.p s.q).passes ≤ 32*width → {S}gcdSafe fuel s c e t width', 'Induct fuel generalizing slots and accumulators. For nonzeroq, use accepted remainder_aux_correct/remainder_passes at rankp to bound the inner local counters by rankp and2rankp+2≤32width; prove its remSafe via rem_loop_safe. rem_loop_refines identifies its preserved q/saved and actual remainder value/counters. remainder_correct preserves width. Unfold one euclidAux step in remaining budgets, rewrite inner result fields, and apply induction at the tail state. The fixed layout retains M and overwrites work.'),
('gcd_start_safe',['gcd_loop_safe'],f'∀ (p q saved : {B}) (c e t width : ℕ), 0 < width → {E}rank p ≤ width → {E}rank q ≤ width → {E}rank saved ≤ width → c + ({E}euclid p q).cancellations ≤ 32*width → e + ({E}euclid p q).rounds ≤ 32*width → t + ({E}euclid p q).passes ≤ 32*width → {S}gcdSafe ({E}rank q+1) ⟨p,q,0,saved⟩ c e (t+1) width', 'Apply gcd_loop_safe. rankq+1≤width+1≤32width since width positive; rankzero=0. Unfold euclid in the budget equalities to account for its extra initial pass. This reusable helper is instantiated without budget premises in preprocess_safe.'),
('preprocess_safe',['gcd_start_safe','gcd_start_refines'],f'∀ (N : ℕ) (a b M : {B}), a.natDegree ≤ N → b.natDegree ≤ N → M.natDegree ≤ N → {S}preprocessSafe (N+1) a b M', 'Set width=N+1>0; rank of each input≤width. For any p,q of such width, accepted euclid_correct and euclid_passes bound cancellations≤2width,rounds≤width,passes≤7width+2≤9width. First gcd_start_safe has zero accumulators. gcd_start_refines preserves M and identifies first output/counters; euclid_output_width bounds its result rank≤width. Second run starts with those first counters, so total budgets are≤4width,2width,18width, all≤32width. Apply gcd_start_safe again. This proves capacity for every actual recursive configuration of both calls.'),
('slots_encoding',[],f'∀ (N : ℕ) (s u : {R}), {S}slotsFit (N+1) s → {S}slotsFit (N+1) u → {E}dense N s.p = {E}dense N u.p → {E}dense N s.q = {E}dense N u.q → {E}dense N s.work = {E}dense N u.work → {E}dense N s.saved = {E}dense N u.saved → s = u', 'Apply accepted Euclid.dense_injective separately to each slot using slotsFit bounds, then prove the Slots records equal by their fields. Four binary arrays thus faithfully encode the complete polynomial store, including retained M.'),
('control_encoding',[],f'∀ (width v : ℕ), v ≤ 32*width → v < 2 ^ ({S}registerBits width)', 'Nat.lt_two_pow_self width gives width<2^width. Multiply by32 and use pow_add with2^5=32 to obtain32width<2^(width+5); registerBits is preciselywidth+5. This is a proven finite encoding capacity, not an unbounded Nat register assumption.'),
('control_values_fit',['control_encoding'],f'∀ (width : ℕ) (s : {R}) (fuel c e t : ℕ), {S}slotsFit width s → fuel ≤ 32*width → c ≤ 32*width → e ≤ 32*width → t ≤ 32*width → ∀ v ∈ {S}controlValues s fuel c e t, v < 2 ^ ({S}registerBits width)', 'Each listed control value is≤32width. Slot ranks≤width; natDegree p≤rankp includingp0, so shifted-XOR offset also≤width. Expand finite-list membership and apply control_encoding. Loop indices/addresses lie in the fixed width range and phase/carry use one bit, accommodated by the reserved sixteen control words.'),
('layout_bound',[],f'∀ N : ℕ, {S}polynomialSlots.length = 4 ∧ {S}controlSlots.length = 16 ∧ {S}actualPreprocessStorage N ≤ 512*(N+1)^2', 'Reduce the two concrete register-layout lists and registerBits. Storage is4width+16(width+5), withwidth=N+1≥1. Derive the loose quadratic bound by elementary natural arithmetic; the512 coefficient is a bound proved after allocation, not its definition.'),
('preprocess_storage',['preprocess_refines','preprocess_safe','slots_encoding','control_values_fit','layout_bound'],f'∀ (N : ℕ) (a b M : {B}), a.natDegree ≤ N → b.natDegree ≤ N → M.natDegree ≤ N → {S}toRun ({S}preprocess a b M) = {E}preprocess a b M ∧ {S}preprocessSafe (N+1) a b M ∧ {S}actualPreprocessStorage N ≤ 512*(N+1)^2', 'Combine the actual tail-slot simulation, full two-call configuration/counter safety, and proved concrete layout bound. The dependencies additionally establish faithful dense slot and finite control-word encoding. Only original polynomial degree bounds remain; no free slots, storage or oracle-correctness premise.')]
nodes=[{'id':i,'dependencies':ds,'spec':{'name':S+i,'statement':st,'imports':['M6EuclidStorage','M6EuclidAccepted'],'context':'','queries':['EuclideanDomain gcd Bezout divisibility'],'guidance':gd+' Return only tactic proof lines without leading by. Keep frozen target and default limits.'},'metadata':{'source_section':'M6 original indexed-array preprocessing storage, with fixed-slot Euclidean implementation','fallback_queries':['polynomial divisibility multiplication cancellation']}}for i,ds,st,gd in rows]
source=H.parents[4]/'research/quantum_m6/research_checkpoints/m6_original_gate_closed_20260915/PROOF.md';g={'title':'M6 Euclid fixed-slot tail simulation and actual storage','source':str(source.relative_to(H.parents[4])),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'scope':'Original Euclidean preprocessing refined to tail-recursive four polynomial slots with bounded control words; actual all-state safety and storage≤512(N+1)^2, independently of cubic time.','nodes':nodes};(H/'graph.json').write_text(json.dumps(g,ensure_ascii=False,indent=2)+'\n')
s='import M6EuclidStorage\nimport M6EuclidAccepted\n\n'
for i,ds,st,gd in rows:s+='noncomputable def M6.EuclidStorageTarget.'+i+' : Prop :=\n  '+st+'\n\n#check M6.EuclidStorageTarget.'+i+'\n\n'
for D in [H/'lean',Path('/home/jing/m6-lean-euclid-storage-formalization')]: (D/'GraphPreflight.lean').write_text(s)
