name = "M7CanonicalClasses"
version = "0.1.0"
defaultTargets = ["M7CanonicalClasses"]
[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "de5ce8a9a66a4aa68a9bdbb35b63a06d34d9ca11"
[[lean_lib]]
name = "M7CanonicalOuter"

[[lean_lib]]
name = "M7Action"

[[lean_lib]]
name = "M7ActionAccepted"

[[lean_lib]]
name = "M7ActionGroup"

[[lean_lib]]
name = "M7CanonicalBlock"

[[lean_lib]]
name = "M7CanonicalBlockAccepted"

[[lean_lib]]
name = "M7ActualOrbit"

[[lean_lib]]
name = "M7ActualOrbitAccepted"

[[lean_lib]]
name = "M7CanonicalClasses"

[[lean_lib]]
name = "M7CanonicalOuterAccepted"

[[lean_lib]]
name = "M7OrbitFibers"

[[lean_lib]]
name = "M7OrbitFibersAccepted"

[[lean_lib]]
name = "M7OrbitResidual"
