from pathlib import Path
import json, hashlib, copy, difflib
repo=Path('/home/jing/quantum_code_discovery_proof')
area=repo/'.humanize-quantum-runs/m7-final-scope-20260915'
source_path=repo/'.humanize-quantum-runs/run-voum358a/call-010/response.json'
source=json.loads(source_path.read_text())['candidate']
c=copy.deepcopy(source)
old='This is a uniform mathematical composition of the checked finite-order M5 arithmetic and M6 exact reduction; it does not declare the authoritative broader M5/M6 obligations resolved or unconditional M7 acceptance. Fresh independent dual reviews and implementation of the full output contract are not claimed.'
new='This uniform mathematical composition proves original M7 at symbolic constructive-selector strength, using the explicitly derived finite-order M5 arithmetic and M6 exact reduction. Fresh independent dual reviews of this exact candidate are pending at author time. Full implementation of every query and replay feature, arbitrary-span efficiency (M8), practical superiority and Lean certification are outside this symbolic claim.'
assert old in c['claim']; c['claim']=c['claim'].replace(old,new)
old_end='Nevertheless, the authoritative obligation retains broader unresolved M5 birth/lift and M6 distance-law dependencies; their milestone acceptance is not inferred from this composition. The requested fresh independent dual reviews of this unchanged integrated argument have not occurred and cannot be represented as completed under the no-agent restriction. Thus unconditional authoritative M7 completion is not claimed.'
new_end='The old harness obligation described M5 and M6 as unresolved even though the current assignment has adopted their arithmetic-workflow and exact-distance-reduction strengths. That historical status does not supply a mathematical gap or a premise. Sections 4–7 directly establish every counting, coverage, distance and witness interface used here. The original M7 symbolic functionality therefore follows from those arguments, without an assumed transversal or unresolved distance oracle. Fresh independent dual reviews of this exact revised candidate remain pending at author time; no prior review vote certifies it.'
assert old_end in c['argument'];c['argument']=c['argument'].replace(old_end,new_end)
c['argument']='Author/provenance note. Sections 1–12 are the harness integrator\'s mathematical composition, with the final milestone-assessment paragraph amended by the controller to match the current task. Source-inspection and nonexecution statements in those sections refer to the original integrator turn. Section 13 and the revised claim are the controller\'s acceptance argument, submitted for fresh full-scope review; they carry no inherited review authority. The mathematical formulas, algorithms, hypotheses and resource bounds in sections 2–11 are unchanged.\n\n'+c['argument']
c['argument']+='''\n\n13. Original milestone gate and current scope.\nThe original roadmap §12 defines M7 as "All certified optima for requested parameters without raw scan". Section 11 permits symbolic conclusions throughout their written hypotheses and separates them from finite certificates. The original M6 gate permits a proved domain, and its distance task permits an exact certified reduction. The current M5 arithmetic-workflow and M6 exact-reduction adoption records do not need to be taken as axioms: §§4–7 derive the exact interfaces invoked by this selector. No global birth estimate, distance predictor, finite catalogue value or SELF premise is used.\n\nThe domain and exact default query language in §2 cover arbitrary finite order and positive equal support weight, requested dimensions and sectors, exact distance floors or objectives, and actual joint locality caps or objectives. Sections 3–6 construct and certify the complete structural transversal rather than requiring it as input. Section 7 computes exact distance and minimum logical witnesses for every generated class, including even orders and NoLogical. Sections 8–9 prove both optimum directions, retain all ties and supply terminating reconstruction of all requested action records and distinct physical presentations. Section 10 supplies explicit arithmetic and finite-loop certificate replay, including omitted-record and empty-answer checks. Section 11 establishes the exact no-raw-support-pair-generation property and discloses action evaluation and output costs. These facts meet each clause of the original M7 symbolic gate.\n\nThis assessment does not strengthen M1–M4 beyond their declared domains, assert quantum-code inequivalence, or require M8 all-span polynomial efficiency. It does not certify an implementation of every theoretical interface. Section 12 accurately describes the earlier frozen compact prototype: its limits do not create a missing step in the mathematical construction, but must accompany any implementation report. Later decoder code and finite tests are separate evidence, not premises of this candidate. Workflow acceptance still requires fresh independent reviews of this exact entire claim, mathematical composition and gate assessment; reviewer disagreement must be investigated rather than overridden by this intended conclusion.\n'''
c['scope']='selected_obligation'
c['remaining_obligations']=[
 'Obtain fresh independent dual reviews of this exact revised candidate, including the full mathematical composition and original-M7 gate assessment. No inherited review vote is valid for this new hash.',
 'A complete software implementation and audit of every query, logical-witness retention and replay feature is outside this symbolic proof. The frozen compact prototype and later decoder have explicitly limited tested interfaces.',
 'M8 arbitrary-span efficiency, practical superiority, Lean certification and quantum-code classification are separate targets, not unresolved internal steps of the original M7 symbolic selector theorem.'
]
p=repo/'RESEARCH_PROBLEM_AND_TAKEOVER_ROADMAP.md'
c['dependencies'].append({'path':str(p.relative_to(repo)),'section':'§§10–12: original distance alternatives, certificate boundary and M7 acceptance criterion; historical status column is not current milestone status','sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
for ref in c['dependencies']:
 p=repo/ref['path'];assert hashlib.sha256(p.read_bytes()).hexdigest()==ref['sha256'],ref['path']
def canonical(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'))
(area/'source-candidate.json').write_text(json.dumps(source,ensure_ascii=False,indent=2)+'\n')
(area/'candidate.json').write_text(json.dumps(c,ensure_ascii=False,indent=2)+'\n')
(area/'audit-seed.json').write_text(json.dumps([{'candidate':c,'kind':'integration'}],ensure_ascii=False,indent=2)+'\n')
(area/'scope-amendment.diff').write_text(''.join(difflib.unified_diff(json.dumps(source,ensure_ascii=False,indent=2).splitlines(True),json.dumps(c,ensure_ascii=False,indent=2).splitlines(True),fromfile='original-integrator-candidate',tofile='current-scope-final-candidate')))
receipt={'source':str(source_path.relative_to(repo)),'source_candidate_sha256':hashlib.sha256(canonical(source).encode()).hexdigest(),'candidate_sha256':hashlib.sha256(canonical(c).encode()).hexdigest(),'mathematical_sections_2_through_11_changed':False,'changes':['claim and scope updated to original M7 symbolic gate','obsolete M5/M6 status conclusion replaced with explicit interface-based assessment','original roadmap gate dependency and section13 added','remaining work separates final review and software completeness from mathematical theorem'],'historical_review_votes_imported':0}
(area/'amendment-provenance.json').write_text(json.dumps(receipt,indent=2)+'\n')
print(json.dumps(receipt,indent=2))
