import { useState, useMemo } from 'react';
import {
  useJournalSessions, useJournalMilestones, useJournalSummary,
  useJournalRecommendations, useJournalAllMilestones,
} from '../hooks/useApi';
import { useGitHead, useGitLog } from '../hooks/useGitLog';
import { aggregateTargets } from '../utils/aggregate';
import { STATUS_COLORS } from '../utils/constants';
import MilestoneCard from '../components/MilestoneCard';
import AttemptCard from '../components/AttemptCard';
import MarkdownBlock from '../components/MarkdownBlock';
import { truncateSubject } from '../utils/format';
import styles from './Journal.module.css';

type Tab = 'milestones' | 'targets';

export default function Journal() {
  const { data: sessions } = useJournalSessions();
  const [activeSession, setActiveSession] = useState('');
  const [tab, setTab] = useState<Tab>('milestones');

  // --- Milestones tab data (per-session) ---
  const currentSession = activeSession || (sessions?.length ? sessions[sessions.length - 1].id : '');
  const { data: milestones } = useJournalMilestones(currentSession);
  const { data: summaryData } = useJournalSummary(currentSession);
  const { data: recsData } = useJournalRecommendations(currentSession);

  // --- Targets tab data (cross-session) ---
  const { data: allMilestoneData } = useJournalAllMilestones();
  const { data: headData } = useGitHead();
  const { data: gitData } = useGitLog();
  const head = headData?.commit;

  // Commits reachable from the current HEAD — sessions from other branches
  // must not pollute the Journal banner. Without this filter the view can
  // pick up e.g. an iter-2 commit from `main` while you're forked at iter-1.
  const reachableFromHead = useMemo(() => {
    const reachable = new Set<string>();
    if (!head || !gitData?.commits) return reachable;
    const bySha = new Map(gitData.commits.map(c => [c.sha, c]));
    const stack = [head.sha];
    while (stack.length) {
      const sha = stack.pop()!;
      if (reachable.has(sha)) continue;
      reachable.add(sha);
      const c = bySha.get(sha);
      if (c) for (const p of c.parents) stack.push(p);
    }
    return reachable;
  }, [head, gitData]);

  // Map the selected session_NNN to its iter-NNN review commit. Sessions are
  // produced by the review agent once per iteration, so the numeric suffix
  // lines up with the iter index.
  const sessionCommit = useMemo(() => {
    if (!currentSession || !gitData?.commits) return undefined;
    const match = currentSession.match(/session_(\d+)/);
    if (!match) return undefined;
    const iterId = `iter-${String(parseInt(match[1], 10)).padStart(3, '0')}`;
    const reachable = (c: typeof gitData.commits[number]) =>
      reachableFromHead.size === 0 || reachableFromHead.has(c.sha);
    return gitData.commits.find(c => reachable(c) && c.iteration === iterId && c.phase === 'review')
      ?? gitData.commits.find(c => reachable(c) && c.iteration === iterId);
  }, [currentSession, gitData, reachableFromHead]);

  const allAggregated = useMemo(() => {
    if (!allMilestoneData?.length) return [];
    return aggregateTargets(allMilestoneData);
  }, [allMilestoneData]);

  const hasAnySessions = !!sessions?.length;
  const currentMeta = sessions?.find(s => s.id === currentSession);
  const hasSessionContent = currentMeta?.hasMilestones || currentMeta?.hasSummary || currentMeta?.hasRecommendations;

  if (!hasAnySessions && !allMilestoneData?.length) {
    return (
      <div className={styles.empty}>
        <p><strong>No review sessions yet.</strong></p>
        <p>Journal data is generated by the review agent after each prover iteration.</p>
        <p>Make sure <code>archon-loop.sh</code> is running without <code>--no-review</code>, or run <code>./review.sh /path/to/project</code> manually.</p>
      </div>
    );
  }

  // Show the session-specific commit when on the Milestones tab (it reflects the
  // review commit behind the currently inspected session). Otherwise fall back to
  // the repo HEAD so users still see where "now" is.
  const bannerCommit = tab === 'milestones' && sessionCommit
    ? { shortSha: sessionCommit.shortSha, branch: sessionCommit.branch ?? 'main', subject: sessionCommit.subject }
    : head;

  return (
    <div className={styles.root}>
      {bannerCommit && (
        <div className={styles.commitBanner} title={bannerCommit.subject}>
          <span className={styles.commitSha}>{bannerCommit.shortSha}</span>
          <span className={styles.commitBranch}>{bannerCommit.branch}</span>
          <span className={styles.commitSubject}>{truncateSubject(bannerCommit.subject, 100)}</span>
          {tab === 'milestones' && sessionCommit && (
            <span className={styles.commitSessionHint}>session {currentSession.replace('session_', '#')}</span>
          )}
        </div>
      )}
      {/* Top-level tabs: Milestones (per-session) | Targets (global) */}
      <div className={styles.tabs}>
        <button className={`${styles.tab} ${tab === 'milestones' ? styles.tabActive : ''}`} onClick={() => setTab('milestones')}>Milestones</button>
        <button className={`${styles.tab} ${tab === 'targets' ? styles.tabActive : ''}`} onClick={() => setTab('targets')}>Targets</button>
      </div>

      {/* ── Milestones tab ── */}
      {tab === 'milestones' && (
        <div className={styles.content}>
          {/* Session selector */}
          {hasAnySessions && (
            <div className={styles.sessionBar}>
              {sessions!.map(s => (
                <button key={s.id}
                  className={`${styles.sessionBtn} ${(currentSession === s.id) ? styles.sessionBtnActive : ''}`}
                  onClick={() => setActiveSession(s.id)}>
                  {s.id.replace('session_', 'Session #')}
                  {!s.hasMilestones && !s.hasSummary && <span style={{ opacity: 0.4 }}> ○</span>}
                </button>
              ))}
            </div>
          )}

          {!hasSessionContent && (
            <div className={styles.empty}>
              <p><strong>Session {currentSession.replace('session_', '#')} — waiting for review data</strong></p>
              <p>The review agent creates milestones, summary, and recommendations after analyzing prover results.</p>
            </div>
          )}

          {/* Milestones */}
          {milestones && milestones.length > 0 && (
            <div className={styles.section}>
              <div className={styles.sectionLabel}>Milestones</div>
              {milestones.map((m, i) => <MilestoneCard key={i} milestone={m} />)}
            </div>
          )}

          {/* Summary */}
          {summaryData?.content && (
            <div className={styles.section}>
              <div className={styles.sectionLabel}>Summary</div>
              <div className={styles.card}><MarkdownBlock content={summaryData.content} className={styles.markdown} /></div>
            </div>
          )}

          {/* Recommendations */}
          {recsData?.content && (
            <div className={styles.section}>
              <div className={styles.sectionLabel}>Recommendations</div>
              <div className={styles.card}><MarkdownBlock content={recsData.content} className={styles.markdown} /></div>
            </div>
          )}
        </div>
      )}

      {/* ── Targets tab (global, independent of session selection) ── */}
      {tab === 'targets' && (
        <div className={styles.content}>
          {allAggregated.length === 0 && (
            <div className={styles.empty}>No targets found across any session</div>
          )}
          {allAggregated.map((t, i) => (
            <div key={i} className={styles.targetCard} style={{ borderLeftColor: STATUS_COLORS[t.status] || 'var(--border)' }}>
              <div className={styles.targetHeader}>
                <code className={styles.targetFile}>{t.file}</code>
                <span className={styles.targetTheorem}>{t.theorem}</span>
                <span className={styles.badge} style={{ color: STATUS_COLORS[t.status] }}>{t.status}</span>
              </div>
              <div className={styles.targetMeta}>
                {t.sessions.length} session{t.sessions.length > 1 ? 's' : ''} · {t.totalAttempts} attempt{t.totalAttempts !== 1 ? 's' : ''}
                {t.sessions.length > 1 && (
                  <span className={styles.sessionFlow}>
                    {t.sessions.map(s => s.replace('session_', '#')).join(' → ')}
                  </span>
                )}
              </div>
              {t.milestones.map((m, mi) => (
                <div key={mi}>
                  {t.sessions.length > 1 && (
                    <div className={styles.sessionTag}>
                      {(m as any).sessionId?.replace('session_', '#') || `#${mi + 1}`}
                      {' · '}
                      <span style={{ color: STATUS_COLORS[m.status] }}>{m.status}</span>
                    </div>
                  )}
                  {m.attempts && m.attempts.length > 0 && (
                    <div className={styles.attempts}>
                      {m.attempts.map((att, ai) => <AttemptCard key={ai} att={att} />)}
                    </div>
                  )}
                </div>
              ))}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
