import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Physlib.Units.WithDim.Basic

/- USER: The assigned Lean file did not exist when this autoformalization task began. -/

noncomputable section

namespace PhyXMiniProblems.ProblemPhyXMini0982

open Dimension

/-!
# Current generated by a rotating conducting spherical shell

The primary raster `982.png` shows a conducting spherical shell of radius
`10.0 cm` rotating at `2 Hz` about a vertical axis.  A uniform `1.00 T`
magnetic field points downward along that axis.  Stationary radial rods make
brush contact at the top of the sphere and at polar angle `60.0°`; their outer
ends are joined through a `10.0 Ω` resistor.

Physical magnitudes are represented by Physlib's unit-independent
`Dimensionful` quantities.  Real numbers occur only as coherent-SI readouts,
dimensionless angles, literal figure labels, and displayed answer values.

Assumption/target split:

* governing laws: `ω = 2πf`, the rotating-conductor motional-emf law between
  two polar contacts, and Ohm's law for the closed external circuit;
* previous-part results: none;
* figure/data readouts: conducting components and brush topology, vertical
  rotation axis, downward uniform field, radial contacts at `0°` and `60°`,
  `r = 10.0 cm`, `f = 2 Hz`, `B = 1.00 T`, and `R = 10.0 Ω`;
* current target conclusions: the current magnitude is exactly `3π/2000 A`,
  and hence the uniquely closest listed answer is B, `4.73 mA`.

The current and motional emf are independent fields of the setup.  Neither is
defined by the requested numerical answer, and no premise below states either
target conclusion.
-/

/-! ## Dimensions, physical magnitudes, and coherent-SI readouts -/

/-- Frequency and angular speed both have inverse-time dimension. -/
def inverseTimeDimension : Dimension := T𝓭⁻¹

/-- Magnetic flux density has SI dimension `M T⁻¹ C⁻¹` (tesla). -/
def magneticFluxDensityDimension : Dimension :=
  M𝓭 * T𝓭⁻¹ * C𝓭⁻¹

/-- Electric potential has SI dimension `M L² T⁻² C⁻¹` (volt). -/
def electricPotentialDimension : Dimension :=
  M𝓭 * L𝓭 * L𝓭 * T𝓭⁻¹ * T𝓭⁻¹ * C𝓭⁻¹

/-- Electric current has SI dimension `C T⁻¹` (ampere). -/
def electricCurrentDimension : Dimension :=
  C𝓭 * T𝓭⁻¹

/-- Electrical resistance has SI dimension `M L² T⁻¹ C⁻²` (ohm). -/
def electricalResistanceDimension : Dimension :=
  M𝓭 * L𝓭 * L𝓭 * T𝓭⁻¹ * C𝓭⁻¹ * C𝓭⁻¹

/-- A nonnegative, unit-independent physical length. -/
abbrev LengthMagnitude : Type :=
  Dimensionful (WithDim L𝓭 NNReal)

/-- A nonnegative, unit-independent rotation frequency. -/
abbrev FrequencyMagnitude : Type :=
  Dimensionful (WithDim inverseTimeDimension NNReal)

/-- A nonnegative, unit-independent angular speed. -/
abbrev AngularSpeedMagnitude : Type :=
  Dimensionful (WithDim inverseTimeDimension NNReal)

/-- A nonnegative, unit-independent magnetic-flux-density magnitude. -/
abbrev MagneticFluxDensityMagnitude : Type :=
  Dimensionful (WithDim magneticFluxDensityDimension NNReal)

/-- A nonnegative, unit-independent electrical resistance. -/
abbrev ResistanceMagnitude : Type :=
  Dimensionful (WithDim electricalResistanceDimension NNReal)

/-- A nonnegative, unit-independent electromotive-force magnitude. -/
abbrev ElectromotiveForceMagnitude : Type :=
  Dimensionful (WithDim electricPotentialDimension NNReal)

/-- A nonnegative, unit-independent electric-current magnitude. -/
abbrev ElectricCurrentMagnitude : Type :=
  Dimensionful (WithDim electricCurrentDimension NNReal)

/-- Coherent-SI scalar readout of a nonnegative dimensionful magnitude. -/
def coherentSIReadout {d : Dimension}
    (quantity : Dimensionful (WithDim d NNReal)) : ℝ :=
  ((quantity UnitChoices.SI).val : ℝ)

/-- Read a length magnitude in metres. -/
def lengthInMeters (length : LengthMagnitude) : ℝ :=
  coherentSIReadout length

/-- Read a rotation frequency in hertz. -/
def frequencyInHertz (frequency : FrequencyMagnitude) : ℝ :=
  coherentSIReadout frequency

/-- Read an angular speed in radians per second. -/
def angularSpeedInRadiansPerSecond (angularSpeed : AngularSpeedMagnitude) : ℝ :=
  coherentSIReadout angularSpeed

/-- Read a magnetic-flux-density magnitude in teslas. -/
def magneticFluxDensityInTeslas
    (fieldMagnitude : MagneticFluxDensityMagnitude) : ℝ :=
  coherentSIReadout fieldMagnitude

/-- Read an electrical resistance in ohms. -/
def resistanceInOhms (resistance : ResistanceMagnitude) : ℝ :=
  coherentSIReadout resistance

/-- Read an electromotive-force magnitude in volts. -/
def electromotiveForceInVolts (emf : ElectromotiveForceMagnitude) : ℝ :=
  coherentSIReadout emf

/-- Read an electric-current magnitude in amperes. -/
def currentInAmperes (current : ElectricCurrentMagnitude) : ℝ :=
  coherentSIReadout current

/-- Convert a degree readout into its dimensionless radian value. -/
def radiansFromDegrees (degrees : ℝ) : ℝ :=
  degrees * Real.pi / 180

/-! ## Physical roles, contact geometry, and primary-raster vocabulary -/

/-- The two brush-contact locations on the spherical shell. -/
inductive SphereContact where
  | top
  | oblique
  deriving DecidableEq, Fintype, Repr

/-- Orientations needed to state the axis geometry. -/
inductive AxisOrientation where
  | vertical
  | horizontal
  | other
  deriving DecidableEq, Repr

/-- Directions along the vertical rotation axis. -/
inductive AxialDirection where
  | upward
  | downward
  deriving DecidableEq, Repr

/-- Qualitative models for the applied magnetic field. -/
inductive MagneticFieldRegime where
  | constantUniform
  | nonuniform
  | timeDependent
  deriving DecidableEq, Repr

/-- Motion of a conductor relative to the laboratory frame. -/
inductive ConductorMotion where
  | rotatesWithSphere
  | stationaryInSupportFrame
  deriving DecidableEq, Repr

/-!
Literal presentation data visible in the primary raster.  Numerical fields
are the printed scalar labels; the calibration predicate below ties them to
dimensionful physical magnitudes.
-/
structure RotatingSphereCircuitFigure where
  sphereShown : Bool
  verticalTopRodShown : Bool
  obliqueRodShown : Bool
  brushContactsShown : SphereContact → Bool
  radialRodShown : SphereContact → Bool
  closingWireShown : Bool
  resistorShownInClosingWire : Bool
  downwardMagneticFieldArrowShown : Bool
  rotationRateArrowShown : Bool
  sixtyDegreeArcShown : Bool
  radiusLabelCentimeters : ℝ
  rotationRateLabelHertz : ℝ
  magneticFieldLabelTeslas : ℝ
  obliqueAngleLabelDegrees : ℝ
  resistanceLabelOhms : ℝ

/-!
Independent physical objects and observables in the experiment.  In
particular, `motionalEmfMagnitude` and `wireCurrentMagnitude` are not defined
by the target formula or an answer choice.
-/
structure RotatingSphereCircuitSetup where
  shellRadius : LengthMagnitude
  rotationFrequency : FrequencyMagnitude
  angularSpeed : AngularSpeedMagnitude
  magneticFluxDensityMagnitude : MagneticFluxDensityMagnitude
  resistorResistance : ResistanceMagnitude
  motionalEmfMagnitude : ElectromotiveForceMagnitude
  wireCurrentMagnitude : ElectricCurrentMagnitude
  contactPolarAngleRadians : SphereContact → ℝ
  rotationAxisOrientation : AxisOrientation
  magneticFieldDirection : AxialDirection
  magneticFieldRegime : MagneticFieldRegime
  shellMotion : ConductorMotion
  rodMotion : SphereContact → ConductorMotion
  shellIsConducting : Bool
  rodIsConducting : SphereContact → Bool
  brushMakesConductingContact : SphereContact → Bool
  rodExtendsRadially : SphereContact → Bool
  outerRodEndsConnectedByWire : Bool
  resistorIncludedInClosingWire : Bool
  figure : RotatingSphereCircuitFigure

/-! ## Scenario data, primary-image evidence, and governing laws -/

/-- Qualitative physical setup specified by the prose. -/
structure MatchesConductingSphereScenario
    (setup : RotatingSphereCircuitSetup) : Prop where
  shellConducts : setup.shellIsConducting = true
  rodsConduct : ∀ contact, setup.rodIsConducting contact = true
  brushesConduct : ∀ contact,
    setup.brushMakesConductingContact contact = true
  rodsAreRadial : ∀ contact, setup.rodExtendsRadially contact = true
  axisIsVertical : setup.rotationAxisOrientation = .vertical
  shellRotates : setup.shellMotion = .rotatesWithSphere
  rodsAreFrameSupported : ∀ contact,
    setup.rodMotion contact = .stationaryInSupportFrame
  fieldIsConstantAndUniform :
    setup.magneticFieldRegime = .constantUniform
  fieldPointsDownward : setup.magneticFieldDirection = .downward
  outerEndsAreConnected : setup.outerRodEndsConnectedByWire = true
  resistorClosesCircuit : setup.resistorIncludedInClosingWire = true

/-!
Primary-raster evidence and calibrations for every printed numerical label.
The polar angles are figure-derived geometry, not conclusions about current.
-/
structure MatchesPrimaryRotatingSphereFigure
    (setup : RotatingSphereCircuitSetup) : Prop where
  sphereIsShown : setup.figure.sphereShown = true
  topRodIsShown : setup.figure.verticalTopRodShown = true
  obliqueRodIsShown : setup.figure.obliqueRodShown = true
  bothBrushesAreShown : ∀ contact,
    setup.figure.brushContactsShown contact = true
  bothRodsAreShownRadial : ∀ contact,
    setup.figure.radialRodShown contact = true
  closingWireIsShown : setup.figure.closingWireShown = true
  resistorIsShown : setup.figure.resistorShownInClosingWire = true
  downwardFieldArrowIsShown :
    setup.figure.downwardMagneticFieldArrowShown = true
  rotationArrowIsShown : setup.figure.rotationRateArrowShown = true
  angleArcIsShown : setup.figure.sixtyDegreeArcShown = true
  radiusLabel : setup.figure.radiusLabelCentimeters = 10.0
  frequencyLabel : setup.figure.rotationRateLabelHertz = 2
  magneticFieldLabel : setup.figure.magneticFieldLabelTeslas = 1.00
  obliqueAngleLabel : setup.figure.obliqueAngleLabelDegrees = 60.0
  resistanceLabel : setup.figure.resistanceLabelOhms = 10.0
  radiusCalibration :
    lengthInMeters setup.shellRadius =
      setup.figure.radiusLabelCentimeters / 100
  frequencyCalibration :
    frequencyInHertz setup.rotationFrequency =
      setup.figure.rotationRateLabelHertz
  magneticFieldCalibration :
    magneticFluxDensityInTeslas setup.magneticFluxDensityMagnitude =
      setup.figure.magneticFieldLabelTeslas
  resistanceCalibration :
    resistanceInOhms setup.resistorResistance =
      setup.figure.resistanceLabelOhms
  topContactAtPole : setup.contactPolarAngleRadians .top = 0
  obliqueContactAngleCalibration :
    setup.contactPolarAngleRadians .oblique =
      radiansFromDegrees setup.figure.obliqueAngleLabelDegrees

/-- Positivity conditions selecting the nondegenerate physical setup. -/
structure HasPhysicalRotatingSphereParameters
    (setup : RotatingSphereCircuitSetup) : Prop where
  radiusPositive : 0 < lengthInMeters setup.shellRadius
  rotationFrequencyPositive : 0 < frequencyInHertz setup.rotationFrequency
  fieldMagnitudePositive :
    0 < magneticFluxDensityInTeslas setup.magneticFluxDensityMagnitude
  resistancePositive : 0 < resistanceInOhms setup.resistorResistance

/-- Conversion from rotation frequency to angular speed: `ω = 2πf`. -/
structure SatisfiesRotationFrequencyLaw
    (setup : RotatingSphereCircuitSetup) : Prop where
  angularSpeedLaw :
    angularSpeedInRadiansPerSecond setup.angularSpeed =
      2 * Real.pi * frequencyInHertz setup.rotationFrequency

/-!
For an axially magnetized conducting sphere rotating about that axis, the
motional-emf magnitude between polar angles `θ₁` and `θ₂` is
`(1/2) B ω r² |sin² θ₂ - sin² θ₁|`.  This relates independent observables and
does not state the requested current or its numerical value.
-/
structure SatisfiesRotatingSphereMotionalEmfLaw
    (setup : RotatingSphereCircuitSetup) : Prop where
  motionalEmfLaw :
    electromotiveForceInVolts setup.motionalEmfMagnitude =
      (1 / 2 : ℝ) *
        magneticFluxDensityInTeslas setup.magneticFluxDensityMagnitude *
        angularSpeedInRadiansPerSecond setup.angularSpeed *
        lengthInMeters setup.shellRadius ^ 2 *
        |Real.sin (setup.contactPolarAngleRadians .oblique) ^ 2 -
          Real.sin (setup.contactPolarAngleRadians .top) ^ 2|

/-- Ohm's law for the current magnitude in the closed external circuit. -/
structure SatisfiesExternalCircuitOhmsLaw
    (setup : RotatingSphereCircuitSetup) : Prop where
  ohmsLaw :
    electromotiveForceInVolts setup.motionalEmfMagnitude =
      currentInAmperes setup.wireCurrentMagnitude *
        resistanceInOhms setup.resistorResistance

/-! ## Answer-choice interpretation and target -/

/-- The four current choices printed with the problem. -/
inductive CurrentAnswerChoice where
  | A
  | B
  | C
  | D
  deriving DecidableEq, Fintype, Repr

/-- Printed magnitude of each answer choice, in milliamperes. -/
def answerChoiceInMilliamperes : CurrentAnswerChoice → ℝ
  | .A => 0.473
  | .B => 4.73
  | .C => 47.3
  | .D => 0

/-- Coherent-SI current readout converted from amperes to milliamperes. -/
def currentInMilliamperes (current : ElectricCurrentMagnitude) : ℝ :=
  1000 * currentInAmperes current

/-!
A listed choice is uniquely closest to the physical current readout.  This
definition does not privilege any particular choice or prescribe the current.
-/
def IsUniqueClosestCurrentChoice
    (setup : RotatingSphereCircuitSetup)
    (choice : CurrentAnswerChoice) : Prop :=
  ∀ other, other ≠ choice →
    |currentInMilliamperes setup.wireCurrentMagnitude -
        answerChoiceInMilliamperes choice| <
      |currentInMilliamperes setup.wireCurrentMagnitude -
        answerChoiceInMilliamperes other|

/-!
The current magnitude is `3π/2000 A ≈ 4.71 mA`; among the printed values,
choice B (`4.73 mA`) is uniquely closest.

Blueprint label: `thm:physics:phyx_mini_0982:target`.
-/
theorem rotating_sphere_wire_current
    (setup : RotatingSphereCircuitSetup)
    (_scenario : MatchesConductingSphereScenario setup)
    (_figure : MatchesPrimaryRotatingSphereFigure setup)
    (_physical : HasPhysicalRotatingSphereParameters setup)
    (_rotationLaw : SatisfiesRotationFrequencyLaw setup)
    (_emfLaw : SatisfiesRotatingSphereMotionalEmfLaw setup)
    (_ohmsLaw : SatisfiesExternalCircuitOhmsLaw setup) :
    currentInAmperes setup.wireCurrentMagnitude =
        3 * Real.pi / 2000 ∧
      IsUniqueClosestCurrentChoice setup .B := by
  have hr : lengthInMeters setup.shellRadius = (1 / 10 : ℝ) := by
    rw [_figure.radiusCalibration, _figure.radiusLabel]
    norm_num
  have hf : frequencyInHertz setup.rotationFrequency = 2 := by
    rw [_figure.frequencyCalibration, _figure.frequencyLabel]
  have hB :
      magneticFluxDensityInTeslas setup.magneticFluxDensityMagnitude = 1 := by
    rw [_figure.magneticFieldCalibration, _figure.magneticFieldLabel]
    norm_num
  have hR : resistanceInOhms setup.resistorResistance = 10 := by
    rw [_figure.resistanceCalibration, _figure.resistanceLabel]
    norm_num
  have htop : setup.contactPolarAngleRadians .top = 0 :=
    _figure.topContactAtPole
  have hoblique :
      setup.contactPolarAngleRadians .oblique = Real.pi / 3 := by
    rw [_figure.obliqueContactAngleCalibration, _figure.obliqueAngleLabel]
    dsimp [radiansFromDegrees]
    norm_num
    ring_nf
  have homega :
      angularSpeedInRadiansPerSecond setup.angularSpeed = 4 * Real.pi := by
    rw [_rotationLaw.angularSpeedLaw, hf]
    ring
  have hemf :
      electromotiveForceInVolts setup.motionalEmfMagnitude =
        3 * Real.pi / 200 := by
    rw [_emfLaw.motionalEmfLaw, hB, homega, hr, hoblique, htop,
      Real.sq_sin_pi_div_three]
    norm_num
    ring
  have hcurrent :
      currentInAmperes setup.wireCurrentMagnitude =
        3 * Real.pi / 2000 := by
    have hohms := _ohmsLaw.ohmsLaw
    rw [hemf, hR] at hohms
    linarith [hohms]
  refine ⟨hcurrent, ?_⟩
  intro other hother
  fin_cases other
  · simp only [currentInMilliamperes, hcurrent, answerChoiceInMilliamperes]
    by_cases hBside : 0 ≤ 1000 * (3 * Real.pi / 2000) - 4.73
    · rw [abs_of_nonneg hBside,
        abs_of_nonneg (by linarith [Real.two_le_pi])]
      linarith
    · rw [abs_of_nonpos (le_of_not_ge hBside),
        abs_of_nonneg (by linarith [Real.two_le_pi])]
      linarith [Real.two_le_pi]
  · exact (hother rfl).elim
  · simp only [currentInMilliamperes, hcurrent, answerChoiceInMilliamperes]
    by_cases hBside : 0 ≤ 1000 * (3 * Real.pi / 2000) - 4.73
    · rw [abs_of_nonneg hBside,
        abs_of_nonpos (by linarith [Real.pi_le_four])]
      linarith [Real.pi_le_four]
    · rw [abs_of_nonpos (le_of_not_ge hBside),
        abs_of_nonpos (by linarith [Real.pi_le_four])]
      norm_num
  · simp only [currentInMilliamperes, hcurrent, answerChoiceInMilliamperes]
    by_cases hBside : 0 ≤ 1000 * (3 * Real.pi / 2000) - 4.73
    · rw [abs_of_nonneg hBside,
        abs_of_nonneg (by linarith [Real.pi_pos])]
      norm_num
    · rw [abs_of_nonpos (le_of_not_ge hBside),
        abs_of_nonneg (by linarith [Real.pi_pos])]
      linarith [Real.two_le_pi]

end PhyXMiniProblems.ProblemPhyXMini0982
