import Mathlib
import Physlib.Electromagnetism.Basic
import Physlib.Units.WithDim.Basic

/- USER: The assigned Lean file did not exist when this autoformalization task began. -/

noncomputable section

namespace PhyXMiniProblems.ProblemPhyXMini0916

open Dimension

/-!
# Magnetic field of a short current-carrying wire segment at `P₂`

A copper wire carries a steady `125 A` current to the left.  The primary
figure marks a `1.0 cm` segment on the `x`-axis and two observation points,
`P₁` and `P₂`, each `1.2 m` from the segment.  The ray from the segment to
`P₂` is in the `xy`-plane and makes a `30°` angle above the negative
`x`-axis.  Thus the right-hand rule makes the field at `P₂` point in the
negative `z` direction.

Physical lengths, current, and vacuum permeability are represented by
unit-independent Physlib `Dimensionful` quantities.  The magnetic field
itself uses Physlib's spacetime-dependent vector-field type.  Real numbers
occur only as explicitly named SI or displayed-label readouts, angles, and
vector components.

Assumption/target split:

* governing laws: time independence for a steady current, the short-segment
  Biot--Savart vector law, and the standard vacuum-permeability calibration;
* previous-part results: none;
* figure/data readouts: copper wire, electroplating-tank destination, steady
  `125 A` leftward current, `1.0 cm` segment, both `1.2 m` point labels, the
  `x`, `y`, and `z` axes, `P₁`, `P₂`, the obstacle/bend, the right-angle
  marker at `P₁`, and the `30°` ray to `P₂` in the `xy`-plane;
* current target conclusions: the exact negative `z` component generated by
  the short-segment model, its rounding to `-4.3 * 10⁻⁸ T`, and unique
  selection of answer choice C.

No target field value or answer choice is stored in a setup, figure, or law
premise.
-/

/-! ## Dimensionful physical quantities and SI readouts -/

/-- Electric current has dimension charge per unit time. -/
def electricCurrentDimension : Dimension := C𝓭 * T𝓭⁻¹

/-- Magnetic permeability has dimension `M L C⁻²`. -/
def magneticPermeabilityDimension : Dimension :=
  M𝓭 * L𝓭 * C𝓭⁻¹ * C𝓭⁻¹

/-- A nonnegative, unit-independent physical length. -/
abbrev LengthQuantity : Type :=
  Dimensionful (WithDim L𝓭 NNReal)

/-- A nonnegative, unit-independent electric-current magnitude. -/
abbrev ElectricCurrentQuantity : Type :=
  Dimensionful (WithDim electricCurrentDimension NNReal)

/-- A nonnegative, unit-independent magnetic permeability. -/
abbrev MagneticPermeabilityQuantity : Type :=
  Dimensionful (WithDim magneticPermeabilityDimension NNReal)

/-- SI metre readout of a physical length. -/
def lengthInMeters (length : LengthQuantity) : ℝ :=
  ((length UnitChoices.SI).val : ℝ)

/-- Centimetre readout used by the printed segment-length label. -/
def lengthInCentimeters (length : LengthQuantity) : ℝ :=
  100 * lengthInMeters length

/-- SI ampere readout of a physical electric-current magnitude. -/
def currentInAmperes (current : ElectricCurrentQuantity) : ℝ :=
  ((current UnitChoices.SI).val : ℝ)

/-- SI readout of permeability in tesla-metres per ampere. -/
def permeabilityInTeslaMetersPerAmpere
    (permeability : MagneticPermeabilityQuantity) : ℝ :=
  ((permeability UnitChoices.SI).val : ℝ)

/-! ## Coordinate, apparatus, and primary-figure vocabulary -/

/-- A three-dimensional spatial vector. -/
abbrev SpatialVector : Type := EuclideanSpace ℝ (Fin 3)

/-!
Mathlib's coordinate cross product transported to the Euclidean-space type
used by Physlib magnetic fields.
-/
def spatialCrossProduct (a b : SpatialVector) : SpatialVector :=
  (WithLp.equiv 2 (Fin 3 → ℝ)).symm
    (crossProduct (WithLp.equiv 2 (Fin 3 → ℝ) a)
      (WithLp.equiv 2 (Fin 3 → ℝ) b))

/-- The three coordinate axes explicitly labelled in the image. -/
inductive CoordinateAxis where
  | x
  | y
  | z
  deriving DecidableEq, Fintype, Repr

/-- Unit vector associated with a displayed coordinate axis. -/
def axisDirection : CoordinateAxis → SpatialVector
  | .x => EuclideanSpace.single (0 : Fin 3) 1
  | .y => EuclideanSpace.single (1 : Fin 3) 1
  | .z => EuclideanSpace.single (2 : Fin 3) 1

/-- The two observation points named in the primary figure. -/
inductive ObservationPoint where
  | P1
  | P2
  deriving DecidableEq, Fintype, Repr

/-- The two pictured locations of the repeated current arrow. -/
inductive CurrentArrowSite where
  | leftOfSegment
  | rightOfSegment
  deriving DecidableEq, Fintype, Repr

/-- Direction of the current arrows along the horizontal wire. -/
inductive HorizontalDirection where
  | leftward
  | rightward
  deriving DecidableEq, Repr

/-- Material of the current-carrying wire. -/
inductive WireMaterial where
  | copper
  | other
  deriving DecidableEq, Repr

/-- Destination stated for the current in the problem prose. -/
inductive CurrentDestination where
  | electroplatingTank
  | other
  deriving DecidableEq, Repr

/-- Whether the current is time-independent. -/
inductive CurrentRegime where
  | steady
  | timeDependent
  deriving DecidableEq, Repr

/-!
Literal labels and qualitative objects in the supplied image `916.png`.
The displayed scalar labels are kept separate from the physical quantities
that they calibrate.
-/
structure ShortWireFigure where
  axisShown : CoordinateAxis → Bool
  pointMarkerShown : ObservationPoint → Bool
  currentArrowShown : CurrentArrowSite → Bool
  currentArrowDirection : CurrentArrowSite → HorizontalDirection
  displayedCurrentInAmperes : CurrentArrowSite → ℝ
  wireDrawnAlongAxis : CoordinateAxis
  segmentMarkerShown : Bool
  displayedSegmentLengthInCentimeters : ℝ
  distanceLabelShown : ObservationPoint → Bool
  displayedDistanceInMeters : ObservationPoint → ℝ
  rightAngleMarkerAtP1Shown : Bool
  angleMarkerAtP2Shown : Bool
  displayedP2AngleInDegrees : ℝ
  bendAndObstacleShown : Bool

/-!
Independent physical quantities and observables for the wire segment.  The
field is not defined from an answer choice or from the requested numerical
component.
-/
structure ShortWireMagneticFieldSetup where
  unitSystem : UnitChoices
  wireMaterial : WireMaterial
  currentDestination : CurrentDestination
  currentRegime : CurrentRegime
  currentMagnitude : ElectricCurrentQuantity
  segmentLength : LengthQuantity
  distanceToPoint : ObservationPoint → LengthQuantity
  p2AngleToSegmentRadians : ℝ
  segmentMidpoint : Space 3
  pointPosition : ObservationPoint → Space 3
  radialUnitDirection : ObservationPoint → SpatialVector
  currentUnitDirection : SpatialVector
  electromagneticSystem : Electromagnetism.EMSystem
  vacuumPermeability : MagneticPermeabilityQuantity
  magneticFieldDueToSegment : Electromagnetism.MagneticField 3
  observationTime : Time
  figure : ShortWireFigure

/-- The Physlib magnetic-field vector at `P₂`, read in coherent SI units. -/
def magneticFieldVectorAtP2InTeslas
    (setup : ShortWireMagneticFieldSetup) : SpatialVector :=
  setup.magneticFieldDueToSegment setup.observationTime
    (setup.pointPosition .P2)

/-- Signed `z` component of the field at `P₂`, in teslas. -/
def magneticFieldZComponentAtP2InTeslas
    (setup : ShortWireMagneticFieldSetup) : ℝ :=
  magneticFieldVectorAtP2InTeslas setup (2 : Fin 3)

/-! ## Problem data and primary-image geometry -/

/-- Prose data and the physical quantities calibrated by its numerical values. -/
structure MatchesShortWireProblemData
    (setup : ShortWireMagneticFieldSetup) : Prop where
  usesSIUnits : setup.unitSystem = UnitChoices.SI
  wireIsCopper : setup.wireMaterial = .copper
  currentGoesToElectroplatingTank :
    setup.currentDestination = .electroplatingTank
  currentIsSteady : setup.currentRegime = .steady
  currentMagnitudeIs125Amperes :
    currentInAmperes setup.currentMagnitude = 125
  segmentLengthIsOneCentimeter :
    lengthInCentimeters setup.segmentLength = 1
  segmentLengthIsOneHundredthMeter :
    lengthInMeters setup.segmentLength = 1 / 100
  pointP1DistanceIsOnePointTwoMeters :
    lengthInMeters (setup.distanceToPoint .P1) = 6 / 5
  pointP2DistanceIsOnePointTwoMeters :
    lengthInMeters (setup.distanceToPoint .P2) = 6 / 5
  pointP2AngleIsThirtyDegrees :
    setup.p2AngleToSegmentRadians = Real.pi / 6

/-!
Primary-image transcription and the corresponding metre-coordinate geometry.
The ray to `P₂` is `30°` above the negative `x` direction.  Combined with
the leftward current this records the sign information needed by the
right-hand rule, but it does not assert any field value.
-/
structure MatchesPrimaryShortWireFigure
    (setup : ShortWireMagneticFieldSetup) : Prop where
  everyAxisShown : ∀ axis, setup.figure.axisShown axis = true
  bothPointMarkersShown : ∀ point, setup.figure.pointMarkerShown point = true
  bothCurrentArrowsShown : ∀ site, setup.figure.currentArrowShown site = true
  bothCurrentArrowsPointLeft : ∀ site,
    setup.figure.currentArrowDirection site = .leftward
  bothCurrentLabelsRead125 : ∀ site,
    setup.figure.displayedCurrentInAmperes site = 125
  currentLabelsCalibratePhysicalCurrent : ∀ site,
    setup.figure.displayedCurrentInAmperes site =
      currentInAmperes setup.currentMagnitude
  wireLiesOnXAxis : setup.figure.wireDrawnAlongAxis = .x
  markedSegmentIsShown : setup.figure.segmentMarkerShown = true
  segmentLabelReadsOneCentimeter :
    setup.figure.displayedSegmentLengthInCentimeters = 1
  segmentLabelCalibratesPhysicalLength :
    setup.figure.displayedSegmentLengthInCentimeters =
      lengthInCentimeters setup.segmentLength
  bothDistanceLabelsShown : ∀ point,
    setup.figure.distanceLabelShown point = true
  bothDistanceLabelsReadOnePointTwo : ∀ point,
    setup.figure.displayedDistanceInMeters point = 6 / 5
  distanceLabelsCalibratePhysicalDistances : ∀ point,
    setup.figure.displayedDistanceInMeters point =
      lengthInMeters (setup.distanceToPoint point)
  rightAngleMarkerAtP1Shown : setup.figure.rightAngleMarkerAtP1Shown = true
  angleMarkerAtP2Shown : setup.figure.angleMarkerAtP2Shown = true
  angleLabelReadsThirtyDegrees : setup.figure.displayedP2AngleInDegrees = 30
  bendAndObstacleShown : setup.figure.bendAndObstacleShown = true
  currentDirectionIsNegativeX :
    setup.currentUnitDirection = -axisDirection .x
  p1DirectionIsPositiveY :
    setup.radialUnitDirection .P1 = axisDirection .y
  p2DirectionIsInXYPlaneAtDisplayedAngle :
    setup.radialUnitDirection .P2 =
      (-Real.cos setup.p2AngleToSegmentRadians) • axisDirection .x +
        Real.sin setup.p2AngleToSegmentRadians • axisDirection .y
  p1PositionFromSegmentCenter :
    setup.pointPosition .P1 =
      (lengthInMeters (setup.distanceToPoint .P1) •
          setup.radialUnitDirection .P1) +ᵥ setup.segmentMidpoint
  p2PositionFromSegmentCenter :
    setup.pointPosition .P2 =
      (lengthInMeters (setup.distanceToPoint .P2) •
          setup.radialUnitDirection .P2) +ᵥ setup.segmentMidpoint

/-- Positivity and unit-vector assumptions selecting the physical branch. -/
structure HasPhysicalShortWireParameters
    (setup : ShortWireMagneticFieldSetup) : Prop where
  currentPositive : 0 < currentInAmperes setup.currentMagnitude
  segmentLengthPositive : 0 < lengthInMeters setup.segmentLength
  pointDistancesPositive : ∀ point,
    0 < lengthInMeters (setup.distanceToPoint point)
  permeabilityPositive :
    0 < permeabilityInTeslaMetersPerAmpere setup.vacuumPermeability
  currentDirectionIsUnit : ‖setup.currentUnitDirection‖ = 1
  radialDirectionsAreUnit : ∀ point,
    ‖setup.radialUnitDirection point‖ = 1
  p2AngleIsAcute :
    0 < setup.p2AngleToSegmentRadians ∧
      setup.p2AngleToSegmentRadians < Real.pi / 2

/-!
The dimensionful permeability agrees with the Physlib electromagnetic system
and has the standard vacuum SI value `4π * 10⁻⁷ T m/A`.  This is calibration
data, not the requested magnetic field.
-/
structure UsesStandardVacuumPermeability
    (setup : ShortWireMagneticFieldSetup) : Prop where
  agreesWithElectromagneticSystem :
    permeabilityInTeslaMetersPerAmpere setup.vacuumPermeability =
      setup.electromagneticSystem.μ₀
  standardSIReadout :
    permeabilityInTeslaMetersPerAmpere setup.vacuumPermeability =
      4 * Real.pi / 10 ^ 7

/-! ## Governing magnetic laws -/

/-- A steady current produces a time-independent field in this model. -/
structure SatisfiesSteadyCurrentFieldModel
    (setup : ShortWireMagneticFieldSetup) : Prop where
  fieldTimeIndependent : ∀ time position,
    setup.magneticFieldDueToSegment time position =
      setup.magneticFieldDueToSegment setup.observationTime position

/-!
Short-current-element form of the Biot--Savart law at `P₂`:

`B = μ₀ I Δℓ /(4πr²) (î_current × r̂)`.

The cross product retains both the `sin θ` factor and the right-hand-rule
sign.  This premise is a general governing relation in the stored physical
quantities; it contains neither the requested numerical field nor an answer
choice.
-/
structure SatisfiesShortSegmentBiotSavartLaw
    (setup : ShortWireMagneticFieldSetup) : Prop where
  fieldAtP2 :
    magneticFieldVectorAtP2InTeslas setup =
      (permeabilityInTeslaMetersPerAmpere setup.vacuumPermeability *
          currentInAmperes setup.currentMagnitude *
          lengthInMeters setup.segmentLength /
          (4 * Real.pi *
            lengthInMeters (setup.distanceToPoint .P2) ^ 2)) •
        spatialCrossProduct setup.currentUnitDirection
          (setup.radialUnitDirection .P2)

/-! ## Derived field and displayed-answer target -/

/-!
The short-segment Biot--Savart calculation gives the exact model value
`-(1 / 23040000) T` in the `z` direction.  Its decimal magnitude is about
`4.3403 * 10⁻⁸ T`.
-/
lemma magneticFieldVectorAtP2_exact
    (setup : ShortWireMagneticFieldSetup)
    (hData : MatchesShortWireProblemData setup)
    (hFigure : MatchesPrimaryShortWireFigure setup)
    (hPhysical : HasPhysicalShortWireParameters setup)
    (hVacuum : UsesStandardVacuumPermeability setup)
    (hSteady : SatisfiesSteadyCurrentFieldModel setup)
    (hBiotSavart : SatisfiesShortSegmentBiotSavartLaw setup) :
    magneticFieldVectorAtP2InTeslas setup =
      (-(1 / 23040000 : ℝ)) • axisDirection .z := by
  rw [hBiotSavart.fieldAtP2, hVacuum.standardSIReadout,
    hData.currentMagnitudeIs125Amperes,
    hData.segmentLengthIsOneHundredthMeter,
    hData.pointP2DistanceIsOnePointTwoMeters,
    hFigure.currentDirectionIsNegativeX,
    hFigure.p2DirectionIsInXYPlaneAtDisplayedAngle,
    hData.pointP2AngleIsThirtyDegrees]
  have hCross :
      spatialCrossProduct (-axisDirection .x)
          ((-Real.cos (Real.pi / 6)) • axisDirection .x +
            Real.sin (Real.pi / 6) • axisDirection .y) =
        (-(1 / 2 : ℝ)) • axisDirection .z := by
    ext i
    fin_cases i <;>
      norm_num [spatialCrossProduct, axisDirection, crossProduct,
        Real.sin_pi_div_six, Pi.single_apply]
    all_goals simp
  rw [hCross, smul_smul]
  congr 1
  field_simp [Real.pi_ne_zero]
  <;> ring

/-- Labels of the four signed magnetic-field answers in the question. -/
inductive AnswerChoice where
  | A
  | B
  | C
  | D
  deriving DecidableEq, Fintype, Repr

/-- Signed magnetic-field component in teslas displayed beside each choice. -/
def displayedMagneticFieldInTeslas : AnswerChoice → ℝ
  | .A => 43 / 10 ^ 9
  | .B => -(215 / 10 ^ 10)
  | .C => -(43 / 10 ^ 9)
  | .D => -(47 / 10 ^ 9)

/-!
Rounding to the nearest `0.1 * 10⁻⁸ T`, the precision used by choices A, C,
and D.
-/
def RoundsToNearestTenthTimesTenPowNegEight
    (actual displayed : ℝ) : Prop :=
  |actual - displayed| < 1 / (2 * 10 ^ 9)

/-- A choice is strictly closer than every distinct displayed alternative. -/
def IsUniqueClosestDisplayedAnswer
    (actual : ℝ) (choice : AnswerChoice) : Prop :=
  ∀ otherChoice, otherChoice ≠ choice →
    |actual - displayedMagneticFieldInTeslas choice| <
      |actual - displayedMagneticFieldInTeslas otherChoice|

/-!
Blueprint declaration `thm:physics:phyx_mini_0916:target`.

At `P₂`, the leftward current and the pictured `30°` geometry give a negative
`z` component.  The exact short-segment value rounds to
`-4.3 * 10⁻⁸ T`, uniquely selecting answer C.
-/
theorem magneticFieldDueToSegmentAtP2
    (setup : ShortWireMagneticFieldSetup)
    (hData : MatchesShortWireProblemData setup)
    (hFigure : MatchesPrimaryShortWireFigure setup)
    (hPhysical : HasPhysicalShortWireParameters setup)
    (hVacuum : UsesStandardVacuumPermeability setup)
    (hSteady : SatisfiesSteadyCurrentFieldModel setup)
    (hBiotSavart : SatisfiesShortSegmentBiotSavartLaw setup) :
    magneticFieldZComponentAtP2InTeslas setup =
        -(1 / 23040000 : ℝ) ∧
      RoundsToNearestTenthTimesTenPowNegEight
        (magneticFieldZComponentAtP2InTeslas setup)
        (displayedMagneticFieldInTeslas .C) ∧
      IsUniqueClosestDisplayedAnswer
        (magneticFieldZComponentAtP2InTeslas setup) .C := by
  have hComponent :
      magneticFieldZComponentAtP2InTeslas setup =
        -(1 / 23040000 : ℝ) := by
    unfold magneticFieldZComponentAtP2InTeslas
    rw [magneticFieldVectorAtP2_exact setup hData hFigure hPhysical
      hVacuum hSteady hBiotSavart]
    norm_num [axisDirection, Pi.single_apply]
  refine ⟨hComponent, ?_, ?_⟩
  · rw [hComponent]
    norm_num [RoundsToNearestTenthTimesTenPowNegEight,
      displayedMagneticFieldInTeslas, abs_of_nonneg, abs_of_nonpos]
  · rw [hComponent]
    intro otherChoice hOtherChoice
    fin_cases otherChoice <;>
      norm_num [displayedMagneticFieldInTeslas, abs_of_nonneg,
        abs_of_nonpos] at *

end PhyXMiniProblems.ProblemPhyXMini0916
