import M5OrderCount
#print axioms M5.AnchoredCount.anchored_single_block_count
#print axioms M5.PolynomialIndicator.residual_factors_regular
#print axioms M5.PolynomialIndicator.exact_signature_indicator
