from pathlib import Path
import json,hashlib,shutil
repo=Path('/home/jing/science-mango-quantum-harness-publish-20260914');src=repo/'pipelines/quantum_formalize/examples/m7/domain';b=repo/'pipelines/quantum_formalize/examples/m7/signature_ideal';p=Path('/home/jing/m7-lean-signature-ideal-formalization');p.mkdir(exist_ok=True);(b/'lean').mkdir(parents=True,exist_ok=True);m=json.loads((src/'MANIFEST.json').read_text());verified={}
for name in ['M6Cyclic','M6CyclicAccepted']:
 f=src/'lean'/(name+'.lean');h=hashlib.sha256(f.read_bytes()).hexdigest();assert h==m['lean/'+f.name];verified[f.name]=h;shutil.copy2(f,p/f.name);shutil.copy2(f,b/'lean'/f.name)
source='''import M6CyclicAccepted

namespace M7.SignatureIdeal
noncomputable def principal (N : ℕ) (F : M6.Cyclic.BinaryPolynomial) : Ideal (M6.Cyclic.CycleRing N) :=
  Ideal.span ({M6.Cyclic.image N F} : Set (M6.Cyclic.CycleRing N))
noncomputable def pairIdeal (N : ℕ) (a b : M6.Cyclic.BinaryPolynomial) : Ideal (M6.Cyclic.CycleRing N) :=
  Ideal.span ({M6.Cyclic.image N a, M6.Cyclic.image N b} : Set (M6.Cyclic.CycleRing N))
end M7.SignatureIdeal
'''
(p/'M7SignatureIdeal.lean').write_text(source);(b/'lean/M7SignatureIdeal.lean').write_text(source);base=Path('/home/jing/m7-lean-canonical-block-formalization')
for n in ['lake-manifest.json','lean-toolchain']:shutil.copy2(base/n,p/n);shutil.copy2(base/n,b/n)
s=(base/'lakefile.toml').read_text().replace('M7CanonicalBlock','M7SignatureIdeal')+'\n[[lean_lib]]\nname = "M6Cyclic"\n\n[[lean_lib]]\nname = "M6CyclicAccepted"\n';(p/'lakefile.toml').write_text(s);shutil.copy2(p/'lakefile.toml',b/'lakefile.toml');(p/'.lake').mkdir(exist_ok=True)
if not(p/'.lake/packages').exists():(p/'.lake/packages').symlink_to('/home/jing/lean-1st-proof/.lake/packages',target_is_directory=True)
f='∀ (N : ℕ) [NeZero N], ';pr='M7.SignatureIdeal.principal';M='M6.Cyclic.modulus N'
items=[
('modulus_zero',[],f+'M6.Cyclic.image N ('+M+') = 0'),
('full_signature_ideal',['modulus_zero'],f+'∀ a b : M6.Cyclic.BinaryPolynomial, M7.SignatureIdeal.pairIdeal N a b = '+pr+' N (M6.Cyclic.signature a b ('+M+'))'),
('quotient_membership',[],f+'∀ F p : M6.Cyclic.BinaryPolynomial, F ∣ '+M+' → (M6.Cyclic.image N p ∈ '+pr+' N F ↔ F ∣ p)'),
('monic_injective',['quotient_membership'],f+'∀ F E : M6.Cyclic.BinaryPolynomial, F.Monic → E.Monic → F ∣ '+M+' → E ∣ '+M+' → ('+pr+' N F = '+pr+' N E ↔ F = E)'),
('principal_gcd',['full_signature_ideal'],f+'∀ F : M6.Cyclic.BinaryPolynomial, '+pr+' N F = '+pr+' N (EuclideanDomain.gcd F ('+M+'))')]
g={'title':'M7 full literal polynomial signature via actual cyclic quotient ideals','nodes':[{'id':i,'dependencies':deps,'spec':{'name':'M7.SignatureIdeal.'+i,'statement':s,'imports':['M7SignatureIdeal'],'context':'','queries':['algebra'],'guidance':'Use accepted M6.Cyclic.signature_bezout and signature_divides. Ideal.span_le and singleton membership/divisibility prove full_signature_ideal. For quotient_membership, a scalar witness in AdjoinRoot lifts to mk q by mk_surjective; mk equality implies modulus divides p-F*q, then F divides p. Conversely map a divisibility witness. monic_injective follows mutual divisibility and monicity. No squarefree/odd-N/irreducible quotient assumption; retain full polynomial multiplicities. This is ideal equality, not root-set equality. Return tactic lines only.\n'+source}}for i,deps,s in items]};(b/'graph.json').write_text(json.dumps(g,indent=2)+'\n');(p/'Preflight.lean').write_text('import M7SignatureIdeal\n'+''.join('def target_'+str(j)+' : Prop := '+s+'\n'for j,(_,_,s)in enumerate(items)))
(b/'IMPORT_PROVENANCE.json').write_text(json.dumps({'source':'../domain','verified_against_canonical_manifest':True,'byte_identical_imports':verified},indent=2)+'\n');(b/'SCOPE.md').write_text('# Full literal signature via cyclic quotient ideals\n\nFive exact targets connect the existing full polynomial gcd to the ideal generated by the actual quotient images, prove quotient ideal membership detects divisibility for divisors of the modulus, and recover monic full divisors uniquely from their ideals. This preserves multiplicities. Unit automorphism integration and degree preservation remain downstream; no full M7 acceptance is claimed.\n');print('prepared5 exact signature-ideal targets with verified M6 imports')
