from pathlib import Path
import json
H=Path(__file__).resolve().parent
p='M5.ConditionalResidueCount.'
params='∀ (T w : ℕ) (F : M5.BinaryPolynomial) (p q : List (Fin T)), '
assume='0 < T → 0 < w → F.Monic → F ∣ M5.cyclicModulus T → '
rows=[
('prefix_gcd_divisibility',[],'∀ (T d : ℕ) (p q : List (Fin T)), (d ∣ '+p+'selectedGcd T p q ↔ d ∣ T ∧ (∀ r ∈ p, d ∣ r.val) ∧ (∀ r ∈ q, d ∣ r.val))',
 'Prove by list induction that d divides prefixGcd exactly when it divides every selected residue, then unfold selectedGcd and gcd divisibility. The empty list uses gcd fold seed zero. Repeated residues are retained and allowed; no injectivity or positivity assumption is needed.'),
('selected_R_pair_count',[],'∀ (P ZA ZB : M5.BinaryPolynomial) (T d k l : ℕ), P.Monic → 0 < T → d ∣ T → '+p+'RSelected P ZA T d k * '+p+'RSelected P ZB T d l = ∑ a : Fin k → Fin T, ∑ b : Fin l → Fin T, '+p+'divisibilityIndicator P ZA ZB d a b',
 'Unfold monicity wrappers and rewrite each factor using accepted M5.TupleCompletion.restricted_completion_R. Unfold restrictedCount and divisibilityIndicator, rewrite card_eq_sum_ones, Nat.cast_sum, sum_filter and distribute sum_mul/mul_sum. Finish by pointwise cases on the four concrete predicates using narrow simp. Avoid change across different inferred Decidable instances. Different lengths and selected polynomials are essential; retain zero completion lengths.'),
('pair_indicator_exact',['prefix_gcd_divisibility'],params+'∀ (a : Fin ('+p+'remaining w p) → Fin T) (b : Fin ('+p+'remaining w q) → Fin T), 0 < T → F.Monic → F ∣ M5.cyclicModulus T → '+p+'pairIndicator w F p q a b = '+p+'feasibleIndicator w F p q a b',
 'selectedGcd is positive because it divides positive T (use prefix_gcd_divisibility at d=selectedGcd). Apply accepted stage9 integer connected_indicator at selectedGcd with completion-coordinate images, rewriting gcd_image and zero anchor. Combine accepted stage23 exact_signature_indicator for the completed polynomials at T. Unfold feasible/feasibleIndicator; case-split the two conditions. Do not compute integer gcd from cancelled polynomial support.'),
('arithmetic_indicator_expansion',['prefix_gcd_divisibility','selected_R_pair_count'],params+assume+p+'rawConditionalA T w F p q = ∑ a : Fin ('+p+'remaining w p) → Fin T, ∑ b : Fin ('+p+'remaining w q) → Fin T, '+p+'pairIndicator w F p q a b',
 'For each d|selectedGcd, prefix_gcd_divisibility gives d|T. Residual factors are monic by accepted stage23 residual_factors_regular, so F times each subset product is monic. Rewrite selected_R_pair_count under d,S sums with membership-aware simp (disch := assumption) only, unfold indicators, and distribute finite sums. Use explicit one-time sum_comm rw/conv permutations (never simp[sum_comm]); align d/S order before sum_congr. Finish using four concrete predicate cases and narrow simp, not broad simp_all over count hypotheses. This is the stage31 expansion route with separate selected polynomials and completion lengths.'),
('exact_conditionalA',['pair_indicator_exact','arithmetic_indicator_expansion'],params+assume+p+'conditionalAAt T w F p q = ('+p+'validCompletions T w F p q).card',
 'Split the fits guard. If false both the arithmetic wrapper and semantic completion set are zero/empty. If true rewrite arithmetic_indicator_expansion and pair_indicator_exact; unfold feasibleIndicator and identify the double finite sum with the filtered product-universe cardinality. Handle casts by card_eq_sum_ones and sum_filter, avoiding definitional-equality assumptions between Decidable instances. No prefix-length assumption may be added to the target.'),
('period_conditionalA_exact',[],'∀ (w : ℕ) (F : M5.BinaryPolynomial) (p q : List (Fin (M5.signaturePeriod F))), 0 < w → F.Monic → F.coeff 0 = 1 → '+p+'conditionalA w F p q = ('+p+'validCompletions (M5.signaturePeriod F) w F p q).card ∧ 0 ≤ '+p+'conditionalA w F p q ∧ (0 < '+p+'conditionalA w F p q ↔ '+p+'fits w p q ∧ ∃ a : Fin ('+p+'remaining w p) → Fin (M5.signaturePeriod F), ∃ b : Fin ('+p+'remaining w q) → Fin (M5.signaturePeriod F), '+p+'feasible w F p q a b)',
 'Accepted period_law gives positive T=signaturePeriodF and F|M_T. Apply exact_conditionalA, then natural-cardinality nonnegativity and card_pos/nonempty. Unpack validCompletions and its fits guard to get exact completion existence. Overfull prefixes yield zero; no extra guard premise is allowed. F=1 and zero-dimensional quotients are included.')]
rows[-1]=(rows[-1][0],['exact_conditionalA'],rows[-1][2],rows[-1][3])
nodes=[]
for id,deps,statement,guidance in rows:
 nodes.append({'id':id,'dependencies':deps,'spec':{'name':p+id,'statement':statement,'imports':['M5ConditionalResidueCount'],'context':'','queries':['finite sum filter cardinality product','list gcd fold divisibility finite sum commutation'],'guidance':guidance+' Return tactic lines only without leading by; preserve exact target.'},'metadata':{'source_section':'§4 conditional arithmetic recovery','fallback_queries':['addition commutativity']}})
g={'title':'M5 stage42: exact conditional residue count for selected prefixes','source':'research/quantum_m5/research_checkpoints/period_residue_arithmetic_law_reviewed/PROOF.md','source_sha256':'a7c0e2ae5f555864340f4b3e6d6674e5b2e74abf382ca5de4d3e5d68da6951a3','scope':'Actual guarded conditional-A divisor/factor arithmetic for two selected residue lists; exact count and positive completion criterion. Recovery algorithm connection remains subsequent, with no squarefree reindex gate.','nodes':nodes}
(H/'graph.json').write_text(json.dumps(g,indent=2)+'\n')
s='import M5ConditionalResidueCount\n\n'
for id,_,statement,_ in rows:s+='noncomputable def M5.Stage42Target.'+id+' : Prop :=\n  '+statement+'\n\n#check M5.Stage42Target.'+id+'\n\n'
for root in [H/'lean',Path('/home/jing/m5-lean-conditional-residue-count-formalization')]: (root/'GraphPreflight.lean').write_text(s)
