from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent;P=Path('/home/jing/m7-lean-query-certificate-formalization');S='M7.QueryCertificate.';G='M7.GlobalQuery.';D='M7.DefaultQuery.';I=G+'Index H N';A='∀ (H N : ℕ) [NeZero N]';Q=A+f' (q : {D}Query) (bases : {G}Family H N)';W=G+'winners q bases';AP=S+'allPresentations q bases';DM=f'{I} → Option ({I})';feas=lambda x:G+'feasible q bases '+x;better=lambda y,x:S+'strictBetter q bases '+y+' '+x
rows=[
('winner_pass_spec',[],Q+f' (W : Finset ({I})) (dominator : {DM}), ({S}winnerPass q bases W dominator = true ↔ (∀ x ∈ W, {feas("x")} ∧ ∀ y : {I}, {feas("y")} → ¬ {better("y","x")}) ∧ (∀ x : {I}, {feas("x")} → x ∉ W → ∃ y : {I}, dominator x = some y ∧ y ∈ W ∧ {better("y","x")}))','Unfold winnerPass and allOn. allOn is the actual finite Finset.toList.all loop: use List.all_eq_true, Finset.mem_toList, Bool.and_eq_true and decide_eq_true_eq. Split the omitted-index condition and dominator x option. The some branch verifies the supplied witness; none fails for an omitted feasible index. Preserve every explicit global comparison.'),
('winner_pass_sound',['winner_pass_spec'],Q+f' (W : Finset ({I})) (dominator : {DM}), {S}winnerPass q bases W dominator = true → W = {W}','Use winner_pass_spec and accepted GlobalQuery.winners_exact. Claimed winners are feasible and globally undominated, hence genuine winners. A genuine winner omitted from W would have a supplied strict dominator in W, which is feasible by the claimed-winner checks, contradicting global undominatedness. This also rules out omitting any tied winner.'),
('winner_pass_complete',['winner_pass_spec'],Q+f', ∃ dominator : {DM}, {S}winnerPass q bases ({W}) dominator = true','Use GlobalQuery.winners_exact for every true winner. For each omitted feasible index, accepted GlobalQuery.strict_dominator supplies a strict winning dominator. Choose that finite witness when the omission condition holds and return none otherwise; a dependent if with Classical.choose works. Apply winner_pass_spec. No complete-family or free comparator premise is allowed.'),
('presentation_pass_spec',[],A+f' (bases : {G}Family H N) (W P : Finset ({I})), ({S}presentationPass bases W P = true ↔ ∀ x : {I}, x ∈ P ↔ x ∈ W ∧ {S}isLeast bases x)','Unfold the two finite allOn loops. The P loop checks claimed membership in W and the actual leastAction equality; the W loop checks every minimal preimage is included in P. Convert the two implications to pointwise iff. Do not replace the checker definition by equality with a semantic expected set.'),
('invalid_rule',[],Q+f' (certificate : {S}Certificate H N), ({S}check q bases certificate = Except.error {D}QueryError.invalidSignature ↔ ¬ {D}valid N q) ∧ ({D}valid N q → {S}check q bases certificate = Except.ok ({S}winnerPass q bases certificate.winners certificate.dominator && {S}presentationPass bases certificate.winners certificate.presentations))','Unfold check and split the actual signature-validity conditional. Invalid signatures always return the explicit error; valid inputs return the finite Boolean checks. Distinguish false certificates from invalid-input errors.'),
('check_sound',['winner_pass_sound','presentation_pass_spec'],Q+f' (certificate : {S}Certificate H N), {S}check q bases certificate = Except.ok true → {D}valid N q ∧ certificate.winners = {W} ∧ certificate.presentations = {AP}','Unfold check and rule out invalid input; Boolean conjunction true gives both actual passes. Use winner_pass_sound, then presentation_pass_spec and Finset.ext. allPresentations is only the semantic target; its filter predicate is GlobalQuery.present = true winner membership and the actual leastAction equality. No expected-set equality is checked in the algorithm.'),
('check_complete',['winner_pass_complete','presentation_pass_spec'],Q+f', {D}valid N q → ∃ dominator : {DM}, {S}check q bases (⟨{W}, {AP}, dominator⟩ : {S}Certificate H N) = Except.ok true','Take the supplied dominator map from winner_pass_complete. The actual presentation set satisfies presentation_pass_spec by unfolding its filter and GlobalQuery.present/isLeast. Unfold check and use input validity and both Boolean passes. This is existence of a valid finite certificate, not trust in recorded numbers.'),
('check_exact',['check_sound','check_complete'],Q+f' (W P : Finset ({I})), ((∃ dominator : {DM}, {S}check q bases (⟨W, P, dominator⟩ : {S}Certificate H N) = Except.ok true) ↔ {D}valid N q ∧ W = {W} ∧ P = {AP})','Forward uses check_sound on the explicit certificate. Reverse substitutes the exact winner/presentation sets and invokes check_complete. The equality with all actual global winners retains every tie, and equality with GlobalPresent gives precisely the verified least-preimage reconstruction. Family coverage remains the independent final root obligation.')]
nodes=[{'id':i,'dependencies':ds,'spec':{'name':S+i,'statement':st,'imports':['M7QueryCertificate','M7GlobalQueryAccepted'],'context':'','queries':['List all_eq_true Finset mem_toList finite set verification'],'guidance':gd+' Return tactic proof lines without leading by; preserve the exact target and default limits.'},'metadata':{'source_section':'M7 original §8–10 finite query certificate replay and all optima','fallback_queries':['algebra']}}for i,ds,st,gd in rows];source=Path('/home/jing/quantum_code_discovery_proof/research_checkpoints/m7_compact_selector_final_20260915/PROOF.md');g={'title':'M7 actual finite query certificate checker','source':str(source),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'scope':'Recompute actual finite feasibility/global comparisons, supplied strict dominators for omissions, and factorized leastAction presentation conditions. Sound and complete for all actual GlobalWin/GlobalPresent ties; explicit invalid-signature error. No assumed complete family or runtime extraction/efficiency gate.','nodes':nodes};(H/'graph.json').write_text(json.dumps(g,ensure_ascii=False,indent=2)+'\n');s='import M7QueryCertificate\nimport M7GlobalQueryAccepted\n\n'
for i,ds,st,gd in rows:s+='noncomputable def M7.QueryCertificateTarget.'+i+' : Prop :=\n  '+st+'\n\n#check M7.QueryCertificateTarget.'+i+'\n\n'
for d in [P,H/'lean']:(d/'GraphPreflight.lean').write_text(s)
