from pathlib import Path
import json,os,sys,tempfile,subprocess,shutil,hashlib
from pipelines.quantum_formalize.dag_runner import load_graph
from pipelines.quantum_formalize.engine import fingerprint
from pipelines.quantum_humanize._runtime import runtime_pin
runtime_pin();repo=Path('/home/jing/science-mango-quantum-harness-publish-20260914');s=repo/'pipelines/quantum_formalize/examples/m6/transfer/trace';p=Path('/home/jing/m6-lean-transfer-trace-formalization');g,n=load_graph(s/'ready_graph.json');assert (p/'ReadyGraphPreflight.lean').read_text()=='import M6TransferTraceReady\n'+''.join('#check ('+x.spec['statement']+')\n' for x in n);assert 'Build completed successfully' in (p/'ReadyBuild.log').read_text();assert 'error:' not in (p/'ReadyGraphPreflight.log').read_text();fingerprint(p)
for f in ['ReadyBuild.log','ReadyGraphPreflight.log']:shutil.copy2(p/f,s/f)
(s/'READY_PREFLIGHT.json').write_text(json.dumps({'exact_target_types_checked':6,'runtime_loader_passed':True,'actual_foundation_import':'../experiment/AcceptedExperiment.lean','pending_imports':[],'seeded_proofs_still_require_frozen_acceptance':True,'graph_sha256':hashlib.sha256((s/'ready_graph.json').read_bytes()).hexdigest()},indent=2)+'\n')
control=Path(tempfile.mkdtemp(prefix='trace-replay-',dir=p/'.humanize-formal-runs'));(control/'graph.json').write_text(json.dumps(g,indent=2)+'\n');home=control/'humanize-home';home.mkdir();config={'project':str(p),'graph':str(control/'graph.json'),'output':str(control/'experiment'),'result_path':str(control/'result.json'),'concurrency':16,'rounds':5,'compile_timeout':180,'turn_timeout':600,'seed_proofs':json.loads((s/'REPLAY_SEEDS.json').read_text())};(control/'config.json').write_text(json.dumps(config,indent=2)+'\n');env=dict(os.environ,HUMANIZE_HOME=str(home),HUMANIZE_SENTRY='off',PYTHONDONTWRITEBYTECODE='1');env['PYTHONPATH']=str(repo)+os.pathsep+env.get('PYTHONPATH','');print('LAUNCHER '+str(control),flush=True);r=subprocess.run([str(Path(sys.executable).parent/'hmz'),'exec','-f','/home/jing/m6-lean-transfer-trace-formalization/.humanize-formal-runs/replay_flow','-c',str(control/'config.json'),'-a','cli=codex,model=gpt-6-astra,effort=medium,permission=read-only,web_search=false','Replay verified candidate proofs through frozen engine and prove remaining exact transfer nodes.'],cwd=control,env=env);raise SystemExit(r.returncode)
