name = "ipho_2026_run"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["IPhO2026Run"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[require]]
name = "PhysLean"
git = "https://github.com/HEPLean/PhysLean"
rev = "1706ae68b63996f1d97717e672e50c9e3933d933"

[[lean_lib]]
name = "IPhO2026Run"
