name = "archon_physics"
version = "0.2.0"
keywords = ["math"]
defaultTargets = ["ArchonPhysics", "ArchonPhysicsConsumers"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0"

[[require]]
name = "Physlib"
git = "https://github.com/HEPLean/PhysLean.git"
rev = "846bc6814ee141aa945d7385646b6e45385e635e"

[[lean_lib]]
name = "ArchonPhysics"

[[lean_lib]]
name = "ArchonPhysicsConsumers"
