from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent;S='M6.RecipeIsometries.';P='M6.Physical.';F='M6.Flatten.';B=S+'Block N';W=S+'Word N';V='M6.Pinned.Vector (2*N)';head='∀ (N : ℕ) [NeZero N]'
def props(f,a,b):
 return f'Function.Bijective ({f}) ∧ ∀ v : {V}, (({f}) v ∈ M6.Spaces.boundaryWords N ({a}) ({b}) ↔ v ∈ M6.Spaces.boundaryWords N a b) ∧ (({f}) v ∈ M6.Spaces.cycleWords N ({a}) ({b}) ↔ v ∈ M6.Spaces.cycleWords N a b) ∧ M6.Pinned.weight (({f}) v) = M6.Pinned.weight v'
rows=[
('permutation_weight',[],f'{head} (e : Equiv.Perm (ZMod N)) (a : {B}), {P}weight N (fun i => a (e i)) = {P}weight N a', 'Finite filtered-universe cardinality is invariant under the explicit index equivalence e. Use a filter-card bijection or convert card to a sum of indicators and reindex with Equiv.sum_comp. No parity or field assumption on ZModN.'),
('shift_laws',[],f'{head} (r : ZMod N) (a : {B}), {S}shift N 0 a = a ∧ {S}shift N (-r) ({S}shift N r a) = a ∧ ({S}shift N r a = 0 ↔ a = 0)', 'Unfold shift and prove function equalities coordinatewise by additive-group arithmetic. For zero iff apply the inverse shift to an equality; shift of the zero function is zero. The reverse inverse follows by using the same law at -r.'),
('multiply_laws',[],f'{head} (u : (ZMod N)ˣ) (a : {B}), {S}multiply N 1 a = a ∧ {S}multiply N (u⁻¹) ({S}multiply N u a) = a ∧ ({S}multiply N u a = 0 ↔ a = 0)', 'The inverse coefficient-index permutation uses the unit inverse. Unfold multiply and simplify inv_inv, units val_mul/val_inv_mul and multiplication associativity. Infer zero iff by applying the inverse. This is an exponent multiplier, not multiplication of a word by an arbitrary polynomial unit.'),
('conv_shift',[],f'{head} (r s : ZMod N) (a h : {B}), {P}conv N ({S}shift N r a) ({S}shift N s h) = {S}shift N (r+s) ({P}conv N a h)', 'Expand finite convolution at coordinatei and reindex the summation variable k to k+r using Equiv.addRight r. The index identity i-(k+r)-s=(i-(r+s))-k follows by abelian-group/ring arithmetic. Preserve actual cyclic indexing and all positive N.'),
('conv_multiply',[],f'{head} (u : (ZMod N)ˣ) (a h : {B}), {P}conv N ({S}multiply N u a) ({S}multiply N u h) = {S}multiply N u ({P}conv N a h)', 'Reindex the finite sum by the genuine equivalence u.mulLeft from Mathlib.Algebra.Group.Units.Equiv (works for units in any monoid; do not assume ZModN is a multiplicative group). Use inverse-unit cancellation and uinv*(i-u*k)=uinv*i-k. Both recipe and input coefficients are permuted.'),
('translated_boundary',['conv_shift','shift_laws'],f'{head} (r s : ZMod N) (a b h : {B}), {P}boundary N ({S}shift N r a) ({S}shift N s b) h = {S}translateWord N r s ({P}boundary N a b h)', 'Apply conv_shift to r,0 and s,0 and shift_laws atzero; expand boundary/translateWord and use pair equality. The generator inputh is unchanged by independent recipe translations.'),
('translated_syndrome',['conv_shift'],f'{head} (r s : ZMod N) (a b : {B}) (z : {W}), {P}syndrome N ({S}shift N r a) ({S}shift N s b) ({S}translateWord N r s z) = {S}shift N (r+s) ({P}syndrome N a b z)', 'Apply conv_shift to the two terms with shifts(s,r) and(r,s); commute s+r once. shift distributes over the pointwise sum definitionally. This is the original x^(r+s) syndrome relation.'),
('multiplied_boundary',['conv_multiply'],f'{head} (u : (ZMod N)ˣ) (a b h : {B}), {P}boundary N ({S}multiply N u a) ({S}multiply N u b) ({S}multiply N u h) = {S}multiplyWord N u ({P}boundary N a b h)', 'Expand the boundary pair and apply conv_multiply to each component. This uses the permuted generator input, as required for exact range transport.'),
('multiplied_syndrome',['conv_multiply'],f'{head} (u : (ZMod N)ˣ) (a b : {B}) (z : {W}), {P}syndrome N ({S}multiply N u a) ({S}multiply N u b) ({S}multiplyWord N u z) = {S}multiply N u ({P}syndrome N a b z)', 'Apply conv_multiply to both syndrome convolutions, then function extensionality; multiply is a coordinate pullback and distributes over the pointwise sum.'),
('exchange_laws',[],f'{head} (a b h : {B}) (z : {W}), {P}boundary N b a h = {S}exchange N ({P}boundary N a b h) ∧ {P}syndrome N b a ({S}exchange N z) = {P}syndrome N a b z', 'The boundary pair swaps definitionally. For the syndrome, expand exchange and use commutativity of addition in ZMod2. No module shear is involved.'),
('translated_weight',['permutation_weight'],f'{head} (r s : ZMod N) (z : {W}), {P}wordWeight N ({S}translateWord N r s z) = {P}wordWeight N z', 'Apply permutation_weight independently to the two blocks with index equivalences Equiv.addRight(-r) and Equiv.addRight(-s); shift(i)=a(i-r). Then add the block weight equalities.'),
('multiplied_weight',['permutation_weight'],f'{head} (u : (ZMod N)ˣ) (z : {W}), {P}wordWeight N ({S}multiplyWord N u z) = {P}wordWeight N z', 'Use permutation_weight with the unit equivalence (u⁻¹).mulLeft on each block. Units.mulLeft is available; no field or odd-order hypothesis.'),
('exchange_weight',[],f'{head} (z : {W}), {P}wordWeight N ({S}exchange N z) = {P}wordWeight N z', 'Unfold wordWeight/exchange; this is Nat.add_comm for the two physical block weights.'),
('lift_transport',[],f'{head} (a b a1 b1 : {B}) (P : {W} → {W}) (H : {B} → {B}), Function.Bijective P → Function.Surjective H → (∀ h, {P}boundary N a1 b1 (H h) = P ({P}boundary N a b h)) → (∀ z, {P}syndrome N a1 b1 (P z) = 0 ↔ {P}syndrome N a b z = 0) → (∀ z, {P}wordWeight N (P z) = {P}wordWeight N z) → {props(S+"lift N P","a1","b1")}', 'Use the verified physical/flatten/space closure. Flatten/unflatten are inverse, so lift of a bijectiveP is bijective. boundary_words_iff identifies actualB with flattened boundary range: H surjectivity handles any new generator, boundary transport and P injectivity give both directions. cycle_words_iff and flatten_left reduce actualC to the supplied exact syndrome equivalence. flatten_weight and flatten_right give physical weight preservation. Generic transport premises are discharged by the three concrete final generators.'),
('translation_isometry',['lift_transport','shift_laws','translated_boundary','translated_syndrome','translated_weight'],f'{head} (a b : {B}) (r s : ZMod N), {props(S+"translate N r s",S+"shift N r a",S+"shift N s b")}', 'Instantiate lift_transport with P=translateWord r s and H=id. Inverse shifts(-r,-s) prove bijectivity; id is surjective. Use translated_boundary/syndrome and shift_laws zero iff, then translated_weight. The conclusion is about the actual Spaces boundaryWords and cycleWords, not newly defined image sets.'),
('multiplier_isometry',['lift_transport','multiply_laws','multiplied_boundary','multiplied_syndrome','multiplied_weight'],f'{head} (a b : {B}) (u : (ZMod N)ˣ), {props(S+"multiplier N u",S+"multiply N u a",S+"multiply N u b")}', 'Instantiate lift_transport with P=multiplyWordu and H=multiplyu. The inverse-unit laws give P bijective and H surjective (choose inverse image usingu⁻¹). Apply the accepted exact boundary/syndrome/weight transport laws. No free isometry hypothesis remains.'),
('exchange_isometry',['lift_transport','exchange_laws','exchange_weight'],f'{head} (a b : {B}), {props(S+"blockExchange N","b","a")}', 'Instantiate lift_transport with P=exchange and H=id. Swapping a pair twice is the identity, hence bijective. exchange_laws gives exact boundary and syndrome statements; exchange_weight supplies physical weight. This proves the original generator without code-classification claims.')]
nodes=[{'id':i,'dependencies':ds,'spec':{'name':S+i,'statement':st,'imports':['M6RecipeIsometries'],'context':'','queries':['finite sum reindex equivalence translation'],'guidance':gd+' Return tactic proof lines without leading by, retaining the exact frozen statement and default limits.'},'metadata':{'source_section':'M6 original §9 recipe translations, unit exponent multipliers and block exchange','fallback_queries':['weight preserving involution minimum distance']}}for i,ds,st,gd in rows]
source=H.parents[4]/'research/quantum_m6/research_checkpoints/m6_original_gate_closed_20260915/PROOF.md';g={'title':'M6 original recipe generators preserve actual cycle/boundary pair and weight','source':str(source.relative_to(H.parents[4])),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'scope':'Independent cyclic translations, common unit exponent multipliers and block exchange are bijective physical coordinate maps preserving actual Spaces boundaryWords/cycleWords and Hamming weight. No shear or classification extension.','nodes':nodes};(H/'graph.json').write_text(json.dumps(g,ensure_ascii=False,indent=2)+'\n')
s='import M6RecipeIsometries\n\n'
for i,ds,st,gd in rows:s+='noncomputable def M6.RecipeTarget.'+i+' : Prop :=\n  '+st+'\n\n#check M6.RecipeTarget.'+i+'\n\n'
for D in [H/'lean',Path('/home/jing/m6-lean-recipe-isometries-formalization')]: (D/'GraphPreflight.lean').write_text(s)
