from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent;P=Path('/home/jing/m7-lean-selection-formalization');S='M7.Selection.'
A='∀ (α : Type)';B=A+' (T : Finset α) (R : α → α → Prop)';C=A+' (T : Finset α) (feasible : α → Prop) (R : α → α → Prop)';D=A+' (m : ℕ) (T : Finset α) (feasible : α → Prop) (objective : α → Fin m → ℤ) (mode : '+S+'Mode)'
hr='(∀ x, ¬ R x x) → (∀ x y z, R x y → R y z → R x z) → '
rows=[
('win_membership',[],C+f' (x : α), x ∈ {S}winners T feasible R ↔ {S}win T feasible R x','Unfold winners and win; prove filter membership. This is literal executable finite predicate expansion, retaining every tie.'),
('win_sound_complete',['win_membership'],C+f' (x : α), x ∈ {S}winners T feasible R ↔ x ∈ T ∧ feasible x ∧ ∀ y ∈ T, feasible y → ¬ R y x','Rewrite win_membership then unfold win; elementary quantifier negation. No relation assumptions are needed for soundness/completeness of the predicate.'),
('finite_extreme',[],B+', '+hr+'∀ x ∈ T, ∃ y ∈ T, (∀ z ∈ T, ¬ R z y) ∧ (y = x ∨ R y x)','Use finite well-foundedness on subtype T: Mathlib Finite.wellFounded_of_trans_of_irrefl (Data/Fintype/Card) with local IsTrans and Std.Irrefl instances. Well-founded induction on the chosen point: if it has an improving predecessor, recurse and compose transitivity; otherwise it is an extreme. Alternatively finite set induction. Only the finite relation is assumed, not an oracle witness.'),
('winning_dominator',['finite_extreme','win_membership'],C+', '+hr+f'∀ x ∈ T, feasible x → ∃ y ∈ {S}winners T feasible R, y = x ∨ R y x','Apply finite_extreme to feasibleSet T feasible; unfold its filter membership. Its extreme is exactly a winner in the original domain. Keep feasible membership when transporting quantifiers.'),
('empty_iff',['winning_dominator','win_membership'],C+', '+hr+f'({S}winners T feasible R = ∅ ↔ {S}feasibleSet T feasible = ∅)','Nonempty feasible set has a winning dominator. Conversely a winner is feasible by win. Finset.eq_empty_iff_forall_not_mem is obsolete; use Finset.eq_empty_of_forall_notMem or Finset.not_nonempty_iff_eq_empty.'),
('nonwinner_strict_dominator',['winning_dominator'],C+', '+hr+f'∀ x ∈ T, feasible x → x ∉ {S}winners T feasible R → ∃ y ∈ {S}winners T feasible R, R y x','The winning_dominator alternative y=x contradicts nonmembership, so retain its strict relation branch. This is the original omitted-record guarantee, including all finite non-total strict orders.'),
('pareto_laws',[],f'∀ (m : ℕ), (∀ a : Fin m → ℤ, ¬ {S}pareto a a) ∧ (∀ a b c : Fin m → ℤ, {S}pareto a b → {S}pareto b c → {S}pareto a c)','Unfold pareto. Irreflexivity follows from the required strict coordinate. For transitivity combine coordinatewise inequalities and reuse a strict coordinate from the first relation with the second weak inequality.'),
('lex_laws',[],f'∀ (m : ℕ), (∀ a : Fin m → ℤ, ¬ {S}lex a a) ∧ (∀ a b c : Fin m → ℤ, {S}lex a b → {S}lex b c → {S}lex a c)','Unfold the explicit first-differing-coordinate lex relation. For two witness indices i,j, split i<j,i=j,j<i; choose the earlier index and use preceding-coordinate equalities. At equal indices compose strict inequalities. Fin order trichotomy works even m=0.'),
('better_laws',['pareto_laws','lex_laws'],f'∀ (m : ℕ) (mode : {S}Mode), (∀ a : Fin m → ℤ, ¬ {S}better mode a a) ∧ (∀ a b c : Fin m → ℤ, {S}better mode a b → {S}better mode b c → {S}better mode a c)','Cases on the concrete mode and use the corresponding accepted laws. These are the actual Pareto/lex objective comparisons in the original selector.'),
('selector_exact',['win_sound_complete','empty_iff','better_laws'],D+f', (∀ x, x ∈ {S}select T feasible objective mode ↔ x ∈ T ∧ feasible x ∧ ∀ y ∈ T, feasible y → ¬ {S}better mode (objective y) (objective x)) ∧ ({S}select T feasible objective mode = ∅ ↔ {S}feasibleSet T feasible = ∅)','Instantiate the generic predicate results with R x y=better mode(objective x)(objective y). Discharge its strict-order hypotheses by better_laws. Final theorem has no free relation-transitivity or oracle-correctness hypothesis.'),
('selector_strict_dominator',['nonwinner_strict_dominator','better_laws'],D+f', ∀ x ∈ T, feasible x → x ∉ {S}select T feasible objective mode → ∃ y ∈ {S}select T feasible objective mode, {S}better mode (objective y) (objective x)','Instantiate nonwinner_strict_dominator and use actual better_laws. This returns a winning strictly improving action record for every feasible omitted record.'),
('empty_objectives',[],A+f' (T : Finset α) (feasible : α → Prop) (objective : α → Fin 0 → ℤ) (mode : {S}Mode), {S}select T feasible objective mode = {S}feasibleSet T feasible','With no objective coordinates neither Pareto nor lex can exhibit a strict coordinate. Unfold select/winners/win and use Fin.elim0 for an impossible coordinate; prove Finset extensional equality, handling any internal decidable instances by membership reasoning. All feasible records are retained as ties.')]
nodes=[{'id':i,'dependencies':ds,'spec':{'name':S+i,'statement':st,'imports':['M7Selection'],'context':'','queries':['finite strict order minimal element'],'guidance':gd+' Return tactic lines without leading by; preserve exact statement and default limits.'},'metadata':{'source_section':'M7 original §8 finite all-optima selector','fallback_queries':['finite set minimal element']}}for i,ds,st,gd in rows]
source=Path('/home/jing/quantum_code_discovery_proof/research_checkpoints/m7_compact_selector_final_20260915/PROOF.md');g={'title':'M7 exact finite winners and actual Pareto/lex selection','source':str(source),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'scope':'Original §8 winners, ties, empty answers and strict winning dominators. Actual Pareto/lex instantiate the generic finite relation lemmas; no efficiency strengthening. Least-preimage physical deduplication is a subsequent batch.','nodes':nodes};(H/'graph.json').write_text(json.dumps(g,ensure_ascii=False,indent=2)+'\n')
s='import M7Selection\n\n'
for i,ds,st,gd in rows:s+='noncomputable def M7.SelectionTarget.'+i+' : Prop :=\n  '+st+'\n\n#check M7.SelectionTarget.'+i+'\n\n'
for d in [H/'lean',P]:(d/'GraphPreflight.lean').write_text(s)
