from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent;N='M6.Euclid.';B=N+'BP'
r=lambda x:N+'rank '+x
rows=[
('binary_normalization',[],f'∀ p : {B}, (p ≠ 0 → p.Monic) ∧ normalize p = p', 'Every binary leading coefficient is0 or1, by ordinary decide over ZMod2. Nonzero p has nonzero leadingCoeff, hence1. Use Polynomial.Monic.normalize_eq_self; handle zero separately.'),
('rank_order',[],f'∀ p q : {B}, ({r("p")} < {r("q")} ↔ p.degree < q.degree) ∧ ({r("p")} ≤ {r("q")} ↔ p.degree ≤ q.degree)', 'Split p=0 and q=0; unfold rank and use Polynomial.degree_eq_natDegree for nonzero polynomials. The zero polynomial has rank0 and degree bottom. Preserve constants.'),
('cancel_drop',['binary_normalization','rank_order'],f'∀ p q : {B}, p ≠ 0 → q ≠ 0 → q.degree ≤ p.degree → {N}rank ({N}cancel p q) < {r("p")}', 'Apply Polynomial.div_wf_lemma to the actual cancellation definition and binary_normalization for monicity of q; transport degree strictness through rank_order.'),
('cancel_mod',[],f'∀ p q : {B}, {N}cancel p q % q = p % q', 'Use Polynomial.mod_eq_of_dvd_sub: cancel p q - p is a multiple ofq, directly by ring. Or ordinary Euclidean remainder add/sub/mul congruence. No nonzero assumptions required.'),
('remainder_aux_correct',['cancel_drop','cancel_mod','rank_order'],f'∀ (fuel : ℕ) (p q : {B}), {r("p")} ≤ fuel → ({N}remainderAux fuel p q).value = p % q ∧ ({N}remainderAux fuel p q).cancellations + {N}rank ({N}remainderAux fuel p q).value ≤ {r("p")}', 'Induct fuel generalizing p. At fuel0 rankp=0 forcesp=0. At stopping guard use mod_zero, zero_mod or Polynomial.mod_eq_self_iff q_nonzero. Otherwise cancel_drop gives enough remaining fuel; apply induction to cancel, cancel_mod and integer/natural arithmetic. The cancellation potential includes final remainder rank.'),
('remainder_correct',['remainder_aux_correct','rank_order'],f'∀ p q : {B}, ({N}remainder p q).value = p % q ∧ ({N}remainder p q).cancellations + {N}rank ({N}remainder p q).value ≤ {r("p")} ∧ (q ≠ 0 → {N}rank ({N}remainder p q).value < {r("q")})', 'Instantiate remainder_aux_correct at rankp; the extra degree-preparation pass does not change value/cancellations. For the final strict remainder bound use Polynomial.degree_mod_lt and rank_order.'),
('euclid_aux_correct',['remainder_correct'],f'∀ (fuel : ℕ) (p q : {B}), {r("q")} < fuel → ({N}euclidAux fuel p q).value = EuclideanDomain.gcd q p ∧ ({N}euclidAux fuel p q).cancellations + {N}rank ({N}euclidAux fuel p q).value ≤ {r("p")} + {r("q")} ∧ ({N}euclidAux fuel p q).rounds ≤ {r("q")}', 'Induct fuel generalizing p q. Base impossible. q0 stops with EuclideanDomain.gcd_zero_left. Otherwise remainder_correct gives rankr<rankq, sufficient recursive fuel, and c_rem+rankr≤rankp. EuclideanDomain.gcd_val q p rewrites gcd q p to gcd (p%q) q, matching recursion. Add induction potential inequality and remainder inequality; cancellation counts telescope even if degp<degq initially.'),
('normalized_gcd',['binary_normalization'],f'∀ p q : {B}, EuclideanDomain.gcd q p = GCDMonoid.gcd p q', 'Use dvd_antisymm_of_normalize_eq: all binary polynomials normalize to themselves, and normalize_gcd holds for the normalized GCDMonoid gcd. EuclideanDomain.gcd_dvd_left/right/dvd_gcd and root gcd_dvd_left/right/dvd_gcd show mutual divisibility. Keep the EuclideanDomain versus GCDMonoid namespaces explicit.'),
('euclid_correct',['euclid_aux_correct','normalized_gcd'],f'∀ p q : {B}, ({N}euclid p q).value = GCDMonoid.gcd p q ∧ ({N}euclid p q).cancellations ≤ {r("p")} + {r("q")} ∧ ({N}euclid p q).rounds ≤ {r("q")}', 'Use euclid_aux_correct with fuel rankq+1 and normalized_gcd. The top-level initial degree scan only changes passes. Drop the nonnegative final-rank term from the cancellation bound.'),
('remainder_passes',[],f'∀ (fuel : ℕ) (p q : {B}), ({N}remainderAux fuel p q).passes = 2 * ({N}remainderAux fuel p q).cancellations + 1', 'Direct structural induction fuel generalizing p q. Stopping states charge one scan; each executed cancellation adds two passes. This is an actual recursive counter identity, not a declared polynomial bound.'),
('euclid_aux_passes',['remainder_passes'],f'∀ (fuel : ℕ) (p q : {B}), ({N}euclidAux fuel p q).passes = 2 * ({N}euclidAux fuel p q).cancellations + 3 * ({N}euclidAux fuel p q).rounds + 1', 'Induct fuel. Unfold remainder and apply remainder_passes: each remainder call costs2c+2, including its initial degree/fuel scan; each Euclid call charges its own zero/degree scan. Combine with recursive identity by arithmetic.'),
('euclid_passes',['euclid_aux_passes'],f'∀ p q : {B}, ({N}euclid p q).passes = 2 * ({N}euclid p q).cancellations + 3 * ({N}euclid p q).rounds + 2', 'Unfold euclid; its initial rankq fuel scan adds one to the proven auxiliary pass counter.'),
('scan_cost',[],f'∀ width : ℕ, {N}scanCost width = width * (6 * width + 4) ∧ (0 < width → {N}scanCost width ≤ 10 * width ^ 2)', 'Prove a generalized foldl accumulator formula for the explicit List.range loop, or use List.foldl_assoc with addition. Every loop iteration adds6width+4. The quadratic bound follows for positive width by arithmetic; cost is derived from the loop, not defined as width squared.'),
('dense_cancel',['binary_normalization'],f'∀ (N : ℕ) (p q : {B}), p ≠ 0 → {N}dense N ({N}cancel p q) = {N}denseXor N p q (p.natDegree - q.natDegree)', 'Nonzero binary p has leadingCoeff1. Expand cancel and dense/List.ofFn; coefficient of q*X^shift is q.coeff(i-shift) when shift≤i, else0. Binary subtraction is addition/XOR (CharTwo). Prove list equality via ofFn congruence or ext entries. This connects the actual polynomial update to the dense indexed-array update.'),
('dense_rank',[],f'∀ (width : ℕ) (p : {B}), {r("p")} ≤ width → {N}scanRank width p = {r("p")}', 'Induct width using List.range_succ and List.foldl_append. Under rankp≤width+1, either rankp≤width and coefficient atwidth iszero, so induction persists; or rankp=width+1, so nonzero p has natDegreewidth and leading coefficient nonzero, and the final iteration setswidth+1. Basewidth0 forcesp0. This proves actual coefficient-array degree scanning, leaving no degree oracle.'),
('dense_injective',[],f'∀ (N : ℕ) (p q : {B}), {r("p")} ≤ N + 1 → {r("q")} ≤ N + 1 → {N}dense N p = {N}dense N q → p = q', 'Polynomial.ext on coefficient indexi. Ifi<N+1, extract the matching List.ofFn entry. Otherwise both coefficients vanish by degree bounds, splitting zero polynomial when converting rank to natDegree. Thus truncated arrays are faithful when the invariant holds.'),
('remainder_safe',['cancel_drop'],f'∀ (fuel : ℕ) (p q : {B}) (width : ℕ), {r("p")} ≤ width → {r("q")} ≤ width → {N}remainderSafe fuel p q width', 'Induct fuel generalizing p. The stopping predicate needs no recursion. Otherwise cancel_drop bounds the next operand strictly below p, preserving both fixed-width bounds. This ghost safety predicate checks every actual recursive intermediate operand.'),
('euclid_safe',['remainder_safe','remainder_correct'],f'∀ (fuel : ℕ) (p q : {B}) (width : ℕ), {r("p")} ≤ width → {r("q")} ≤ width → {N}euclidSafe fuel p q width', 'Induct fuel generalizing p q. For nonzeroq, remainder_safe proves its entire inner loop fits width; remainder_correct bounds rank of its value by rankp (or strictly by rankq), then apply induction to the next Euclid pair. No fuel sufficiency premise needed for width safety.'),
('euclid_output_width',['remainder_correct'],f'∀ (fuel : ℕ) (p q : {B}), {N}rank ({N}euclidAux fuel p q).value ≤ max ({r("p")}) ({r("q")})', 'Induct fuel generalizing p q. Stopping output is p. Otherwise remainder_correct bounds rankr≤rankp, and induction gives output≤max(rankq,rankr)≤max(rankp,rankq). This supplies the width bound when composing two gcd calls.'),
('bit_cost_bound',['euclid_correct','euclid_passes','scan_cost','euclid_safe'],f'∀ (N : ℕ) (p q : {B}), p.natDegree ≤ N → q.natDegree ≤ N → {N}bitCost N p q ≤ 90 * (N + 1) ^ 3 ∧ {N}euclidSafe ({r("q")} + 1) p q (N + 1)', 'Rankp,rankq≤N+1 by definition, including zero. euclid_correct gives c≤2width and e≤width; euclid_passes yields passes≤7width+2≤9width forwidth=N+1≥1. scan_cost≤10width², hence≤90width³ by multiplication arithmetic. euclid_safe proves every actual operand fits these arrays. No arbitrary oracle/cost premise.'),
('preprocess_correct_cost',['euclid_correct','euclid_output_width','bit_cost_bound'],f'∀ (N : ℕ) (a b M : {B}), a.natDegree ≤ N → b.natDegree ≤ N → M.natDegree ≤ N → ({N}preprocess a b M).value = GCDMonoid.gcd (GCDMonoid.gcd a b) M ∧ {N}preprocessBitCost N a b M ≤ 180 * (N + 1) ^ 3', 'Unfold the actual shared two-call preprocessing. euclid_correct identifies first and final outputs. euclid_output_width bounds the first result rank bymax initial ranks≤N+1, hence natDegree≤N (split zero if needed). Apply bit_cost_bound to both calls and distribute pass count times scanCost. This is source gcd(a,b,M) preprocessing with its conservative cubic bit bound.')]
nodes=[{'id':i,'dependencies':ds,'spec':{'name':N+i,'statement':st,'imports':['M6Euclid'],'context':'','queries':['EuclideanDomain gcd Bezout divisibility'],'guidance':gd+' Return tactic proof lines without leading by; preserve the exact frozen statement and default compiler/axiom limits.'},'metadata':{'source_section':'M6 original §1 gcd preprocessing and §5 indexed-array bit model','fallback_queries':['polynomial divisibility multiplication cancellation']}}for i,ds,st,gd in rows]
source=H.parents[4]/'research/quantum_m6/research_checkpoints/m6_original_gate_closed_20260915/PROOF.md'
g={'title':'M6 binary leading-XOR Euclid and actual cubic preprocessing cost','source':str(source.relative_to(H.parents[4])),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'scope':'Actual fuel-based binary leading-term remainder and Euclidean recursion; exact normalized gcd, telescoping cancellation/round bounds, faithful fixed-width dense XOR updates and conservative original indexed-array bit cost including degree preparation.','nodes':nodes}
(H/'graph.json').write_text(json.dumps(g,ensure_ascii=False,indent=2)+'\n')
s='import M6Euclid\n\n'
for i,ds,st,gd in rows:s+='noncomputable def M6.EuclidTarget.'+i+' : Prop :=\n  '+st+'\n\n#check M6.EuclidTarget.'+i+'\n\n'
for D in [H/'lean',Path('/home/jing/m6-lean-euclid-formalization')]: (D/'GraphPreflight.lean').write_text(s)
