"""Per-target proof Review retry accounting and dispatch gating.

The outer Archon loop is project-scoped, so ``max_iterations`` cannot express
"give every theorem at most N reviewed proof attempts". This module persists
that missing per-file state.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


STATE_FILENAME = "proof-review-gate.json"
REPORT_FILENAME = "PROOF_REVIEW_GATE.md"
AUTO_NOTES_FILENAME = "AUTO_NOTES.md"
PASS_STATUSES = {
    "solved", "passed", "pass", "complete", "completed", "success", "closed",
}


@dataclass(frozen=True)
class ProofReviewResult:
    solved: tuple[str, ...]
    retry: tuple[str, ...]
    exhausted: tuple[str, ...]
    reviewed: tuple[str, ...]


def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _relative_file(value: str, project_path: Path) -> str:
    path = Path(value)
    try:
        return str(path.resolve().relative_to(project_path.resolve()))
    except (OSError, ValueError):
        return str(path)


def load_proof_review_state(state_dir: Path) -> dict:
    path = state_dir / STATE_FILENAME
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def _load_milestones(session_dir: Path, project_path: Path) -> dict[str, dict]:
    path = session_dir / "milestones.jsonl"
    rows: dict[str, dict] = {}
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return rows
    for line in lines:
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(row, dict):
            continue
        target = row.get("target")
        if not isinstance(target, dict):
            continue
        raw_file = str(target.get("file") or "")
        if raw_file:
            rows[_relative_file(raw_file, project_path)] = row
    return rows


def _write_report(state_dir: Path, state: dict) -> None:
    targets = state.get("targets", {})
    buckets: dict[str, list[str]] = {
        "solved": [], "retry": [], "proof_review_exhausted": [],
    }
    for rel, record in sorted(targets.items()):
        if isinstance(record, dict):
            buckets.setdefault(
                str(record.get("status") or "retry"), []
            ).append(rel)
    lines = [
        "# Proof Review Gate",
        "",
        f"- Maximum reviewed proof attempts per target: {state.get('max_iterations', 3)}",
        f"- Solved: {len(buckets.get('solved', []))}",
        f"- Retry: {len(buckets.get('retry', []))}",
        f"- Review exhausted: {len(buckets.get('proof_review_exhausted', []))}",
        "",
    ]
    for key, title in (
        ("retry", "Retry in the next proof batch"),
        ("proof_review_exhausted", "Proof Review exhausted"),
    ):
        values = buckets.get(key, [])
        if values:
            lines.extend([f"## {title}", ""])
            for rel in values:
                record = targets[rel]
                lines.append(
                    f"- `{rel}` — attempts {record.get('attempts', 0)}/"
                    f"{state.get('max_iterations', 3)}; "
                    f"{record.get('reason', '')}"
                )
            lines.append("")
    (state_dir / REPORT_FILENAME).write_text(
        "\n".join(lines).rstrip() + "\n", encoding="utf-8",
    )


def _write_retry_notes(
    state_dir: Path,
    *,
    retry: list[str],
    exhausted: list[str],
    targets: dict,
    max_iterations: int,
) -> None:
    if not retry and not exhausted:
        return
    lines = [
        "# Automated proof Review retry notes",
        "",
        "These notes are generated by the per-target proof Review gate.",
    ]
    if retry:
        lines.extend([
            "",
            "## Mandatory proof retries",
            "",
            "Schedule these Review-failed targets first in the next batch, "
            "then fill remaining concurrency slots with new eligible targets:",
        ])
        for rel in retry:
            record = targets[rel]
            lines.append(
                f"- `{rel}` — reviewed attempt {record['attempts']}/"
                f"{max_iterations}: {record.get('reason', '')}"
            )
    if exhausted:
        lines.extend([
            "",
            "## Proof Review exhausted",
            "",
            "Do not schedule these targets again:",
        ])
        lines.extend(f"- `{rel}`" for rel in exhausted)
    (state_dir / AUTO_NOTES_FILENAME).write_text(
        "\n".join(lines).rstrip() + "\n", encoding="utf-8",
    )


def apply_proof_review(
    *,
    state_dir: Path,
    project_path: Path,
    session_dir: Path,
    iter_num: int,
    reviewed_objectives: Iterable[Path],
    max_iterations: int,
) -> ProofReviewResult:
    """Consume one proof Review verdict for every dispatched objective."""
    max_iterations = max(1, int(max_iterations))
    state = load_proof_review_state(state_dir)
    targets = state.get("targets")
    if not isinstance(targets, dict):
        targets = {}
    milestones = _load_milestones(session_dir, project_path)
    solved: list[str] = []
    retry: list[str] = []
    exhausted: list[str] = []
    reviewed: list[str] = []
    seen: set[str] = set()
    for objective in reviewed_objectives:
        rel = _relative_file(str(objective), project_path)
        if not rel or rel in seen:
            continue
        seen.add(rel)
        previous = targets.get(rel)
        if not isinstance(previous, dict):
            previous = {}
        if str(previous.get("status") or "") in {
            "solved", "proof_review_exhausted",
        }:
            continue
        row = milestones.get(rel)
        raw_status = str(row.get("status") or "") if row else ""
        status_key = raw_status.strip().lower().replace("-", "_")
        attempts = int(previous.get("attempts") or 0) + 1
        if status_key in PASS_STATUSES:
            status = "solved"
            reason = f"proof Review status={raw_status or 'solved'}"
            solved.append(rel)
        elif attempts >= max_iterations:
            status = "proof_review_exhausted"
            reason = (
                f"proof Review status={raw_status or 'missing verdict'}; "
                "maximum attempts reached"
            )
            exhausted.append(rel)
        else:
            status = "retry"
            reason = f"proof Review status={raw_status or 'missing verdict'}"
            retry.append(rel)
        targets[rel] = {
            "status": status,
            "attempts": attempts,
            "last_review_iter": iter_num,
            "reason": reason,
            "updated_at": _utcnow(),
        }
        reviewed.append(rel)
    state = {
        "version": 1,
        "max_iterations": max_iterations,
        "last_review_iter": iter_num,
        "updated_at": _utcnow(),
        "targets": targets,
    }
    state_path = state_dir / STATE_FILENAME
    state_tmp = state_path.with_suffix(state_path.suffix + ".tmp")
    state_tmp.write_text(
        json.dumps(state, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    state_tmp.replace(state_path)
    _write_report(state_dir, state)
    _write_retry_notes(
        state_dir,
        retry=retry,
        exhausted=exhausted,
        targets=targets,
        max_iterations=max_iterations,
    )
    return ProofReviewResult(
        solved=tuple(sorted(solved)),
        retry=tuple(sorted(retry)),
        exhausted=tuple(sorted(exhausted)),
        reviewed=tuple(sorted(reviewed)),
    )


def filter_objectives_for_proof_review_gate(
    objectives: Iterable[Path],
    *,
    state_dir: Path,
    project_path: Path,
    enabled: bool,
) -> tuple[list[Path], list[tuple[Path, str]]]:
    items = list(objectives)
    if not enabled:
        return items, []
    state = load_proof_review_state(state_dir)
    targets = state.get("targets", {}) if state else {}
    kept: list[Path] = []
    dropped: list[tuple[Path, str]] = []
    for path in items:
        rel = _relative_file(str(path), project_path)
        record = targets.get(rel) if isinstance(targets, dict) else None
        status = str(record.get("status") or "") if isinstance(record, dict) else ""
        if status in {"solved", "proof_review_exhausted"}:
            dropped.append((path, status))
        else:
            kept.append(path)
    return kept, dropped


def proof_review_prompt_block(
    *,
    state_dir: Path,
    max_iterations: int,
    enabled: bool,
) -> str:
    if not enabled:
        return ""
    state = load_proof_review_state(state_dir)
    targets = state.get("targets", {}) if state else {}
    retry = [
        (rel, record)
        for rel, record in sorted(targets.items())
        if isinstance(record, dict) and record.get("status") == "retry"
    ]
    exhausted = [
        rel for rel, record in sorted(targets.items())
        if isinstance(record, dict)
        and record.get("status") == "proof_review_exhausted"
    ]
    lines = [
        "",
        "## Per-target proof Review retry gate",
        "",
        f"Each target may receive at most {max_iterations} reviewed proof attempts.",
        "Schedule retry targets first, then fill the batch with new eligible targets.",
        "Never schedule proof_review_exhausted targets.",
        f"Current retry targets: {len(retry)}; exhausted targets: {len(exhausted)}.",
    ]
    for rel, record in retry:
        lines.append(
            f"- RETRY `{rel}` — {record.get('attempts', 0)}/{max_iterations} "
            f"used; {record.get('reason', '')}"
        )
    if exhausted:
        lines.append(
            "- EXHAUSTED: " + ", ".join(f"`{rel}`" for rel in exhausted)
        )
    return "\n".join(lines) + "\n"
