from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent;P=Path('/home/jing/m7-lean-global-query-formalization');S='M7.GlobalQuery.';A='∀ (H N : ℕ) [NeZero N] (q : M7.DefaultQuery.Query) (bases : '+S+'Family H N)';I=S+'Index H N';W=S+'winners q bases';F=lambda x:S+'feasible q bases '+x;O=lambda x:S+'objective q bases '+x;R=lambda x:S+'realize bases '+x;Pr=lambda x:S+'present q bases '+x;B=lambda x,y:'M7.Selection.better q.order ('+O(x)+') ('+O(y)+')'
rows=[
('winners_exact',[],A+f', (∀ x : {I}, x ∈ {W} ↔ {F("x")} ∧ ∀ y : {I}, {F("y")} → ¬ {B("y","x")}) ∧ ({W} = ∅ ↔ ¬ ∃ x : {I}, {F("x")})','Instantiate Selection.selector_exact over the whole Fin H × actual Record domain. Competitors range over every class and action, never only the current base orbit. Simplify univ membership and feasibleSet emptiness.'),
('strict_dominator',[],A+f' (x : {I}), {F("x")} → x ∉ {W} → ∃ y ∈ {W}, {B("y","x")}','Instantiate Selection.selector_strict_dominator for the full finite product domain and literal DefaultQuery predicates. Pareto/lex order laws are already accepted.'),
('winning_classes',[],A+f' (i : Fin H), i ∈ {S}winningClasses q bases ↔ ∃ g : M7.Action.Record N, (i,g) ∈ {W}','Unfold winningClasses and use Finset.mem_image; product extensionality converts the first component equality. Keep every tied class.'),
('winning_fiber',['winners_exact'],A+f' (x y : {I}), x.1 = y.1 → {R("x")} = {R("y")} → (x ∈ {W} ↔ y ∈ {W})','Use winners_exact. Same class index and actual image make concrete feasible and objective equal; global competitors are identical. Do not assume class-label invariance for different images.'),
('presentation_sound',[],A+f' (x : {I}), {Pr("x")} → x ∈ {W} ∧ ∀ g : M7.Action.Record N, M7.Action.act g (bases x.1) = {R("x")} → M7.ActualPresentation.encode x.2 ≤ M7.ActualPresentation.encode g','Unfold present and apply the some direction of verified ActualPresentation.leastAction_spec. The winner is global; the least-preimage search is within its one structural class.'),
('same_class_presentation',['winning_fiber'],A+f' (x : {I}), x ∈ {W} → ∃! g : M7.Action.Record N, {Pr("(x.1,g)")} ∧ M7.Action.act g (bases x.1) = {R("x")}','Apply verified leastAction_spec to target realize bases x. Its none alternative is impossible because x.2 is a preimage. The some candidate is globally winning by winning_fiber. Any other presented preimage has the same leastAction value, hence identical action. Do not substitute per-class optima.'),
('physical_presentation',['same_class_presentation'],A+f', {S}separated bases → ∀ x ∈ {W}, ∃! y : {I}, {Pr("y")} ∧ {R("y")} = {R("x")}','Use same_class_presentation. The explicit intermediate separated property forces any competing same-image record to have x.1 as its class index. Then uniqueness of the action supplies product equality. This hypothesis will be discharged by actual canonical-generation closure at the final root, not assumed there.'),
('empty_objectives',[],A+f', q.objectives = [] → {W} = M7.Selection.feasibleSet Finset.univ ({S}feasible q bases)','Instantiate accepted Selection.empty_objectives after destructuring/replacing Query.objectives so its dependent Fin length is zero. Keep all global feasible indices.'),
('invalid_rejection',['winners_exact'],A+f', (¬ M7.DefaultQuery.valid N q → {S}answer q bases = Except.error M7.DefaultQuery.QueryError.invalidSignature ∧ {W} = ∅) ∧ (M7.DefaultQuery.valid N q → {S}answer q bases = Except.ok ({W}))','Unfold answer for the error/ok branch. For empty winners use winners_exact and the valid conjunct of actual DefaultQuery.feasible. Invalid signatures are rejected, distinct from a legal empty global answer.')]
nodes=[{'id':i,'dependencies':ds,'spec':{'name':S+i,'statement':st,'imports':['M7GlobalQuery','M7SelectionAccepted','M7ActualPresentationAccepted'],'context':'','queries':['finite set minimum lexicographic order'],'guidance':gd+' Return tactic lines without leading by; preserve frozen target and default limits.'},'metadata':{'source_section':'M7 original §8/9 global classes/actions and distinct physical ties','fallback_queries':['algebra']}}for i,ds,st,gd in rows];source=Path('/home/jing/quantum_code_discovery_proof/research_checkpoints/m7_compact_selector_final_20260915/PROOF.md');g={'title':'M7 global finite-family default query and physical presentations','source':str(source),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'scope':'Actual global comparisons over Fin H × Action.Record, all ties and exact least-preimage presentation. Structural family coverage and orbit separation must be supplied by proved canonical enumeration in the final root; no free full-transversal premise is a final conclusion.','nodes':nodes};(H/'graph.json').write_text(json.dumps(g,ensure_ascii=False,indent=2)+'\n');s='import M7GlobalQuery\nimport M7SelectionAccepted\nimport M7ActualPresentationAccepted\n\n'
for i,ds,st,gd in rows:s+='noncomputable def M7.GlobalQueryTarget.'+i+' : Prop :=\n  '+st+'\n\n#check M7.GlobalQueryTarget.'+i+'\n\n'
for d in [P,H/'lean']:(d/'GraphPreflight.lean').write_text(s)
