import M7GlobalQueryAccepted
import M7ActionAccepted
import M7RecipeSignatureAccepted
import M7ActualFactorizedAccepted
import M7PrefixOrbitAccepted
import M7CanonicalOuterAccepted
import M7CanonicalClassesAccepted
import M7CompactCorrectnessAccepted
import M7GeneratedFamilyAccepted
import M7OverfullBoundaryAccepted
import M7QuerySectorsAccepted
import M7FinalSelectorAccepted
import M7DefaultQueryAccepted
import M7ActualPresentationAccepted
import M7GeneratedLabelsAccepted
import M7FinalReplayAccepted
import M7GenerationReplayAccepted
import M7LabelReplayAccepted
import M7FactorReplayAccepted
import M7FinalResourcesAccepted
import M7ScalarWorkAccepted
import M7CompactStorageAccepted
import M7GenerationCallsAccepted
import M7StreamingCostAccepted
import M7ObjectiveComparisonAccepted
import M7SelectionAccepted

namespace M7.Final

/-- Exact frozen original-scope clauses; no correctness proposition is an input. -/
noncomputable def ActionSignature : Prop :=
  (∀ (N : ℕ) [NeZero N], Fintype.card (M7.Action.Record N) = Nat.totient N * 2 * N * N) ∧
  (Fintype.card (M7.Action.Record 1) = 2) ∧
  (∀ (N : ℕ) [NeZero N], ∀ c : M7.Action.Recipe N, (M7.RecipeSignature.signature c).Monic ∧ M7.RecipeSignature.signature c ∣ (M6.Cyclic.modulus N)) ∧
  (∀ (N : ℕ) [NeZero N], ∀ c : M7.Action.Recipe N, ∀ g : M7.Action.Record N, M7.RecipeSignature.signature (M7.Action.act g c) = M7.SignatureTau.sourceTau g.unit (M7.RecipeSignature.signature c)) ∧
  (∀ (N : ℕ) [NeZero N], ∀ (u : (ZMod N)ˣ) (F : M6.Cyclic.BinaryPolynomial), F.Monic → F ∣ (M6.Cyclic.modulus N) → (M7.SignatureTau.tau u F).natDegree = F.natDegree) ∧
  (∀ (N : ℕ) [NeZero N], ∀ c : M7.Action.Recipe N, ∀ (E : M6.Cyclic.BinaryPolynomial → Prop) (L R : Finset (ZMod N) → Prop), M7.RecipeSignature.sourceCount c E L R = M7.ActualOrbit.distinctCount c (fun y => E (M7.RecipeSignature.signature y) ∧ L y.1 ∧ R y.2) ∧ M7.ActualFactorized.stabilizerNumerator c ∣ M7.RecipeSignature.sourceNumerator c E L R) ∧
  (∀ (N : ℕ) [NeZero N], ∀ c : M7.Action.Recipe N, M7.ActualFactorized.stabilizerNumerator c = M7.ActualOrbit.stabilizerCount c) ∧
  (∀ (N : ℕ) [NeZero N], ∀ c : M7.Action.Recipe N, 0 < M7.ActualFactorized.stabilizerNumerator c) ∧
  (∀ (N : ℕ) [NeZero N], ∀ c : M7.Action.Recipe N, ∀ (E : M7.Action.Recipe N → Prop) (L R : Finset (ZMod N) → Prop), M7.ActualFactorized.TranslationInvariant E → (M7.ActualFactorized.numerator c (fun u => E (M7.ActualFactorized.outerImage c u)) L R / M7.ActualFactorized.stabilizerNumerator c = M7.ActualOrbit.distinctCount c (fun y => E y ∧ L y.1 ∧ R y.2) ∧ M7.ActualFactorized.stabilizerNumerator c ∣ M7.ActualFactorized.numerator c (fun u => E (M7.ActualFactorized.outerImage c u)) L R)) ∧
  (∀ (N : ℕ) [NeZero N], ∀ (w : ℕ) (E : Finset M5.BinaryPolynomial) (A B WA WB : Finset ℕ), M7.PrefixSector.ValidSector N E → M7.PrefixCompleted.Base N A B WA WB → ∀ bases : Finset (M7.Action.Recipe N), (∀ c ∈ bases, M7.PrefixOrbit.ClassValid w c) → M7.CanonicalClasses.Normalized bases → M7.PrefixOrbit.residual w E A B WA WB bases = (M7.OrbitResidual.remaining (M7.ResiduePrefix.completed N w E A B WA WB) bases).card) ∧
  (∀ (N : ℕ) [NeZero N], ∀ (w : ℕ) (E : Finset M5.BinaryPolynomial) (A B WA WB : Finset ℕ), M7.PrefixSector.ValidSector N E → M7.PrefixCompleted.Base N A B WA WB → ∀ bases : Finset (M7.Action.Recipe N), (∀ c ∈ bases, M7.PrefixOrbit.ClassValid w c) → M7.CanonicalClasses.Normalized bases → 0 ≤ M7.PrefixOrbit.residual w E A B WA WB bases ∧ (0 < M7.PrefixOrbit.residual w E A B WA WB bases ↔ ∃ y ∈ M7.ResiduePrefix.completed N w E A B WA WB, y ∉ M7.OrbitResidual.covered bases))

/-- Exact frozen original-scope clauses; no correctness proposition is an input. -/
noncomputable def Canonical : Prop :=
  (∀ (N : ℕ) [NeZero N], ∀ (c : M7.Action.Recipe N) k, k ∈ M7.CanonicalOuter.keyset c → M7.CanonicalOuter.pairKey (M7.CanonicalOuter.canonical c) ≤ k) ∧
  (∀ (N : ℕ) [NeZero N], ∀ c : M7.Action.Recipe N, M7.Action.act (M7.CanonicalOuter.realizer c) c = M7.CanonicalOuter.canonical c) ∧
  (∀ (N : ℕ) [NeZero N], ∀ c : M7.Action.Recipe N, M7.Action.act (M7.Action.inverse (M7.CanonicalOuter.realizer c)) (M7.CanonicalOuter.canonical c) = c) ∧
  (∀ (N : ℕ) [NeZero N], ∀ (g : M7.Action.Record N) (c : M7.Action.Recipe N), M7.CanonicalOuter.canonical (M7.Action.act g c) = M7.CanonicalOuter.canonical c) ∧
  (∀ (N : ℕ) [NeZero N], ∀ c d : M7.Action.Recipe N, (∃ g : M7.Action.Record N, M7.Action.act g c = d) ↔ M7.CanonicalOuter.canonical c = M7.CanonicalOuter.canonical d) ∧
  (∀ (N : ℕ) [NeZero N], ∀ c : M7.Action.Recipe N, M7.CanonicalOuter.canonical (M7.CanonicalOuter.canonical c) = M7.CanonicalOuter.canonical c)

/-- Exact frozen original-scope clauses; no correctness proposition is an input. -/
noncomputable def Generation : Prop :=
  (∀ (N : ℕ) [NeZero N] (w : ℕ) (E : Finset M5.BinaryPolynomial), ∀ (bases : Finset (M7.Action.Recipe N)) (fuel : ℕ) (root : ℤ), ∀ e ∈ (M7.CompactGeneration.run w E fuel bases root).emitted, M7.Action.act e.action e.leaf = e.representative ∧ M7.Action.act (M7.Action.inverse e.action) e.representative = e.leaf ∧ e.leafSignature = M7.RecipeSignature.signature e.leaf ∧ e.representativeSignature = M7.RecipeSignature.signature e.representative ∧ e.stabilizer = M7.ActualFactorized.stabilizerNumerator e.representative ∧ 0 < e.stabilizer) ∧
  (∀ (N : ℕ) [NeZero N] (w : ℕ) (E : Finset M5.BinaryPolynomial), M7.PrefixSector.ValidSector N E → M7.RecoveryInstance.GoodBases w (M7.CompactGeneration.generate (N := N) w E).finalBases ∧ (M7.CompactGeneration.generate (N := N) w E).finalResidual = 0 ∧ (M7.CompactGeneration.generate (N := N) w E).fuelExhausted = false ∧ ((M7.CompactGeneration.generate (N := N) w E).emitted.map (fun e => e.representative)).Nodup) ∧
  (∀ (N : ℕ) [NeZero N] (w : ℕ) (E : Finset M5.BinaryPolynomial), M7.PrefixSector.ValidSector N E → (M7.CompactGeneration.generate (N := N) w E).finalBases.card = (M7.CompactGeneration.generate (N := N) w E).emitted.length) ∧
  (∀ (N : ℕ) [NeZero N] (w : ℕ) (E : Finset M5.BinaryPolynomial), M7.PrefixSector.ValidSector N E → ∀ y ∈ M7.RecoveryPrefix.completed N w E [], y ∈ M7.OrbitResidual.covered (M7.CompactGeneration.generate (N := N) w E).finalBases) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → ∀ b : M7.Action.Recipe N, b ∈ (M7.CompactGeneration.generate (N := N) w E).finalBases ↔ ∃ i : Fin (M7.GeneratedFamily.size N w E), M7.GeneratedFamily.family N w E i = b) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → ∀ i : Fin (M7.GeneratedFamily.size N w E), M7.PrefixOrbit.ClassValid w (M7.GeneratedFamily.family N w E i) ∧ M7.CanonicalOuter.canonical (M7.GeneratedFamily.family N w E i) = M7.GeneratedFamily.family N w E i) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → ∀ i : Fin (M7.GeneratedFamily.size N w E), (0 : ZMod N) ∈ (M7.GeneratedFamily.family N w E i).1 ∧ (0 : ZMod N) ∈ (M7.GeneratedFamily.family N w E i).2) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → Function.Injective (M7.GeneratedFamily.family N w E)) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → M7.GlobalQuery.separated (M7.GeneratedFamily.family N w E)) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → ∀ i : Fin (M7.GeneratedFamily.size N w E), ∃ g : M7.Action.Record N, M7.RecipeSignature.signature (M7.Action.act g (M7.GeneratedFamily.family N w E i)) ∈ E) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → ∀ c : M7.Action.Recipe N, (∃ (i : Fin (M7.GeneratedFamily.size N w E)) (g : M7.Action.Record N), M7.Action.act g (M7.GeneratedFamily.family N w E i) = c) ↔ M7.PrefixOrbit.ClassValid w c ∧ ∃ g : M7.Action.Record N, M7.RecipeSignature.signature (M7.Action.act g c) ∈ E) ∧
  (∀ (N w : ℕ) [NeZero N], N < w → ∀ c : M7.Action.Recipe N, ¬ M7.PrefixOrbit.ClassValid w c) ∧
  (∀ (N w : ℕ) [NeZero N], ∀ E : Finset M5.BinaryPolynomial, M7.PrefixSector.ValidSector N E → N < w → (M7.CompactGeneration.generate (N := N) w E).finalBases = ∅ ∧ (M7.CompactGeneration.generate (N := N) w E).emitted = [] ∧ (M7.CompactGeneration.generate (N := N) w E).finalResidual = 0 ∧ (M7.CompactGeneration.generate (N := N) w E).fuelExhausted = false) ∧
  (∀ (N w : ℕ) [NeZero N], 0 < w → M7.CompactGeneration.residual (N := N) w ∅ ∅ [] = 0) ∧
  (∀ (N w : ℕ) [NeZero N], 0 < w → (M7.CompactGeneration.generate (N := N) w ∅).finalBases = ∅ ∧ (M7.CompactGeneration.generate (N := N) w ∅).emitted = [] ∧ (M7.CompactGeneration.generate (N := N) w ∅).finalResidual = 0 ∧ (M7.CompactGeneration.generate (N := N) w ∅).fuelExhausted = false) ∧
  (∀ (N : ℕ) [NeZero N], ∀ (F : M6.Cyclic.BinaryPolynomial), F ∈ M7.QuerySectors.allSectors N → F.Monic ∧ F ∣ M6.Cyclic.modulus N) ∧
  (∀ (N : ℕ) [NeZero N], ∀ (F : M6.Cyclic.BinaryPolynomial), F.Monic → F ∣ M6.Cyclic.modulus N → F ∈ M7.QuerySectors.allSectors N) ∧
  (∀ (N : ℕ) [NeZero N], ∀ (F : M6.Cyclic.BinaryPolynomial), F ∈ M7.QuerySectors.allSectors N ↔ F.Monic ∧ F ∣ M6.Cyclic.modulus N) ∧
  (∀ (N : ℕ) [NeZero N], ∀ q : M7.DefaultQuery.Query, M7.DefaultQuery.valid N q → M7.PrefixSector.ValidSector N (M7.QuerySectors.effective N q)) ∧
  (∀ (N : ℕ) [NeZero N], ∀ (q : M7.DefaultQuery.Query) (c : M7.Action.Recipe N), M7.DefaultQuery.signature c ∈ M7.QuerySectors.effective N q ↔ M7.DefaultQuery.allows q (M7.DefaultQuery.signature c))

/-- Exact frozen original-scope clauses; no correctness proposition is an input. -/
noncomputable def Selector : Prop :=
  (∀ (H N : ℕ) [NeZero N] (q : M7.DefaultQuery.Query) (bases : M7.GlobalQuery.Family H N) (i : Fin H), i ∈ M7.GlobalQuery.winningClasses q bases ↔ ∃ g : M7.Action.Record N, (i,g) ∈ M7.GlobalQuery.winners q bases) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), 0 < w → w ≤ N → M7.DefaultQuery.valid N q → ∀ c : M7.Action.Recipe N, M7.FinalSelector.RawFeasible w q c → ∃ x : M7.FinalSelector.Index N w q, M7.FinalSelector.realize q x = c) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), 0 < w → w ≤ N → M7.DefaultQuery.valid N q → ∀ x : M7.FinalSelector.Index N w q, M7.GlobalQuery.feasible q (M7.FinalSelector.family N w q) x ↔ M7.FinalSelector.RawFeasible w q (M7.FinalSelector.realize q x)) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), 0 < w → w ≤ N → M7.DefaultQuery.valid N q → ∀ x : M7.FinalSelector.Index N w q, M7.FinalSelector.win q x = true ↔ M7.FinalSelector.RawWinner w q (M7.FinalSelector.realize q x)) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), 0 < w → w ≤ N → M7.DefaultQuery.valid N q → ∀ c : M7.Action.Recipe N, M7.FinalSelector.RawWinner w q c ↔ ∃ x : M7.FinalSelector.Index N w q, M7.FinalSelector.win q x = true ∧ M7.FinalSelector.realize q x = c) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), 0 < w → w ≤ N → M7.DefaultQuery.valid N q → ∀ c : M7.Action.Recipe N, M7.FinalSelector.RawWinner w q c ↔ ∃! x : M7.FinalSelector.Index N w q, M7.FinalSelector.present q x = true ∧ M7.FinalSelector.realize q x = c) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), 0 < w → w ≤ N → M7.DefaultQuery.valid N q → ((∀ x : M7.FinalSelector.Index N w q, M7.FinalSelector.win q x = false) ↔ ¬ ∃ c : M7.Action.Recipe N, M7.FinalSelector.RawFeasible w q c)) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), 0 < w → w ≤ N → M7.DefaultQuery.valid N q → ∀ c : M7.Action.Recipe N, M7.FinalSelector.RawFeasible w q c → ¬ M7.FinalSelector.RawWinner w q c → ∃ d : M7.Action.Recipe N, M7.FinalSelector.RawWinner w q d ∧ M7.Selection.better q.order (M7.DefaultQuery.objective q d) (M7.DefaultQuery.objective q c)) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), (¬ M7.DefaultQuery.valid N q) → (∀ x : M7.FinalSelector.Index N w q, M7.FinalSelector.answer q x = Except.error M7.DefaultQuery.QueryError.invalidSignature) ∧ (¬ ∃ c : M7.Action.Recipe N, M7.FinalSelector.RawFeasible w q c)) ∧
  (∀ (N : ℕ) [NeZero N] (q : M7.DefaultQuery.Query) (base placed : M7.Action.Recipe N), (q.sectorMode = M7.DefaultQuery.SectorMode.classSector → (M7.DefaultQuery.sectorTest q base placed ↔ ∃ g : M7.Action.Record N, M7.DefaultQuery.allows q (M7.DefaultQuery.signature (M7.Action.act g base)))) ∧ (q.sectorMode = M7.DefaultQuery.SectorMode.placementSector → (M7.DefaultQuery.sectorTest q base placed ↔ M7.DefaultQuery.allows q (M7.DefaultQuery.signature placed)))) ∧
  (∀ (N : ℕ) [NeZero N] (q : M7.DefaultQuery.Query) (base placed : M7.Action.Recipe N), (M7.DefaultQuery.needsDistance q → M7.DefaultQuery.distance placed = none → ¬ M7.DefaultQuery.feasible q base placed) ∧ (q.distanceFloor = none → M7.DefaultQuery.Coordinate.negativeDistance ∉ q.objectives → (M7.DefaultQuery.feasible q base placed ↔ M7.DefaultQuery.valid N q ∧ M7.DefaultQuery.dimension placed ∈ q.dimensions ∧ M7.DefaultQuery.sectorTest q base placed ∧ (match q.localityCap with | none => True | some cap => M7.DefaultQuery.locality placed ≤ cap) ∧ (match q.radiusCap with | none => True | some cap => M7.DefaultQuery.radius placed ≤ cap)))) ∧
  (∀ (N : ℕ) [NeZero N] (q : M7.DefaultQuery.Query) (base : M7.Action.Recipe N), q.objectives = [] → M7.DefaultQuery.winners q base = M7.Selection.feasibleSet Finset.univ (fun g : M7.Action.Record N => M7.DefaultQuery.feasible q base (M7.Action.act g base))) ∧
  (∀ (N : ℕ) [NeZero N] (g h : M7.Action.Record N), (M7.ActualPresentation.encode g ≤ M7.ActualPresentation.encode h ↔ (g.unit : ZMod N).val < (h.unit : ZMod N).val ∨ (g.unit : ZMod N).val = (h.unit : ZMod N).val ∧ (g.exchange < h.exchange ∨ g.exchange = h.exchange ∧ (g.leftShift.val < h.leftShift.val ∨ g.leftShift.val = h.leftShift.val ∧ g.rightShift.val ≤ h.rightShift.val)))) ∧
  (∀ (N : ℕ) [NeZero N] (c q : M7.Action.Recipe N), (∀ g : M7.Action.Record N, M7.ActualPresentation.leastAction c q = some g ↔ M7.Action.act g c = q ∧ ∀ h : M7.Action.Record N, M7.Action.act h c = q → M7.ActualPresentation.encode g ≤ M7.ActualPresentation.encode h) ∧ (M7.ActualPresentation.leastAction c q = none ↔ ¬ ∃ g : M7.Action.Record N, M7.Action.act g c = q)) ∧
  (∀ (N : ℕ) [NeZero N] (c : M7.Action.Recipe N) (m : ℕ) (feasible : M7.Action.Recipe N → Prop) (objective : M7.Action.Recipe N → Fin m → ℤ) (mode : M7.Selection.Mode) (g : M7.Action.Record N), g ∈ M7.ActualPresentation.selected c feasible objective mode → ∃! h : M7.Action.Record N, M7.ActualPresentation.present c feasible objective mode h ∧ M7.Action.act h c = M7.Action.act g c)

/-- Exact frozen original-scope clauses; no correctness proposition is an input. -/
noncomputable def PhysicalLabels : Prop :=
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → ∀ i : Fin (M7.GeneratedFamily.size N w E), M6.Final.PointwiseCorrect N (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).1) (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).2)) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → ∀ (i : Fin (M7.GeneratedFamily.size N w E)) (g : M7.Action.Record N), (M7.DefaultQuery.dimension (M7.Action.act g (M7.GeneratedFamily.family N w E i)), M7.DefaultQuery.distance (M7.Action.act g (M7.GeneratedFamily.family N w E i))) = M7.QualityTable.cache (M7.GeneratedFamily.family N w E i)) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → ∀ (i : Fin (M7.GeneratedFamily.size N w E)) (g : M7.Action.Record N), (M7.QualityTable.leftTable (M7.GeneratedFamily.family N w E i) (g.unit,g.exchange)).size = N ∧ (M7.QualityTable.rightTable (M7.GeneratedFamily.family N w E i) (g.unit,g.exchange)).size = N ∧ M7.QualityTable.placedScores (M7.GeneratedFamily.family N w E i) g = (M7.DefaultQuery.locality (M7.Action.act g (M7.GeneratedFamily.family N w E i)), M7.DefaultQuery.radius (M7.Action.act g (M7.GeneratedFamily.family N w E i)))) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → ∀ (i : Fin (M7.GeneratedFamily.size N w E)) (g : M7.Action.Record N) (d k : ℕ) (v : M6.Pinned.Vector (2*N)), M6.ActualTransfer.solve N (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).1) (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).2) = some (d,v,k) → M7.Transport.distance (M7.Action.act g (M7.GeneratedFamily.family N w E i)) = some d ∧ M7.Transport.Xmap g v ∈ M7.Transport.LX (M7.Action.act g (M7.GeneratedFamily.family N w E i)) ∧ M6.Pinned.weight (M7.Transport.Xmap g v) = d ∧ M6.Flatten.J N (M7.Transport.Xmap g v) ∈ M7.Transport.LZ (M7.Action.act g (M7.GeneratedFamily.family N w E i)) ∧ M6.Pinned.weight (M6.Flatten.J N (M7.Transport.Xmap g v)) = d ∧ k ≤ 2*N)

/-- Exact frozen original-scope clauses; no correctness proposition is an input. -/
noncomputable def Replay : Prop :=
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), ∀ c : M7.FinalReplay.Certificate N w q, (M7.FinalReplay.check q c = Except.ok true ↔ M7.DefaultQuery.valid N q ∧ M7.GenerationReplay.check w (M7.QuerySectors.effective N q) c.generation = true ∧ M7.FactorReplay.check (M6.Cyclic.modulus N) c.factors = true ∧ c.generation.finalBases = (M7.CompactGeneration.generate (N := N) w (M7.QuerySectors.effective N q)).finalBases ∧ (∀ i, M7.LabelReplay.check (M7.FinalSelector.family N w q i) (c.labels i) = true) ∧ M7.QueryCertificate.check q (M7.FinalSelector.family N w q) c.query = Except.ok true)) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), 0 < w → w ≤ N → M7.DefaultQuery.valid N q → ∃ c : M7.FinalReplay.Certificate N w q, M7.FinalReplay.check q c = Except.ok true) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), 0 < w → w ≤ N → ∀ c : M7.FinalReplay.Certificate N w q, M7.FinalReplay.check q c = Except.ok true → c.query.winners = M7.GlobalQuery.winners q (M7.FinalSelector.family N w q) ∧ c.query.presentations = M7.QueryCertificate.allPresentations q (M7.FinalSelector.family N w q)) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), 0 < w → w ≤ N → ∀ c : M7.FinalReplay.Certificate N w q, M7.FinalReplay.check q c = Except.ok true → ∀ y : M7.Action.Recipe N, M7.FinalSelector.RawWinner w q y ↔ ∃ x ∈ c.query.winners, M7.FinalSelector.realize q x = y) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), 0 < w → w ≤ N → ∀ c : M7.FinalReplay.Certificate N w q, M7.FinalReplay.check q c = Except.ok true → ∀ y : M7.Action.Recipe N, M7.FinalSelector.RawWinner w q y ↔ ∃! x : M7.FinalSelector.Index N w q, x ∈ c.query.presentations ∧ M7.FinalSelector.realize q x = y) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), 0 < w → w ≤ N → ∀ c : M7.FinalReplay.Certificate N w q, M7.FinalReplay.check q c = Except.ok true → ∀ i : Fin (M7.GeneratedFamily.size N w (M7.QuerySectors.effective N q)), ((c.labels i).answer = none ↔ (M7.RecipeSignature.signature (M7.FinalSelector.family N w q i)).natDegree = 0) ∧ (∀ (d k : ℕ) (v : M6.Pinned.Vector (2*N)), (c.labels i).answer = some (d,v,k) → M7.DefaultQuery.distance (M7.FinalSelector.family N w q i) = some d ∧ v ∈ M7.Transport.LX (M7.FinalSelector.family N w q i) ∧ M6.Pinned.weight v = d ∧ M6.Flatten.J N v ∈ M7.Transport.LZ (M7.FinalSelector.family N w q i) ∧ M6.Pinned.weight (M6.Flatten.J N v) = d ∧ k ≤ 2*N)) ∧
  (∀ (N w : ℕ) [NeZero N] (q : M7.DefaultQuery.Query), ¬ M7.DefaultQuery.valid N q → ∀ c : M7.FinalReplay.Certificate N w q, M7.FinalReplay.check q c = Except.error M7.DefaultQuery.QueryError.invalidSignature) ∧
  (∀ (N : ℕ) [NeZero N] (w : ℕ) (E : Finset M5.BinaryPolynomial), M7.PrefixSector.ValidSector N E → M7.GenerationReplay.check w E (M7.CompactGeneration.generate (N := N) w E) = true) ∧
  (∀ (N : ℕ) [NeZero N] (w : ℕ) (E : Finset M5.BinaryPolynomial), M7.PrefixSector.ValidSector N E → 0 < w → ∀ o : M7.CompactGeneration.Output N, M7.GenerationReplay.check w E o = true → M7.RecoveryInstance.GoodBases w o.finalBases ∧ M7.GenerationReplay.FreshFrom w E ∅ o.emitted ∧ (o.emitted.map (fun e => e.representative)).Nodup ∧ (∀ y ∈ M7.RecoveryPrefix.completed N w E [], y ∈ M7.OrbitResidual.covered o.finalBases) ∧ (∀ c : M7.Action.Recipe N, M7.RawCoverage.Queried w E c → M7.CanonicalOuter.canonical c ∈ o.finalBases ∧ ∃ b ∈ o.finalBases, ∃ g : M7.Action.Record N, M7.Action.act g b = c)) ∧
  (∀ (N : ℕ) [NeZero N] (c : M7.Action.Recipe N) (d : ℕ) (P : M6.Pinned.Pins (2*N)) (xs : List (Fin (2*N))), (M7.LabelReplay.endpoint P (M7.LabelReplay.trace c d P xs), M7.LabelReplay.queryCount (M7.LabelReplay.trace c d P xs)) = M6.Pinned.recover (fun P => (M7.LabelReplay.Q c P).coeff d) P xs) ∧
  (∀ (N : ℕ) [NeZero N] (c : M7.Action.Recipe N) (r : M7.LabelReplay.Certificate N), M7.LabelReplay.check c r = true → r.signature = M7.RecipeSignature.signature c ∧ (∀ i : Fin (2*N+1), r.coefficients i = (M7.LabelReplay.Q c (M6.Pinned.free (2*N))).coeff i.val) ∧ r.answer = M6.ActualTransfer.solve N (M7.Supports.polynomial c.1) (M7.Supports.polynomial c.2) ∧ r.pins = M7.LabelReplay.pinData c) ∧
  (∀ (N : ℕ) [NeZero N] (c : M7.Action.Recipe N), M7.LabelReplay.check c (M7.LabelReplay.expected c) = true) ∧
  (∀ (N w : ℕ) [NeZero N] (c : M7.Action.Recipe N) (r : M7.LabelReplay.Certificate N), c.1.card = w → c.2.card = w → (0 : ZMod N) ∈ c.1 → (0 : ZMod N) ∈ c.2 → M7.Connectivity.connected c → M7.LabelReplay.check c r = true → (r.answer = none ↔ (M7.RecipeSignature.signature c).natDegree = 0) ∧ (∀ (d k : ℕ) (v : M6.Pinned.Vector (2*N)), r.answer = some (d,v,k) → M7.DefaultQuery.distance c = some d ∧ v ∈ M7.Transport.LX c ∧ M6.Pinned.weight v = d ∧ M6.Flatten.J N v ∈ M7.Transport.LZ c ∧ M6.Pinned.weight (M6.Flatten.J N v) = d ∧ k ≤ 2*N)) ∧
  (∀ (n : ℕ) (p : M7.FactorReplay.BP), p ∈ M7.FactorReplay.pool n ↔ p.natDegree ≤ n) ∧
  (∀ p : M7.FactorReplay.BP, M7.FactorReplay.irreducibleCheck p = true ↔ p.Monic ∧ Irreducible p) ∧
  (∀ (F : M7.FactorReplay.BP) (factors : List (M7.FactorReplay.BP × ℕ)), M7.FactorReplay.check F factors = true ↔ (factors.map Prod.fst).Nodup ∧ (∀ t ∈ factors, t.1.Monic ∧ Irreducible t.1 ∧ 0 < t.2) ∧ M7.FactorReplay.product factors = F) ∧
  (∀ F : M7.FactorReplay.BP, F.Monic → M7.FactorReplay.check F (M7.FactorReplay.expected F) = true)

/-- Exact frozen original-scope clauses; no correctness proposition is an input. -/
noncomputable def Resources : Prop :=
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → (M7.CompactGeneration.generate (N := N) w E).finalBases.card = M7.GeneratedFamily.size N w E ∧ (M7.GenerationCalls.generateMeasured (N := N) w E).2.root + (M7.GenerationCalls.generateMeasured (N := N) w E).2.children = (1 + M7.GeneratedFamily.size N w E * (2*M7.PrefixBits.depth N+1)) ∧ (M7.GenerationCalls.generateMeasured (N := N) w E).2.orbitCounts ≤ M7.GeneratedFamily.size N w E*(1 + M7.GeneratedFamily.size N w E * (2*M7.PrefixBits.depth N+1))) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → M7.CompactStorage.storedCoreBits N (M7.GeneratedFamily.size N w E) ≤ 16*(M7.GeneratedFamily.size N w E)*N ∧ M7.CompactStorage.storedWithTablesBits N (M7.GeneratedFamily.size N w E) ≤ 16*(M7.GeneratedFamily.size N w E)*N + 2*(M7.GeneratedFamily.size N w E)*Nat.totient N*N) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → M7.FinalResources.distanceWork N w E ≤ 50000*N^3 * (∑ i : Fin (M7.GeneratedFamily.size N w E), 4^(M6.ActualTransfer.span (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).1) (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).2))) ∧ ∀ i : Fin (M7.GeneratedFamily.size N w E), M6.ActualTransfer.actualSolveStorage N (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).1) (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).2) ≤ 16384*N^2*2^(M6.ActualTransfer.span (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).1) (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).2))) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → ∀ (d k : Fin (M7.GeneratedFamily.size N w E) → ℕ) (v : Fin (M7.GeneratedFamily.size N w E) → M6.Pinned.Vector (2*N)), (∀ i, M6.ActualTransfer.solve N (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).1) (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).2) = some (d i,v i,k i)) → (∑ i : Fin (M7.GeneratedFamily.size N w E), M6.ActualTransfer.actualWitnessWork N (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).1) (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).2) (k i)) ≤ 200000*N^4 * (∑ i : Fin (M7.GeneratedFamily.size N w E), 4^(M6.ActualTransfer.span (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).1) (M7.Supports.polynomial (M7.GeneratedFamily.family N w E i).2)))) ∧
  (∀ (H N : ℕ) [NeZero N] (q : M7.DefaultQuery.Query) (bases : M7.GlobalQuery.Family H N), ∀ (x : M7.GlobalQuery.Index H N) (j : Fin q.objectives.length), 1 + (M7.GlobalQuery.objective q bases x j).natAbs.size ≤ M7.FinalResources.objectiveBits q bases) ∧
  (∀ (N w : ℕ) [NeZero N] (E : Finset M5.BinaryPolynomial), 0 < w → w ≤ N → M7.PrefixSector.ValidSector N E → ∀ q : M7.DefaultQuery.Query, M7.FinalResources.comparisonCharge q (M7.GeneratedFamily.family N w E) ≤ 2 * ((M7.GeneratedFamily.size N w E) * (2*Nat.totient N*N^2))^2 * (q.objectives.length+1) * M7.FinalResources.objectiveBits q (M7.GeneratedFamily.family N w E)) ∧
  (∀ (N w : ℕ) (A B WA WB : Finset ℕ), 0 < N → w ≤ N → M7.PrefixCompleted.Base N A B WA WB → ∀ F : M5.BinaryPolynomial, F.Monic → F ∣ M5.cyclicModulus N → M7.ScalarWork.prefixWork N w F A B WA WB ≤ 1024 * N^4 * M7.ArithmeticLoops.divisorCount N * 2^(M7.ArithmeticLoops.factorCount N + N)) ∧
  (∀ (N w : ℕ) (A B WA WB : Finset ℕ), 0 < N → w ≤ N → M7.PrefixCompleted.Base N A B WA WB → ∀ E : Finset M5.BinaryPolynomial, M7.PrefixSector.ValidSector N E → M7.ScalarWork.sector N w E A B WA WB ≤ 1024 * N^4 * E.card * M7.ArithmeticLoops.divisorCount N * 2^(M7.ArithmeticLoops.factorCount N + N)) ∧
  (∀ (N : ℕ) [NeZero N], M7.ScalarWork.maskPositions N = 4 * Fintype.card ((ZMod N)ˣ) * N^2) ∧
  (∀ (N : ℕ) [NeZero N] (w : ℕ) (E : Finset M5.BinaryPolynomial) (bases : Finset (M7.Action.Recipe N)), M7.CompactStorage.Valid (M7.CompactGeneration.emission w E bases)) ∧
  (∀ (N : ℕ) [NeZero N] (e f : M7.CompactGeneration.Emission N), M7.CompactStorage.Valid e → M7.CompactStorage.Valid f → M7.CompactStorage.encode e = M7.CompactStorage.encode f → M7.CompactStorage.coreView e = M7.CompactStorage.coreView f) ∧
  (∀ (N : ℕ) [NeZero N] (e : M7.CompactGeneration.Emission N) (u : (ZMod N)ˣ) (F : M5.BinaryPolynomial), F.natDegree ≤ N → (M7.CompactStorage.unitTable e u = M7.CompactStorage.polynomialBits N F ↔ M7.RecipeSignature.signature (M7.Action.act (⟨u,false,0,0⟩ : M7.Action.Record N) e.representative) = F)) ∧
  (∀ (N H : ℕ) [NeZero N], M7.CompactStorage.coreBits N = 12*N+4 ∧ M7.CompactStorage.coreBits N ≤ 16*N ∧ M7.CompactStorage.tableBits N = Nat.totient N*(N+1) ∧ M7.CompactStorage.storedCoreBits N H ≤ 16*H*N ∧ M7.CompactStorage.storedWithTablesBits N H ≤ 16*H*N + 2*H*Nat.totient N*N) ∧
  (∀ (N : ℕ) [NeZero N] (w : ℕ) (E : Finset M5.BinaryPolynomial), (M7.GenerationCalls.generateMeasured (N := N) w E).1 = (M7.CompactGeneration.generate (N := N) w E) ∧ (M7.GenerationCalls.generateMeasured (N := N) w E).2.root + (M7.GenerationCalls.generateMeasured (N := N) w E).2.children = (1 + (M7.CompactGeneration.generate (N := N) w E).emitted.length * (2 * M7.PrefixBits.depth N + 1)) ∧ (M7.GenerationCalls.generateMeasured (N := N) w E).2.orbitCounts ≤ (M7.CompactGeneration.generate (N := N) w E).finalBases.card * (1 + (M7.CompactGeneration.generate (N := N) w E).emitted.length * (2 * M7.PrefixBits.depth N + 1))) ∧
  (∀ (H N : ℕ) [NeZero N] (q : M7.DefaultQuery.Query) (bases : M7.GlobalQuery.Family H N), ∀ x : M7.GlobalQuery.Index H N, (M7.StreamingCost.streamWin q bases x).result = M7.StreamingIndices.streamWin q bases x ∧ (M7.StreamingCost.streamWin q bases x).outer = 0 ∧ (M7.StreamingCost.streamWin q bases x).inner ≤ (H * M7.StreamingCost.recordCount N)) ∧
  (∀ (H N : ℕ) [NeZero N] (q : M7.DefaultQuery.Query) (bases : M7.GlobalQuery.Family H N), (M7.StreamingCost.scanWins q bases).outer ≤ (H * M7.StreamingCost.recordCount N) ∧ (M7.StreamingCost.scanWins q bases).inner ≤ (H * M7.StreamingCost.recordCount N)^2) ∧
  (∀ (N : ℕ) [NeZero N], M7.StreamingCost.recordCount N = Fintype.card (M7.Action.Record N) ∧ M7.StreamingCost.recordCount N = 2 * Nat.totient N * N^2) ∧
  (∀ (m : ℕ) (mode : M7.Selection.Mode) (a b : Fin m → ℤ), (M7.ObjectiveComparison.compare mode a b).1 = true ↔ M7.Selection.better mode a b) ∧
  (∀ (m : ℕ) (mode : M7.Selection.Mode) (a b : Fin m → ℤ), (M7.ObjectiveComparison.compare mode a b).2 ≤ 2*m ∧ (M7.ObjectiveComparison.compare mode a b).2 ≤ 2*(m+1))

/-- Exact frozen original-scope clauses; no correctness proposition is an input. -/
noncomputable def PresentationExtensions : Prop :=
  (∀ (α : Type) (m : ℕ) (T : Finset α) (feasible : α → Prop) (objective : α → Fin m → ℤ) (mode : M7.Selection.Mode), (∀ x, x ∈ M7.Selection.select T feasible objective mode ↔ x ∈ T ∧ feasible x ∧ ∀ y ∈ T, feasible y → ¬ M7.Selection.better mode (objective y) (objective x)) ∧ (M7.Selection.select T feasible objective mode = ∅ ↔ M7.Selection.feasibleSet T feasible = ∅)) ∧
  (∀ (α : Type) (m : ℕ) (T : Finset α) (feasible : α → Prop) (objective : α → Fin m → ℤ) (mode : M7.Selection.Mode), ∀ x ∈ T, feasible x → x ∉ M7.Selection.select T feasible objective mode → ∃ y ∈ M7.Selection.select T feasible objective mode, M7.Selection.better mode (objective y) (objective x)) ∧
  (∀ (α : Type) (T : Finset α) (feasible : α → Prop) (objective : α → Fin 0 → ℤ) (mode : M7.Selection.Mode), M7.Selection.select T feasible objective mode = M7.Selection.feasibleSet T feasible) ∧
  (∀ (N : ℕ) [NeZero N] (c : M7.Action.Recipe N) (m : ℕ) (feasible : M7.Action.Recipe N → Prop) (objective : M7.Action.Recipe N → Fin m → ℤ) (mode : M7.Selection.Mode) (g h : M7.Action.Record N), M7.Action.act g c = M7.Action.act h c → (g ∈ M7.ActualPresentation.selected c feasible objective mode ↔ h ∈ M7.ActualPresentation.selected c feasible objective mode)) ∧
  (∀ (N : ℕ) [NeZero N] (c : M7.Action.Recipe N) (m : ℕ) (feasible : M7.Action.Recipe N → Prop) (objective : M7.Action.Recipe N → Fin m → ℤ) (mode : M7.Selection.Mode) (g : M7.Action.Record N), M7.ActualPresentation.present c feasible objective mode g → g ∈ M7.ActualPresentation.selected c feasible objective mode ∧ ∀ h : M7.Action.Record N, M7.Action.act h c = M7.Action.act g c → M7.ActualPresentation.encode g ≤ M7.ActualPresentation.encode h)

noncomputable def OriginalM7 : Prop :=
  ActionSignature ∧ Canonical ∧ Generation ∧ Selector ∧ PhysicalLabels ∧ Replay ∧ Resources ∧ PresentationExtensions
end M7.Final
