import M7PrefixOrbit
def target_0 : Prop := ∀ (N : ℕ) [NeZero N], ∀ (A B WA WB : Finset ℕ) (y : M7.Action.Recipe N), M7.PrefixCompleted.Base N A B WA WB → M7.PrefixOrbit.Within A WA y.1 → M7.PrefixOrbit.Within B WB y.2 → (0 : ZMod N) ∈ y.1 ∧ (0 : ZMod N) ∈ y.2
def target_1 : Prop := ∀ (N : ℕ) [NeZero N], ∀ y : M7.Action.Recipe N, M7.Domain.connectivityGcd y.1 y.2 = M5.Connectivity.supportGcd N (M7.ResiduePrefix.encode y.1) (M7.ResiduePrefix.encode y.2)
def target_2 : Prop := ∀ (N : ℕ) [NeZero N], ∀ (w : ℕ) (E : Finset M5.BinaryPolynomial) (A B WA WB : Finset ℕ), M7.PrefixCompleted.Base N A B WA WB → ∀ y : M7.Action.Recipe N, y ∈ M7.ResiduePrefix.completed N w E A B WA WB ↔ M7.PrefixOrbit.ClassValid w y ∧ M7.RecipeSignature.signature y ∈ E ∧ M7.PrefixOrbit.Within A WA y.1 ∧ M7.PrefixOrbit.Within B WB y.2
def target_3 : Prop := ∀ (N : ℕ) [NeZero N], ∀ (w : ℕ) (c : M7.Action.Recipe N) (g : M7.Action.Record N), M7.PrefixOrbit.ClassValid w c → M7.PrefixOrbit.ClassValid w (M7.Action.act g c)
def target_4 : Prop := ∀ (N : ℕ) [NeZero N], ∀ (w : ℕ) (E : Finset M5.BinaryPolynomial) (A B WA WB : Finset ℕ), M7.PrefixCompleted.Base N A B WA WB → ∀ c : M7.Action.Recipe N, M7.PrefixOrbit.ClassValid w c → M7.PrefixOrbit.orbitCount E A B WA WB c = M7.ActualOrbit.distinctCount c (fun y => y ∈ M7.ResiduePrefix.completed N w E A B WA WB)
def target_5 : Prop := ∀ (N : ℕ) [NeZero N], ∀ (w : ℕ) (E : Finset M5.BinaryPolynomial) (A B WA WB : Finset ℕ), M7.PrefixSector.ValidSector N E → M7.PrefixCompleted.Base N A B WA WB → ∀ bases : Finset (M7.Action.Recipe N), (∀ c ∈ bases, M7.PrefixOrbit.ClassValid w c) → M7.PrefixOrbit.residual w E A B WA WB bases = M7.OrbitResidual.subtraction (M7.ResiduePrefix.completed N w E A B WA WB) bases
def target_6 : Prop := ∀ (N : ℕ) [NeZero N], ∀ (w : ℕ) (E : Finset M5.BinaryPolynomial) (A B WA WB : Finset ℕ), M7.PrefixSector.ValidSector N E → M7.PrefixCompleted.Base N A B WA WB → ∀ bases : Finset (M7.Action.Recipe N), (∀ c ∈ bases, M7.PrefixOrbit.ClassValid w c) → M7.CanonicalClasses.Normalized bases → M7.PrefixOrbit.residual w E A B WA WB bases = (M7.OrbitResidual.remaining (M7.ResiduePrefix.completed N w E A B WA WB) bases).card
def target_7 : Prop := ∀ (N : ℕ) [NeZero N], ∀ (w : ℕ) (E : Finset M5.BinaryPolynomial) (A B WA WB : Finset ℕ), M7.PrefixSector.ValidSector N E → M7.PrefixCompleted.Base N A B WA WB → ∀ bases : Finset (M7.Action.Recipe N), (∀ c ∈ bases, M7.PrefixOrbit.ClassValid w c) → M7.CanonicalClasses.Normalized bases → 0 ≤ M7.PrefixOrbit.residual w E A B WA WB bases ∧ (0 < M7.PrefixOrbit.residual w E A B WA WB bases ↔ ∃ y ∈ M7.ResiduePrefix.completed N w E A B WA WB, y ∉ M7.OrbitResidual.covered bases)
def target_8 : Prop := ∀ (N : ℕ) [NeZero N], ∀ (w : ℕ) (E : Finset M5.BinaryPolynomial) (A B WA WB : Finset ℕ), M7.PrefixCompleted.Base N A B WA WB → ∀ y ∈ M7.ResiduePrefix.completed N w E A B WA WB, M7.PrefixOrbit.ClassValid w (M7.CanonicalOuter.canonical y)
