import Mathlib
import IChO2026Chem

/-!
# IChO 2026 T9-A6: constitutional isomers of a β-cyclodextrin dimer

The source asks for constitutional linkage isomers, not stereoisomers.  A
β-cyclodextrin is represented as a seven-unit cyclic α-1,4-linked molecule
with an explicitly non-superimposable mirror stereochemical descriptor.  For
the displayed synthesis, the official rubric identifies the two monomer
regioisomers as M-1R and M-4R.  Thus the source-specific attachment positions
are units 1 and 4; the general unit-3 fallback does not occur in this dimer.

`Sym2` is Mathlib's type of unordered pairs.  It records the chemical fact
that a linkage from the first macrocycle at position `i` to the second at
position `j` is the same constitutional linkage as the exchanged pair.
-/

namespace IChO2026Problems.T9A6

/-- The α-D-glucopyranoside units from which cyclodextrins are formed. -/
private inductive AlphaDGlucopyranosideUnit where
  | mk
  deriving DecidableEq, Repr

/-- The α-1,4 glycosidic linkage specified for cyclodextrins in T9. -/
private inductive GlycosidicLinkage where
  | alphaOneFour
  deriving DecidableEq, Repr

/-- An abstract absolute configuration at a stereogenic centre. -/
private inductive TetrahedralConfiguration where
  | R
  | S
  deriving DecidableEq, Repr

/-- Mirror reflection exchanges the two absolute configurations. -/
private def mirrorConfiguration : TetrahedralConfiguration → TetrahedralConfiguration
  | .R => .S
  | .S => .R

/-- A stereochemical descriptor is chiral when it differs from its mirror.
This is the only stereochemical feature used here: the requested count is of
constitutional linkage isomers, so no mirror-image products are identified. -/
private def IsChiral (configuration : Fin 7 → TetrahedralConfiguration) : Prop :=
  configuration ≠ fun unit => mirrorConfiguration (configuration unit)

/-- A β-cyclodextrin: seven α-D-glucopyranoside units in a cyclic array with
α-1,4 linkages and the chirality stated in the source. -/
private structure BetaCyclodextrin where
  glucopyranosideUnit : Fin 7 → AlphaDGlucopyranosideUnit
  linkageFromUnit : Fin 7 → GlycosidicLinkage
  all_linkages_are_alpha_one_four :
    ∀ unit, linkageFromUnit unit = .alphaOneFour
  stereochemistry : Fin 7 → TetrahedralConfiguration
  is_chiral : IsChiral stereochemistry

/-- Unit 1 of the seven-membered β-CD macrocycle, using zero-based `Fin`
indices. -/
private def unitOne : Fin 7 := ⟨0, by omega⟩

/-- Unit 4 of the seven-membered β-CD macrocycle. -/
private def unitFour : Fin 7 := ⟨3, by omega⟩

/-- The attachment positions of the two monomer regioisomers named in the
official answer: M-1R and M-4R. -/
private def sinayAttachmentPositions : Finset (Fin 7) :=
  {unitOne, unitFour}

/-- All constitutional dimer linkages generated by pairing the two permitted
attachment positions.  `Finset.sym2` forms unordered pairs, so it retains
the mixed linkage only once. -/
private def generatedDimerLinkageIsomers : Finset (Sym2 (Fin 7)) :=
  sinayAttachmentPositions.sym2

/-- A synthesis of the β-CD homodimer in the Sinay sequence.  The final field
is the source-to-Lean chemical bridge: it says that the constitutional
products are exactly those generated by the two regioselective attachment
positions, without asserting their number. -/
private structure SinayBetaCDDimerSynthesis where
  firstMacrocycle : BetaCyclodextrin
  secondMacrocycle : BetaCyclodextrin
  same_parent_stereochemistry :
    firstMacrocycle.stereochemistry = secondMacrocycle.stereochemistry
  constitutionalLinkageIsomers : Finset (Sym2 (Fin 7))
  isomers_generated_by_regioselective_alkylation :
    constitutionalLinkageIsomers = generatedDimerLinkageIsomers

/-- T9-A6.  The two permitted β-CD attachment positions give three unordered
constitutional linkage classes: 1-1, 1-4, and 4-4.  The use of `Sym2` proves
that 1-4 and 4-1 are one class. -/
theorem number_of_sinay_beta_cd_dimer_constitutional_isomers
    (synthesis : SinayBetaCDDimerSynthesis) :
    synthesis.constitutionalLinkageIsomers.card = 3 := by
  rw [synthesis.isomers_generated_by_regioselective_alkylation]
  unfold generatedDimerLinkageIsomers
  rw [Finset.card_sym2]
  norm_num [sinayAttachmentPositions, unitOne, unitFour]

end IChO2026Problems.T9A6
