import M8OptimizerResources
def M8.OptimizerTarget.distance_work : Prop := ∀ (N : ℕ) [NeZero N] (a b : M6.ActualTransfer.BP), M6.ActualTransfer.span a b ≤ M8.Cutoff.limit N → M6.ActualTransfer.actualDistanceWork N a b ≤ 50000*(N+1)^5
def M8.OptimizerTarget.witness_work : Prop := ∀ (N : ℕ) [NeZero N] (a b : M6.ActualTransfer.BP), ∀ (d : ℕ) (v : M6.Pinned.Vector (2*N)) (k : ℕ), M6.ActualTransfer.span a b ≤ M8.Cutoff.limit N → M6.ActualTransfer.solve N a b = some (d,v,k) → M6.ActualTransfer.actualWitnessWork N a b k ≤ 200000*(N+1)^6
def M8.OptimizerTarget.solve_storage : Prop := ∀ (N : ℕ) [NeZero N] (a b : M6.ActualTransfer.BP), M6.ActualTransfer.span a b ≤ M8.Cutoff.limit N → M6.ActualTransfer.actualSolveStorage N a b ≤ 16384*(N+1)^3
def M8.OptimizerTarget.weight_bounds : Prop := ∀ (N : ℕ) [NeZero N] (a b : M6.ActualTransfer.BP), ∀ (pins : M6.Pinned.Pins (2*N)) (character : Bool), ∀ i m t, M6.Transfer.polynomialMass ((M8.OptimizerResources.weight N a b pins character) i m t) ≤ 4 ∧ ((M8.OptimizerResources.weight N a b pins character) i m t).natDegree ≤ 2
def M8.OptimizerTarget.indexed_guarantee : Prop := ∀ (N : ℕ) [NeZero N] (a b : M6.ActualTransfer.BP), ∀ (pins : M6.Pinned.Pins (2*N)) (character : Bool), M6.ActualTransfer.span a b ≤ M8.Cutoff.limit N → M6.Transfer.IndexedArrayGuarantee (M6.ActualTransfer.span a b) N (M8.OptimizerResources.weight N a b pins character)
def M8.OptimizerTarget.trace_capacity : Prop := ∀ (N : ℕ) [NeZero N] (a b : M6.ActualTransfer.BP), ∀ (pins : M6.Pinned.Pins (2*N)) (character : Bool), M6.ActualTransfer.span a b ≤ M8.Cutoff.limit N → ∀ d : ℕ, ((M6.Transfer.arrayTrace (M8.OptimizerResources.weight N a b pins character) N).coeff d).natAbs ≤ 2^(M6.ActualTransfer.span a b) * 8^N ∧ ((M6.Transfer.arrayTrace (M8.OptimizerResources.weight N a b pins character) N).coeff d).natAbs < 2^(4*(N+1))
def M8.OptimizerTarget.trace_prefix_capacity : Prop := ∀ (N : ℕ) [NeZero N] (a b : M6.ActualTransfer.BP), ∀ (pins : M6.Pinned.Pins (2*N)) (character : Bool), M6.ActualTransfer.span a b ≤ M8.Cutoff.limit N → ∀ (k : ℕ) (d : Fin (2*N+1)), (((((Finset.univ : Finset (M6.Transfer.Memory (M6.ActualTransfer.span a b))).toList.take k).map (fun start => M6.Transfer.scalarLayers (N:=N) (M8.OptimizerResources.weight N a b pins character) start N (start,d))).sum)).natAbs ≤ 2^(M6.ActualTransfer.span a b) * 8^N ∧ (((((Finset.univ : Finset (M6.Transfer.Memory (M6.ActualTransfer.span a b))).toList.take k).map (fun start => M6.Transfer.scalarLayers (N:=N) (M8.OptimizerResources.weight N a b pins character) start N (start,d))).sum)).natAbs < 2^(4*(N+1))
def M8.OptimizerTarget.scatter_capacity : Prop := ∀ (N : ℕ) [NeZero N] (a b : M6.ActualTransfer.BP), ∀ (pins : M6.Pinned.Pins (2*N)) (character : Bool), M6.ActualTransfer.span a b ≤ M8.Cutoff.limit N → ∀ (start : M6.Transfer.Memory (M6.ActualTransfer.span a b)) (i : ℕ), i < N → ∀ (k : ℕ) (addr : M6.Transfer.CoefficientAddress (M6.ActualTransfer.span a b) N), (((M6.Transfer.scatterEventList (M6.ActualTransfer.span a b) N).take k).foldl (M6.Transfer.scatterUpdate ((M8.OptimizerResources.weight N a b pins character) i) (M6.Transfer.scalarLayers (N:=N) (M8.OptimizerResources.weight N a b pins character) start i)) (fun _ => 0) addr).natAbs < 2^(4*(N+1)) ∧ ∀ e : M6.Transfer.ScatterEvent (M6.ActualTransfer.span a b) N, (M6.Transfer.eventTerm ((M8.OptimizerResources.weight N a b pins character) i) (M6.Transfer.scalarLayers (N:=N) (M8.OptimizerResources.weight N a b pins character) start i) e).natAbs < 2^(4*(N+1))
