from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent;P=Path('/home/jing/m7-lean-presentation-formalization');S='M7.Presentation.'
A='∀ (κ σ τ : Type) [LinearOrder κ] [LinearOrder σ] [LinearOrder τ]';B=A+' (K : Finset κ) (L : κ → Finset σ) (R : κ → Finset τ)';C='∀ (κ σ τ X Y : Type) [LinearOrder κ] [LinearOrder σ] [LinearOrder τ] (K : Finset κ) (S : Finset σ) (T : Finset τ) (l : κ → σ → X) (r : κ → τ → Y)';D=C+' (m : ℕ) (feasible : X × Y → Prop) (objective : X × Y → Fin m → ℤ) (mode : M7.Selection.Mode)';rec=S+'Record κ σ τ';sel=S+'selected K S T l r feasible objective mode';pr=S+'present K S T l r feasible objective mode';dom=S+'domain K S T';real=S+'realize l r';target=S+'targetLeast K S T l r'
rows=[
('record_eta',[],f'∀ (κ σ τ : Type) (a : {rec}), {S}mk ({S}outer a) ({S}left a) ({S}right a) = a','The nested Lex synonym has the same underlying product. Destructure both pairs or use rfl after cases.'),
('record_mono',[],A+f' (k : κ) (s s1 : σ) (t t1 : τ), s ≤ s1 → t ≤ t1 → {S}mk k s t ≤ {S}mk k s1 t1','Use Prod.Lex.toLex_le_toLex or its partial-order variant twice. Equal outer coordinate reduces to the inner lex order; weak coordinate inequalities imply lex weak order. This proves that independent coordinate minima give the least pair.'),
('candidates_sound',[],B+f' (a : {rec}), a ∈ {S}candidates K L R → {S}valid K L R a','Unfold candidates; Finset.mem_biUnion identifies the outer k; split the nonempty test. Singleton equality identifies a with the two independent min values, whose membership follows from Finset.min\'_mem. No product traversal is in candidates.'),
('candidate_dominates',['record_eta','record_mono'],B+f' (a : {rec}), {S}valid K L R a → ∃ b ∈ {S}candidates K L R, b ≤ a','Use the outer coordinate of a, witnessing both fibers nonempty by its coordinates. Choose the candidate of their separate min\' values; membership in candidates is direct. min\'_le and record_mono give b≤mk(outer a)(left a)(right a), then record_eta.'),
('leastOf_spec',[], '∀ (α : Type) [LinearOrder α] (T : Finset α), (∀ x, '+S+'leastOf T = some x ↔ x ∈ T ∧ ∀ y ∈ T, x ≤ y) ∧ ('+S+'leastOf T = none ↔ T = ∅)','Split T.Nonempty in leastOf; Finset.min\'_mem/min\'_le give soundness. Conversely uniqueness of the minimum follows by le_antisymm. Empty case uses Finset.not_nonempty_iff_eq_empty. Handle proof-irrelevance of nonempty witnesses normally.'),
('factorLeast_spec',['leastOf_spec','candidates_sound','candidate_dominates'],B+f' (a : {rec}), {S}factorLeast K L R = some a ↔ {S}valid K L R a ∧ ∀ b, {S}valid K L R b → a ≤ b','Forward: leastOf candidate min is valid; any valid b is bounded below by a candidate c, so a≤c≤b. Reverse: choose a candidate c≤a from candidate_dominates; validity and global minimality give a≤c, hence equality and a is a candidate, then leastOf_spec. The full preimage is only a semantic predicate, never enumerated in factorLeast.'),
('factorLeast_none',['leastOf_spec','candidate_dominates','candidates_sound'],B+f', {S}factorLeast K L R = none ↔ ¬ ∃ a : {rec}, {S}valid K L R a','leastOf none iff candidates empty. Any valid record yields a candidate, and any candidate is valid; combine the two implications. Covers empty outer domain and every empty single-block fiber.'),
('domain_membership',['record_eta'],f'∀ (κ σ τ : Type) (K : Finset κ) (S : Finset σ) (T : Finset τ) (a : {rec}), a ∈ {dom} ↔ {S}outer a ∈ K ∧ {S}left a ∈ S ∧ {S}right a ∈ T','Unfold domain and use biUnion/image/product membership. In the reverse direction choose the actual two coordinates and record_eta. This domain enumerates action records for selection, permitted by the original source; factorLeast never calls it.'),
('targetLeast_spec',['factorLeast_spec','factorLeast_none','domain_membership'],C+f' (q : X × Y), (∀ a : {rec}, {target} q = some a ↔ a ∈ {dom} ∧ {real} a = q ∧ ∀ b ∈ {dom}, {real} b = q → a ≤ b) ∧ ({target} q = none ↔ ¬ ∃ a ∈ {dom}, {real} a = q)','Instantiate factorLeast with the separately filtered left and right image fibers. Prove their valid predicate iff domain membership and equality of the realized pair using Prod.ext and filter membership. Then rewrite the two accepted exact factorLeast results; do not add a Cartesian scan to the algorithm definition.'),
('winning_fiber',[],D+f' (a b : {rec}), a ∈ {dom} → b ∈ {dom} → {real} a = {real} b → (a ∈ {sel} ↔ b ∈ {sel})','The actual selected definition invokes M7.Selection.select. Use accepted selector_exact or unfold the literal win predicate. Feasibility and every objective coordinate depend on realize, so equal images give identical comparisons. No free Win-invariance or correctness oracle is assumed.'),
('presentation_exact',['targetLeast_spec','winning_fiber'],D+f' (a : {rec}), a ∈ {sel} → ∃! b : {rec}, {pr} b ∧ {real} b = {real} a','A winning a lies in domain by actual selector_exact. targetLeast at its image cannot be none by targetLeast_spec; obtain its unique least preimage b. It is winning by winning_fiber, so present. Any other present record with the same image yields the same targetLeast Option value, hence equality. This is every tied physical presentation exactly once.'),
('presentation_sound',['targetLeast_spec'],D+f' (a : {rec}), {pr} a → a ∈ {sel} ∧ a ∈ {dom} ∧ ∀ b ∈ {dom}, {real} b = {real} a → a ≤ b','Unfold present. Its first conjunct is actual winning membership; its concrete targetLeast equality gives domain membership and minimality via targetLeast_spec. All returned presentations are winners and the least action preimage.')]
nodes=[{'id':i,'dependencies':ds,'spec':{'name':S+i,'statement':st,'imports':['M7Presentation','M7SelectionAccepted'],'context':'','queries':['finite set minimum lexicographic order'],'guidance':gd+' Return tactic proof lines without leading by; preserve exact target and default limits.'},'metadata':{'source_section':'M7 original §9 factorized least preimages and all physical ties','fallback_queries':['finite strict order minimal element']}} for i,ds,st,gd in rows]
source=Path('/home/jing/quantum_code_discovery_proof/research_checkpoints/m7_compact_selector_final_20260915/PROOF.md');g={'title':'M7 factorized least-preimage reconstruction and actual winning presentation deduplication','source':str(source),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'scope':'Separate single-block minima then outer minimum; actual Pareto/lex winners descend to exactly one record per realized winning presentation. Concrete action encoding bridge remains parent integration.','nodes':nodes};(H/'graph.json').write_text(json.dumps(g,ensure_ascii=False,indent=2)+'\n')
s='import M7Presentation\nimport M7SelectionAccepted\n\n'
for i,ds,st,gd in rows:s+='noncomputable def M7.PresentationTarget.'+i+' : Prop :=\n  '+st+'\n\n#check M7.PresentationTarget.'+i+'\n\n'
for d in [H/'lean',P]:(d/'GraphPreflight.lean').write_text(s)
