import M6FinalReady
#print axioms M6.Coordinates.block_coeff
#print axioms M6.Coordinates.block_degree
#print axioms M6.Coordinates.block_reconstruct
#print axioms M6.Coordinates.encode_sum
#print axioms M6.Coordinates.modulus_monic_degree
#print axioms M6.Coordinates.root_period
#print axioms M6.Coordinates.encode_injective
#print axioms M6.Coordinates.encode_polynomial
#print axioms M6.Coordinates.encode_surjective
#print axioms M6.Coordinates.rootPow_add
#print axioms M6.Coordinates.encode_conv
#print axioms M6.BoundaryFibers.annihilator_general
#print axioms M6.BoundaryFibers.boundary_add
#print axioms M6.BoundaryFibers.kernel_iff
#print axioms M6.BoundaryFibers.nonzero_monic
#print axioms M6.BoundaryFibers.signature_nonzero
#print axioms M6.BoundaryFibers.kernel_card
#print axioms M6.BoundaryFibers.fiber_card
#print axioms M6.Flatten.flatten_add
#print axioms M6.Flatten.flatten_dot
#print axioms M6.Flatten.flatten_left
#print axioms M6.Flatten.flatten_right
#print axioms M6.Flatten.flatten_smul
#print axioms M6.Flatten.flatten_weight
#print axioms M6.Flatten.J_involution
#print axioms M6.Flatten.J_weight
#print axioms M6.Flatten.cycle_orthogonal
#print axioms M6.Spaces.boundary_eval
#print axioms M6.Spaces.dual_boundary_eval
#print axioms M6.Spaces.input_card
#print axioms M6.Spaces.boundary_words_iff
#print axioms M6.Spaces.cycle_words_iff
#print axioms M6.Spaces.boundaries_are_cycles
#print axioms M6.Spaces.dual_boundary_card
#print axioms M6.Spaces.logical_words_iff
#print axioms M6.Spaces.zero_not_logical
#print axioms M6.Character.sign_add
#print axioms M6.Character.sign_eq_one
#print axioms M6.Character.character_add
#print axioms M6.Character.sign_sum
#print axioms M6.Character.character_product
#print axioms M6.Character.orthogonality
#print axioms M6.Character.weighted_factorization
#print axioms M6.Character.weighted_macwilliams
#print axioms M6.Character.free_character_factor
#print axioms M6.Character.weight_as_sum
#print axioms M6.Character.pinned_product
#print axioms M6.Character.pinned_macwilliams
#print axioms M6.Character.constant_transform
#print axioms M6.FiberSum.sum_by_fibers
#print axioms M6.Character.dual_cardinality
#print axioms M6.FiberSum.uniform_weighted_sum
#print axioms M6.FiberSum.uniform_cardinality
#print axioms M6.Pinned.agrees_pin
#print axioms M6.Pinned.choose_properties
#print axioms M6.Pinned.count_nonnegative_positive
#print axioms M6.Pinned.decode_unique
#print axioms M6.Pinned.distance_spec
#print axioms M6.Pinned.enumerator_coeff
#print axioms M6.Pinned.recover_positive
#print axioms M6.Pinned.weight_bound
#print axioms M6.Pinned.count_pin_partition
#print axioms M6.Pinned.first_positive_distance
#print axioms M6.Pinned.recover_properties
#print axioms M6.Pinned.recover_from_counts
#print axioms M6.Pinned.solve_exact
#print axioms M6.Pinned.minimum_witness
#print axioms M6.CSS.involution_distance
#print axioms M6.CSS.logical_pauli_components
#print axioms M6.CSS.pure_weights
#print axioms M6.CSS.quantum_distance_spec
#print axioms M6.CSS.support_bounds
#print axioms M6.CSS.css_distance_min
#print axioms M6.CSS.common_quantum_distance
#print axioms M6.ActualCSS.J_boundary_iff
#print axioms M6.ActualCSS.J_dot
#print axioms M6.ActualCSS.zero_boundaries
#print axioms M6.ActualCSS.J_cycle_iff
#print axioms M6.ActualCSS.J_logical_iff
#print axioms M6.ActualCSS.Z_boundaries_are_cycles
#print axioms M6.ActualCSS.common_quantum_distance
#print axioms M6.Transfer.memory_follows
#print axioms M6.Transfer.output_convolution
#print axioms M6.Transfer.shift_coordinates
#print axioms M6.Transfer.memory_forced
#print axioms M6.Transfer.labels_bijective
#print axioms M6.Transfer.closed_walk_card
#print axioms M6.Transfer.indexed_weight_sum
#print axioms M6.Transfer.layers_matrix
#print axioms M6.Transfer.matrix_trace_cycle
#print axioms M6.Transfer.uniform_matrix_power
#print axioms M6.Transfer.array_trace_matrix
#print axioms M6.Transfer.labelled_trace
#print axioms M6.Transfer.array_trace_inputs
#print axioms M6.Transfer.layers_degree
#print axioms M6.Transfer.mass_add
#print axioms M6.Transfer.mass_basic
#print axioms M6.Transfer.mass_sum
#print axioms M6.Transfer.mass_mul
#print axioms M6.Transfer.propagate_mass
#print axioms M6.Transfer.layers_mass
#print axioms M6.Transfer.trace_coefficient_bound
#print axioms M6.Transfer.scatter_event_count
#print axioms M6.Transfer.scatter_prefix_formula
#print axioms M6.Transfer.small_polynomial_convolution
#print axioms M6.Transfer.scatter_polynomial_coeff
#print axioms M6.Transfer.scalar_layers_exact
#print axioms M6.Transfer.scalar_trace_coefficient
#print axioms M6.Transfer.scalar_trace_polynomial
#print axioms M6.Transfer.boundary_factor_bounds
#print axioms M6.Transfer.boundary_edge_bounds
#print axioms M6.Transfer.character_factor_bounds
#print axioms M6.Transfer.character_edge_bounds
#print axioms M6.Normalize.divide_coeff
#print axioms M6.Normalize.scaled_coeff_divisible
#print axioms M6.Normalize.divide_degree
#print axioms M6.Normalize.divide_scaled
#print axioms M6.ActualTransfer.left_coordinate
#print axioms M6.ActualTransfer.right_coordinate
#print axioms M6.ActualTransfer.window_conv
#print axioms M6.ActualTransfer.product_halves
#print axioms M6.ActualTransfer.boundary_input_product
#print axioms M6.ActualTransfer.character_input_product
#print axioms M6.ActualTransfer.boundary_trace_inputs
#print axioms M6.ActualTransfer.character_trace_inputs
#print axioms M6.ActualCounts.encoded_boundary
#print axioms M6.ActualCounts.finite_image_weighted_sum
#print axioms M6.ActualCounts.boundary_eq_iff
#print axioms M6.ActualCounts.boundary_fiber_card
#print axioms M6.ActualCounts.boundary_weighted_sum
#print axioms M6.ActualCounts.dual_boundary_fiber_card
#print axioms M6.ActualCounts.boundary_pinned_sum
#print axioms M6.ActualCounts.dual_weighted_sum
#print axioms M6.ActualCounts.input_normalization
#print axioms M6.ActualCounts.cycle_pinned_sum
#print axioms M6.ActualCounts.f_le_order
#print axioms M6.ActualCounts.boundary_card
#print axioms M6.ActualCounts.boundary_finrank
#print axioms M6.ActualCounts.cycle_card
#print axioms M6.ActualCounts.dual_boundary_finrank
#print axioms M6.ActualCounts.logical_card
#print axioms M6.ActualCounts.encoded_dimension
#print axioms M6.ActualCounts.logicals_nonempty_iff
#print axioms M6.ActualCounts.zero_signature_no_logicals
#print axioms M6.Pinned.enumerator_sdiff
#print axioms M6.Pinned.enumerator_total
#print axioms M6.Pinned.enumerator_zero_coeff
#print axioms M6.ActualResult.boundary_normalized
#print axioms M6.ActualResult.cycle_normalized
#print axioms M6.ActualResult.Q_enumerator
#print axioms M6.ActualResult.Q_coeff
#print axioms M6.ActualResult.Q_total
#print axioms M6.ActualResult.Q_zero
#print axioms M6.ActualResult.solve_exact
#print axioms M6.FixedSpan.distance_improvement
#print axioms M6.FixedSpan.recipe_degree
#print axioms M6.FixedSpan.recipe_divides
#print axioms M6.FixedSpan.recipe_support
#print axioms M6.FixedSpan.witness_improvement
#print axioms M6.FixedSpan.recipe_signature
#print axioms M6.FixedSpan.nontrivial_family
#print axioms M6.ZeroSpan.anchored_zero
#print axioms M6.ZeroSpan.boundary_loops
#print axioms M6.ZeroSpan.character_loops
#print axioms M6.ZeroSpan.connected_zero
#print axioms M6.ZeroSpan.signature_one
#print axioms M6.ZeroSpan.zero_memory_trace
#print axioms M6.ZeroSpan.boundary_trace_zero
#print axioms M6.ZeroSpan.character_trace_zero
#print axioms M6.Transfer.address_width
#print axioms M6.Transfer.coefficient_width
#print axioms M6.Transfer.state_count
#print axioms M6.Transfer.trace_storage_bound
#print axioms M6.Transfer.scatter_loop_count
#print axioms M6.Transfer.trace_work_bound
#print axioms M6.Transfer.actual_trace_intermediates
#print axioms M6.Transfer.finite_coefficient_mass
#print axioms M6.Transfer.encoded_array_mass
#print axioms M6.Transfer.event_mass_bound
#print axioms M6.Transfer.scatter_prefix_magnitude
#print axioms M6.Transfer.actual_layer_intermediates
#print axioms M6.Transfer.actual_signed_capacity
#print axioms M6.Transfer.actual_trace_storage_bound
#print axioms M6.Transfer.actual_trace_work_bound
#print axioms M6.Transfer.actual_address_capacity
#print axioms M6.Transfer.indexed_array_correct_resources
#print axioms M6.ActualTransfer.boundary_indexed_resources
#print axioms M6.ActualTransfer.character_indexed_resources
#print axioms M6.Transfer.paired_storage_bound
#print axioms M6.Transfer.paired_work_bound
#print axioms M6.Transfer.post_event_count
#print axioms M6.Transfer.distance_work_bound
#print axioms M6.Transfer.solve_storage_bound
#print axioms M6.Transfer.witness_work_bound
#print axioms M6.ActualTransfer.scalar_trace_support
#print axioms M6.ActualTransfer.shift_division
#print axioms M6.ActualTransfer.shifted_coefficient_exact
#print axioms M6.ActualTransfer.shifted_output_exact
#print axioms M6.ActualTransfer.shifted_scan_exact
#print axioms M6.Transfer.division_difference_fits
#print axioms M6.ActualTransfer.query_coefficients_fit
#print axioms M6.Euclid.binary_normalization
#print axioms M6.Euclid.cancel_mod
#print axioms M6.Euclid.dense_injective
#print axioms M6.Euclid.dense_rank
#print axioms M6.Euclid.rank_order
#print axioms M6.Euclid.remainder_passes
#print axioms M6.Euclid.scan_cost
#print axioms M6.Euclid.cancel_drop
#print axioms M6.Euclid.dense_cancel
#print axioms M6.Euclid.euclid_aux_passes
#print axioms M6.Euclid.normalized_gcd
#print axioms M6.Euclid.euclid_passes
#print axioms M6.Euclid.remainder_aux_correct
#print axioms M6.Euclid.remainder_safe
#print axioms M6.Euclid.remainder_correct
#print axioms M6.Euclid.euclid_aux_correct
#print axioms M6.Euclid.euclid_output_width
#print axioms M6.Euclid.euclid_safe
#print axioms M6.Euclid.euclid_correct
#print axioms M6.Euclid.bit_cost_bound
#print axioms M6.Euclid.preprocess_correct_cost
#print axioms M6.ActualTransfer.actual_solve_queries
#print axioms M6.ActualTransfer.actual_distance_work
#print axioms M6.ActualTransfer.actual_witness_work
#print axioms M6.RecipeIsometries.conv_multiply
#print axioms M6.RecipeIsometries.conv_shift
#print axioms M6.RecipeIsometries.exchange_laws
#print axioms M6.RecipeIsometries.exchange_weight
#print axioms M6.RecipeIsometries.lift_transport
#print axioms M6.RecipeIsometries.multiply_laws
#print axioms M6.RecipeIsometries.permutation_weight
#print axioms M6.RecipeIsometries.shift_laws
#print axioms M6.RecipeIsometries.exchange_isometry
#print axioms M6.RecipeIsometries.multiplied_boundary
#print axioms M6.RecipeIsometries.multiplied_syndrome
#print axioms M6.RecipeIsometries.multiplied_weight
#print axioms M6.RecipeIsometries.translated_boundary
#print axioms M6.RecipeIsometries.translated_syndrome
#print axioms M6.RecipeIsometries.translated_weight
#print axioms M6.RecipeIsometries.multiplier_isometry
#print axioms M6.RecipeIsometries.translation_isometry
#print axioms M6.EuclidStorage.control_encoding
#print axioms M6.EuclidStorage.layout_bound
#print axioms M6.EuclidStorage.rem_loop_refines
#print axioms M6.EuclidStorage.slots_encoding
#print axioms M6.EuclidStorage.control_values_fit
#print axioms M6.EuclidStorage.gcd_loop_refines
#print axioms M6.EuclidStorage.rem_loop_safe
#print axioms M6.EuclidStorage.gcd_loop_safe
#print axioms M6.EuclidStorage.gcd_start_refines
#print axioms M6.EuclidStorage.gcd_start_safe
#print axioms M6.EuclidStorage.preprocess_refines
#print axioms M6.EuclidStorage.preprocess_safe
#print axioms M6.EuclidStorage.preprocess_storage
#print axioms M6.ActualTransfer.actual_solve_storage
#print axioms M6.Transfer.complete_address_capacity
#print axioms M6.Transfer.recovery_stack_allocation
#print axioms M6.Final.answer_correct
#print axioms M6.Final.counting_correct
#print axioms M6.Final.execution_correct
#print axioms M6.Final.fixed_span_correct
#print axioms M6.Final.parameters_correct
#print axioms M6.Final.zero_span_correct
def preflight_0 : Prop := ∀ (N : ℕ) [NeZero N] (a b : M6.Final.BP), M6.Final.Admissible N a b → M6.Final.StorageCorrect N a b
def preflight_1 : Prop := M6.Final.RecipeCorrect
def preflight_2 : Prop := M6.Final.OriginalM6
