from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent;P=Path('/home/jing/m7-lean-query-rebase-formalization');S='M7.QueryRebase.';G='M7.GlobalQuery.';D='M7.DefaultQuery.';A='∀ (H N : ℕ) [NeZero N]';Q=A+f' (q : {D}Query) (bases : {G}Family H N) (moves : Fin H → M7.Action.Record N)';I=G+'Index H N';nb='('+S+'rebase bases moves)';rp=lambda x:'('+S+'reparam moves '+x+')';rz=lambda b,x:G+'realize '+b+' '+x;win=lambda b:G+'winners q '+b;pr=lambda b,x:G+'present q '+b+' '+x
rows=[
('reparameterization',[],A+f' (moves : Fin H → M7.Action.Record N), (∀ x : {I}, {S}undo moves ({S}reparam moves x) = x) ∧ (∀ x : {I}, {S}reparam moves ({S}undo moves x) = x) ∧ Function.Bijective ({S}reparam moves)','Unfold the explicit right-composition and undo with inverse. Use actual accepted Action.associative, right_inverse, left_inverse and right_identity, plus product equality. Prove injectivity and surjectivity from the two explicit inverse identities. No abstract assumed action is used.'),
('realize_reparam',[],A+f' (bases : {G}Family H N) (moves : Fin H → M7.Action.Record N) (x : {I}), {rz(nb,"x")} = {rz("bases",rp("x"))}','Unfold rebase, reparam and GlobalQuery.realize; this is exactly actual Action.act_compose, oriented symmetrically.'),
('sector_base',[],f'∀ (N : ℕ) [NeZero N] (q : {D}Query) (base placed : M7.Action.Recipe N) (g : M7.Action.Record N), ({D}sectorTest q (M7.Action.act g base) placed ↔ {D}sectorTest q base placed)','Split sectorMode. Placement-sector is identical. Class-sector existential records reparameterize by h ↦ compose h g. Reverse direction chooses compose h (inverse g), using associative, left_inverse/right_inverse, right_identity and act_compose. Keep the literal full signature predicate; no signature transport or distance-invariance theorem is required.'),
('feasible_objective',['realize_reparam','sector_base'],Q+f' (x : {I}), ({G}feasible q {nb} x ↔ {G}feasible q bases {rp("x")}) ∧ {G}objective q {nb} x = {G}objective q bases {rp("x")}','Use literal realization equality from realize_reparam. Unfold GlobalQuery.feasible/objective and DefaultQuery.feasible; every placement-dependent term is identical. Only the class-sector base changes, handled by sector_base. This retains caps, NoLogical policy and all objective coordinates without class-label invariance assumptions.'),
('winners_reparam',['reparameterization','feasible_objective'],Q+f' (x : {I}), x ∈ {win(nb)} ↔ {rp("x")} ∈ {win("bases")}','Use verified GlobalQuery.winners_exact on both families, feasible_objective on each competitor, and surjectivity of reparam from reparameterization to transport the universal global comparison. Competitors span every class/action index; no per-class-optimum shortcut.'),
('winning_classes',['winners_reparam','reparameterization'],Q+f', {G}winningClasses q {nb} = {G}winningClasses q bases','Use verified GlobalQuery.winning_classes membership equivalence. reparam preserves the class index definitionally and is bijective; undo also preserves it. Transport every winning action, keeping all tied class indices.'),
('winner_images',['winners_reparam','realize_reparam','reparameterization'],Q+f' (placed : M7.Action.Recipe N), ((∃ x ∈ {win(nb)}, {rz(nb,"x")} = placed) ↔ ∃ x ∈ {win("bases")}, {rz("bases","x")} = placed)','Transport witnesses by reparam and its explicit undo, using winners_reparam and realize_reparam. This is equality of physical winner-image sets, not equality of redundant action encodings.'),
('presentation_images',['winner_images'],Q+f' (placed : M7.Action.Recipe N), ((∃ x : {I}, {pr(nb,"x")} ∧ {rz(nb,"x")} = placed) ↔ ∃ x : {I}, {pr("bases","x")} ∧ {rz("bases","x")} = placed)','For each family, presented physical images equal winning physical images: present implies winner by definition; conversely apply verified GlobalQuery.same_class_presentation to any winning index and use its realizing equality. Then use winner_images. Least action indices may change after rebasing, so only the actual physical-image sets are equated. No separation/coverage/full-transversal hypothesis is needed.')]
nodes=[{'id':i,'dependencies':ds,'spec':{'name':S+i,'statement':st,'imports':['M7QueryRebase','M7ActionAccepted','M7GlobalQueryAccepted'],'context':'','queries':['finite group action inverse composition bijection'],'guidance':gd+' Return tactic lines without leading by; preserve exact target and default limits.'},'metadata':{'source_section':'M7 original §8/9 raw-presentation comparison through actual class actions','fallback_queries':['algebra']}}for i,ds,st,gd in rows];source=Path('/home/jing/quantum_code_discovery_proof/research_checkpoints/m7_compact_selector_final_20260915/PROOF.md');g={'title':'M7 actual base-action reparameterization of global queries','source':str(source),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'scope':'Literal query equivalence under independently rebasing each stored class by an actual action; preserves all global winning classes/actions via a bijection and the physical winner/presentation image sets. No complete-family or distance-invariance hypothesis.','nodes':nodes};(H/'graph.json').write_text(json.dumps(g,ensure_ascii=False,indent=2)+'\n');s='import M7QueryRebase\nimport M7ActionAccepted\nimport M7GlobalQueryAccepted\n\n'
for i,ds,st,gd in rows:s+='noncomputable def M7.QueryRebaseTarget.'+i+' : Prop :=\n  '+st+'\n\n#check M7.QueryRebaseTarget.'+i+'\n\n'
for d in [P,H/'lean']:(d/'GraphPreflight.lean').write_text(s)
