from pathlib import Path
import json,hashlib
H=Path(__file__).resolve().parent;P=Path('/home/jing/m7-lean-actual-presentation-formalization');S='M7.ActualPresentation.';A='∀ (N : ℕ) [NeZero N]';R='M7.Action.Record N';C='M7.Action.Recipe N';E=S+'Encoded N';G=A+f' (c : {C}) (m : ℕ) (feasible : {C} → Prop) (objective : {C} → Fin m → ℤ) (mode : M7.Selection.Mode)';sel=S+'selected c feasible objective mode';pr=S+'present c feasible objective mode';rows=[
('decode_encode',[],A+f' (g : {R}), {S}decode ({S}encode g) = g','Destructure the actual four-field action record. Unit and exchange fields are unchanged; ZMod.natCast_zmod_val recovers each shift. No group law or distance invariant is assumed.'),
('encode_decode',[],A+f' (a : {E}), {S}encode ({S}decode a) = a','Destructure both nested Lex pairs and UnitKey. Each finite shift returns from its natural-code cast using ZMod.val_natCast and Nat.mod_eq_of_lt from Fin.isLt; use Fin.ext. This proves a genuine full action encoding equivalence including N=1.'),
('four_field_order',[],A+f' (g h : {R}), ({S}encode g ≤ {S}encode h ↔ (g.unit : ZMod N).val < (h.unit : ZMod N).val ∨ (g.unit : ZMod N).val = (h.unit : ZMod N).val ∧ (g.exchange < h.exchange ∨ g.exchange = h.exchange ∧ (g.leftShift.val < h.leftShift.val ∨ g.leftShift.val = h.leftShift.val ∧ g.rightShift.val ≤ h.rightShift.val)))','Unfold encode and nested Prod.Lex.toLex_le_toLex. UnitKey order is explicitly lifted from unit.val; equality of unit codes iff unit equality uses ZMod.val_injective and Units.ext. Fin comparisons use their natural val. This is exactly the original four-field lex order, not product partial order.'),
('realize_decode',[],A+f' (c : {C}) (a : {E}), M7.Presentation.realize ({S}leftImage c) ({S}rightImage c) a = M7.Action.act ({S}decode a) c','The two actual affine images are exactly the generic left/right realization by definition. Unfold realize,leftImage,rightImage,decode,act; both fields agree, including exchange.'),
('domain_univ',[],A+f', M7.Presentation.domain (Finset.univ : Finset ({S}Outer N)) (Finset.univ : Finset (Fin N)) (Finset.univ : Finset (Fin N)) = (Finset.univ : Finset ({E}))','Use the accepted generic domain_membership and Finset.ext; all three coordinate memberships are in univ. This is finite action-record enumeration, not structural support-pair generation.'),
('leastAction_spec',['decode_encode','encode_decode','realize_decode','domain_univ'],A+f' (c q : {C}), (∀ g : {R}, {S}leastAction c q = some g ↔ M7.Action.act g c = q ∧ ∀ h : {R}, M7.Action.act h c = q → {S}encode g ≤ {S}encode h) ∧ ({S}leastAction c q = none ↔ ¬ ∃ g : {R}, M7.Action.act g c = q)','Instantiate accepted targetLeast_spec with the actual Outer/FinN domains and left/right affine image functions. Rewrite domain_univ and realize_decode. encode/decode are inverse, so Option.map decode preserves the exact least-preimage specification; use encode g to transport any actual record back to the encoded domain. Algorithm remains factorized.'),
('winning_fiber',[],G+f' (g h : {R}), M7.Action.act g c = M7.Action.act h c → (g ∈ {sel} ↔ h ∈ {sel})','Unfold actual selected and use accepted M7.Selection.selector_exact, or its win_sound_complete predicate. Both feasibility and objective are functions of the literal realized recipe. Same physical pair implies the same comparisons. This does not assume action-invariance of an unconnected label.'),
('presentation_exact',['leastAction_spec','winning_fiber'],G+f' (g : {R}), g ∈ {sel} → ∃! h : {R}, {pr} h ∧ M7.Action.act h c = M7.Action.act g c','leastAction at the winning image has a preimage, hence is some h by leastAction_spec. It has the same literal image, so winning_fiber makes h winning; it is present by its leastAction equality. Any other present record with that image gives the same Option result, hence uniqueness. Every actual tied presentation is returned once.'),
('presentation_sound',['leastAction_spec'],G+f' (g : {R}), {pr} g → g ∈ {sel} ∧ ∀ h : {R}, M7.Action.act h c = M7.Action.act g c → {S}encode g ≤ {S}encode h','Unfold present; retain actual winning membership and apply leastAction_spec to get least-preimage minimality. No default-query label hypothesis is added here; the next batch instantiates feasible/objective with literal signature, locality and actual M6 distance.')]
nodes=[{'id':i,'dependencies':ds,'spec':{'name':S+i,'statement':st,'imports':['M7ActualPresentation','M7PresentationAccepted'],'context':'','queries':['finite set minimum lexicographic order'],'guidance':gd+' Return tactic proof lines without leading by; preserve exact target and default limits.'},'metadata':{'source_section':'M7 original §9 actual four-field record and literal supports','fallback_queries':['algebra']}} for i,ds,st,gd in rows];source=Path('/home/jing/quantum_code_discovery_proof/research_checkpoints/m7_compact_selector_final_20260915/PROOF.md');g={'title':'M7 actual four-field factorized presentation reconstruction','source':str(source),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'scope':'Explicit actual Record encoding equivalence and four-field order; factorized leastAction realizes literal supports and returns each actual winning image once. Default query bindings are a separate batch.','nodes':nodes};(H/'graph.json').write_text(json.dumps(g,ensure_ascii=False,indent=2)+'\n');s='import M7ActualPresentation\nimport M7PresentationAccepted\n\n'
for i,ds,st,gd in rows:s+='noncomputable def M7.ActualPresentationTarget.'+i+' : Prop :=\n  '+st+'\n\n#check M7.ActualPresentationTarget.'+i+'\n\n'
for d in [H/'lean',P]:(d/'GraphPreflight.lean').write_text(s)
